### ISSUE TITLE
Move code from hpp to cpp

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#100]

**Comment by pmoulon** [comment]
Can you tell for which module and why?
Having header only files is not really a problem.
It can just make compile time longer.. but make module file easier to use for third party projects..

**Comment by fabiencastan** [comment]
Yes, the goal is to reduce the build time especially when you are developing. Coding many stuff in headers invalidate **a lot** of code for nothing. For third party usage, we already have compiled modules, so IMHO it will not change much.
Why is it a problem to have more builded modules?

**Comment by pmoulon** [comment]
It's not a problem but you know some third party like Eigen are header only and efficient.
But an analysis of which header files make the more compilation time would be great.
Did you know any tool(s) that allow to know which headers are the bottleneck?

**Comment by fabiencastan** [comment]
Yes, Eigen doesn't require linking and that's useful because it simplifies library usage. But having an header only library is not the ambition of openMVG, and having 3 or 7 compiled modules doesn't really change much for 3rd party usage. On the other hand, having a good split between hpp and cpp can reduce a lot the compile time for all openMVG developpers.

I don't know any tool for global build statistics. But there are small tools to help cleaning the code to reduce includes propagation. I have used [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) and [cppclean](https://github.com/myint/cppclean) a long time ago.
[Why IWYU?](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md)

**Comment by simogasp** [comment]
Just for the sake of the argument, the modules that are header only (and so a new module definition is required) are:

* cameras [numeric, geometry, stl]
* color harmonization [linearProgramming, image, matching, features]
* geometry [multiview, linearProgramming, robust_estimation, numeric ]
* graph
* robust estimation [numeric, features, matching, cameras]
* stl
* tracks [matching]

The [ ] are the internal module dependencies (got it using a simple grep include, maybe not 100% reliable)

@pmoulon Is/was there a criterium on which you decided whether to make it hpp only or not? That would help to better understand the needs.

Also i created the graph of the  [module dependencies](https://gist.github.com/simogasp/ba6c8e2024a96065243b) in which I added the above ones (red ellipses). I lacks of the dependencies of the existing modules towards the header only ones though.

**Comment by simogasp** [comment]
[dep.pdf](https://github.com/poparteu/openMVG/files/108330/dep.pdf)
with an image it's maybe better

**Comment by pmoulon** [comment]
My criteria was (reasonable):
 - if the module use template only method, => header only module,
 - if the module is so tiny that it provides only some basic functionality that can be seen as independent from openMVG (like stl extensions) => header only module.

My ultimate goal is to make OpenMVG powerful, understandable and easy to use. And it don't consists in making a complex system to use and build.

As you said @simogasp each contributor have it's own idea of what the library should be...
My initial intuition was to make each module as independent as possible to make it's usage the more spreadable as possible.
As said on the main openMVG page:
  *The openMVG credo is: "Keep it simple, keep it maintainable". OpenMVG targets readable code that is easy to use and modify by the community.*

Note: Boost & Eigen are two library that have shown that header only library is not a problem even in complex applications. 
My concern is to focus on features and usability and not on compilation time ;-)

**Comment by fabiencastan** [comment]
I'm really surprised by your reaction, the idea was to clean the code progressively to make it more consistent, to reduce compilation time and to "keep it maintainable". I understand that you prefer to focus on features instead of doing this boring job, but we propose to contribute on that. I disagree that it's over-engineering. Cleaning the code progressively and defining clear rules is important to help all contributors to navigate through the code.
Cleaning include dependencies becomes harder and harder over time because all files get a lot of indirect includes and they succeed to compile due to all those indirect includes instead of declaring them explicitely.

The other point behind this issue was to remove all the "static" methods from headers. "static" keyword means internal linkage (only accessible in one translation unit), so it should not be used in header files because all those functions are duplicated in each translation unit.

I agree on the ambition of making OpenMVG powerful, understandable and easy to use. The ambition of this task was to contribute on that. But if you are convinced that keeping all the code in header files is a good thing, we can keep it as is.

**Comment by pmoulon** [comment]
I just tried to put openMVG_tracks and openMVG_geometry to cpp files and the build time remains exactly the same.

**Comment by cpichard** [comment]
Hi,

Just to jump into the conversation, there is a gcc option "-ftime-report" that can give you statistics about the times and resources spent during the different stages of the compilation. I ran a compilation with this option and the results are enclosed in the file compilation_times.txt.zip
[compilation_times.txt.zip](https://github.com/poparteu/openMVG/files/115494/compilation_times.txt.zip)
.
Even if I am not totally sure how to interpret correctly the numbers, the template instanciation part seems quite high for some files, this can give you some hints on where to freshen up the code if you want to.

I found a good explanation about slow compilation time on stackoverflow:
http://stackoverflow.com/questions/28919285/identify-slow-to-compile-function

Hope that helps,

**Comment by pmoulon** [comment]
Thanks @cpichard 
It will help to see which files take the more time to be compiled.

It would be interesting to list the files that take the longer time to be compiled.

```Perhaps the main compilation bottleneck is when numeric.h is included somewhere.```
