### ISSUE TITLE
Running fault: SIGSEGV, Segmentation fault during runing aliceVision_imageMatching

### ISSUE THREAD

**Issue by hzhshok** [alicevision/AliceVision#1000]
Hello, 
i got segmentation fault(core dump) as the following when running meshroom during imagematching phase.

**Meshroom log: and i also got GDB stack with the command line see the last section.**
- commandLine: aliceVision_imageMatching  --input "/tmp/MeshroomCache/CameraInit/bfaf7634159a5d41dae8a977e2ad39cc0e03298a/cameraInit.sfm" --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/c048c9bffa9214034a1257710d55cf3b34745b60" --method VocabularyTree --tree "" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel debug --output "/tmp/MeshroomCache/ImageMatching/8429df661129d8494f267e77b2c6ecebde5d92f8/imageMatches.txt"
 - logFile: /tmp/MeshroomCache/ImageMatching/8429df661129d8494f267e77b2c6ecebde5d92f8/log
[2021-03-02 16:49:02,470][ERROR] Error on node computation: Error on node "ImageMatching_1":
Log:
Program called with the following parameters:
 * featuresFolders =  = [/tmp/MeshroomCache/FeatureExtraction/c048c9bffa9214034a1257710d55cf3b34745b60]
 * input = "/tmp/MeshroomCache/CameraInit/bfaf7634159a5d41dae8a977e2ad39cc0e03298a/cameraInit.sfm"
 * matchingMode = "a/a" (default)
 * maxDescriptors = 500
 * method =  Unknown Type "20EImageMatchingMethod"
 * minNbImages = 200
 * nbMatches = 50
 * nbNeighbors = 50 (default)
 * output = "/tmp/MeshroomCache/ImageMatching/8429df661129d8494f267e77b2c6ecebde5d92f8/imageMatches.txt"
 * outputCombinedSfM = "" (default)
 * tree = ""
 * verboseLevel = "debug"
 * weights = ""

[16:49:01.495405][warning] The number of intrinsics is incoherent:
[16:49:01.495837][warning] 2 intrinsics declared and 1 intrinsics used.
[16:49:01.495897][debug] Use EXHAUSTIVE method instead of VOCABULARYTREE (less images than minNbImages).
[16:49:01.495916][info] Use EXHAUSTIVE method.
[16:49:01.495971][info] Number of selected image pairs: 15
[16:49:01.496074][info] pairList exported in: /tmp/MeshroomCache/ImageMatching/8429df661129d8494f267e77b2c6ecebde5d92f8/imageMatches.txt
Segmentation fault (core dumped)

**GDB showed:**
(gdb) set args --input "/tmp/MeshroomCache/CameraInit/14f9b41c9c1614bf62541ed308584e3ec8451911/cameraInit.sfm" --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/bf6b9eb7d0d02b05132419303f07c34ceae59f6b" --method VocabularyTree --tree "" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel debug --output "/tmp/MeshroomCache/ImageMatching/b8422ea5af7cbef61ec6633f4ba8ee39c8175f7f/imageMatches.txt"
(gdb) r
Starting program: /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/aliceVision_imageMatching --input "/tmp/MeshroomCache/CameraInit/14f9b41c9c1614bf62541ed308584e3ec8451911/cameraInit.sfm" --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/bf6b9eb7d0d02b05132419303f07c34ceae59f6b" --method VocabularyTree --tree "" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel debug --output "/tmp/MeshroomCache/ImageMatching/b8422ea5af7cbef61ec6633f4ba8ee39c8175f7f/imageMatches.txt"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe6174700 (LWP 168412)]
[New Thread 0x7fffe3973700 (LWP 168413)]
[New Thread 0x7fffe1172700 (LWP 168414)]
[New Thread 0x7fffe0971700 (LWP 168415)]
[New Thread 0x7fffdc170700 (LWP 168416)]
[New Thread 0x7fffd996f700 (LWP 168417)]
[New Thread 0x7fffd716e700 (LWP 168418)]
[New Thread 0x7fffd496d700 (LWP 168419)]
[New Thread 0x7fffd216c700 (LWP 168420)]
[New Thread 0x7fffcf96b700 (LWP 168421)]
[New Thread 0x7fffcd16a700 (LWP 168422)]
[New Thread 0x7fffca969700 (LWP 168423)]
[New Thread 0x7fffc8168700 (LWP 168424)]
[New Thread 0x7fffc5967700 (LWP 168425)]
[New Thread 0x7fffc3166700 (LWP 168426)]
[New Thread 0x7fffc0965700 (LWP 168427)]
[New Thread 0x7fffbe164700 (LWP 168428)]
[New Thread 0x7fffbb963700 (LWP 168429)]
[New Thread 0x7fffb9162700 (LWP 168430)]
[New Thread 0x7fffb6961700 (LWP 168431)]
[New Thread 0x7fffb4160700 (LWP 168432)]
[New Thread 0x7fffb195f700 (LWP 168433)]
[New Thread 0x7fffaf15e700 (LWP 168434)]
Program called with the following parameters:
 * featuresFolders =  = [/tmp/MeshroomCache/FeatureExtraction/bf6b9eb7d0d02b05132419303f07c34ceae59f6b]
 * input = "/tmp/MeshroomCache/CameraInit/14f9b41c9c1614bf62541ed308584e3ec8451911/cameraInit.sfm"
 * matchingMode = "a/a" (default)
 * maxDescriptors = 500
 * method =  Unknown Type "20EImageMatchingMethod"
 * minNbImages = 200
 * nbMatches = 50
 * nbNeighbors = 50 (default)
 * output = "/tmp/MeshroomCache/ImageMatching/b8422ea5af7cbef61ec6633f4ba8ee39c8175f7f/imageMatches.txt"
 * outputCombinedSfM = "" (default)
 * tree = ""
 * verboseLevel = "debug"
 * weights = ""

[16:17:07.565251][debug] Use EXHAUSTIVE method instead of VOCABULARYTREE (less images than minNbImages).
[16:17:07.565716][info] Use EXHAUSTIVE method.
[16:17:07.565773][info] Number of selected image pairs: 3
[16:17:07.565952][info] pairList exported in: /tmp/MeshroomCache/ImageMatching/b8422ea5af7cbef61ec6633f4ba8ee39c8175f7f/imageMatches.txt

Thread 1 "aliceVision_ima" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x40) at malloc.c:3102
3102	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x40) at malloc.c:3102
#1  0x00005555556d96f1 in Eigen::internal::handmade_aligned_free (ptr=0x5555574d8540)
    at /usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:98
#2  0x00005555556d9710 in Eigen::internal::aligned_free (ptr=0x5555574d8540)
    at /usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:179
#3  0x00007ffff782aaf0 in Eigen::aligned_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::deallocate (this=0x7fffffffd540, p=0x5555574d8540) at /usr/local/include/eigen3/Eigen/src/Core/util/Memory.h:763
#4  0x00007ffff78271d2 in std::allocator_traits<Eigen::aligned_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > > >::deallocate (__a=..., __p=0x5555574d8540, __n=1)
    at /usr/include/c++/9/bits/alloc_traits.h:333
#5  0x00007ffff7822745 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > >, std::less<unsigned int>, Eigen::aligned_allocator<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::_M_put_node (
    this=0x7fffffffd540, __p=0x5555574d8540) at /usr/include/c++/9/bits/stl_tree.h:584
#6  0x00007ffff781d734 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > >, std::less<unsigned int>, Eigen::aligned_allocator<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::_M_drop_node (
    this=0x7fffffffd540, __p=0x5555574d8540) at /usr/include/c++/9/bits/stl_tree.h:651
#7  0x00007ffff7818554 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > >, std::less<unsigned int>, Eigen::aligned_allocator<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::_M_erase (
    this=0x7fffffffd540, __x=0x5555574d8540) at /usr/include/c++/9/bits/stl_tree.h:1915
#8  0x00007ffff781441c in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > >, std::less<unsigned int>, Eigen::aligned_allocator<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::~_Rb_tree (
    this=0x7fffffffd540, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_tree.h:995
#9  0x00007ffff781134a in std::map<unsigned int, std::shared_ptr<aliceVision::camera::IntrinsicBase>, std::less<unsigned int>, Eigen::aligned_allocator<std::pair<unsigned int const, std::shared_ptr<aliceVision::camera::IntrinsicBase> > > >::~map (this=0x7fffffffd540, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_map.h:300
#10 0x00007ffff3df3556 in aliceVision::sfmData::SfMData::~SfMData (this=0x7fffffffd510, __in_chrg=<optimized out>)
    at /home/xx/workshop/prj/opensource/AliceVision/AliceVision/src/aliceVision/sfmData/SfMData.cpp:27
#11 0x00005555556d7c2a in aliceVision_main (argc=21, argv=0x7fffffffdcb8)
--Type <RET> for more, q to quit, c to continue without paging--AA
    at /home/xx/workshop/prj/opensource/AliceVision/AliceVision/src/software/pipeline/main_imageMatching.cpp:702
#12 0x00005555556d26bc in main (argc=21, argv=0x7fffffffdcb8)
    at /home/xx/workshop/prj/opensource/AliceVision/AliceVision/src/aliceVision/system/main.hpp:37

**Also dump the used SO  libraries:**
From                To                  Syms Read   Shared Object Library
0x00007ffff7fd0100  0x00007ffff7ff2674  Yes (*)     /lib64/ld-linux-x86-64.so.2
0x00007ffff77722f0  0x00007ffff7bcfd9d  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_sfm.so.2
0x00007ffff66c9c20  0x00007ffff6810c22  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_sfmDataIO.so.2
0x00007ffff62e8150  0x00007ffff630eb04  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_voctree.so.2
0x00007ffff61dbbf0  0x00007ffff622babc  Yes (*)     /lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0
0x00007ffff619fbb0  0x00007ffff61ae79c  Yes (*)     /lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0
0x00007ffff616ce40  0x00007ffff617d80c  Yes (*)     /lib/x86_64-linux-gnu/libglog.so.0
0x00007ffff6147ae0  0x00007ffff61574d5  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007ffff61171c0  0x00007ffff6137d97  Yes (*)     /lib/x86_64-linux-gnu/libcxsparse.so.3
0x00007ffff60366e0  0x00007ffff6102182  Yes (*)     /lib/x86_64-linux-gnu/libcholmod.so.3
0x00007ffff3fa3000  0x00007ffff5e8b490  Yes (*)     /lib/x86_64-linux-gnu/libopenblas.so.0
0x00007ffff3df31a0  0x00007ffff3e5703a  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_sfmData.so.2
0x00007ffff3caa7f0  0x00007ffff3ccac15  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_system.so.2
0x00007ffff3b792d0  0x00007ffff3bf268a  Yes (*)     /lib/x86_64-linux-gnu/libboost_log.so.1.71.0
0x00007ffff39e91a0  0x00007ffff3ad0e32  Yes (*)     /lib/x86_64-linux-gnu/libstdc++.so.6
0x00007ffff380b3c0  0x00007ffff38b1f18  Yes         /lib/x86_64-linux-gnu/libm.so.6
0x00007ffff37c36d0  0x00007ffff37ed5d2  Yes (*)     /lib/x86_64-linux-gnu/libgomp.so.1
0x00007ffff37a25e0  0x00007ffff37b3045  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007ffff35d0630  0x00007ffff374520d  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007ffff2af7190  0x00007ffff30abcb4  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_multiview.so.2
0x00007ffff1c1c0c0  0x00007ffff1c4763a  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_track.so.2
0x00007ffff1851fc0  0x00007ffff1b2c008  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_lInftyComputerVision.so.2
0x00007ffff175e1e0  0x00007ffff176404a  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/lib--Type <RET> for more, q to quit, c to continue without paging--
aliceVision_robustEstimation.so.2
0x00007ffff1536e30  0x00007ffff167809c  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_matching.so.2
0x00007ffff10dcb20  0x00007ffff119fe16  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_geometry.so.2
0x00007ffff0cd6ef0  0x00007ffff0d6dde8  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_feature.so.2
0x00007ffff0a654c0  0x00007ffff0acaaa4  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_numeric.so.2
0x00007ffff07cf3f0  0x00007ffff088b9c9  Yes (*)     /lib/x86_64-linux-gnu/libboost_regex.so.1.71.0
0x00007ffff05c3610  0x00007ffff071392d  Yes (*)     /usr/local/lib/libAlembic.so.1.7
0x00007ffff0423b90  0x00007ffff0469e4d  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libaliceVision_image.so.2
0x00007ffff0332a20  0x00007ffff0350b5b  Yes (*)     /lib/x86_64-linux-gnu/libgflags.so.2.2
0x00007ffff0312200  0x00007ffff0319de8  Yes (*)     /lib/x86_64-linux-gnu/libunwind.so.8
0x00007ffff03060a0  0x00007ffff030be09  Yes (*)     /lib/x86_64-linux-gnu/libamd.so.2
0x00007ffff02fb080  0x00007ffff02ff683  Yes (*)     /lib/x86_64-linux-gnu/libcolamd.so.2
0x00007ffff02f60a0  0x00007ffff02f6813  Yes (*)     /lib/x86_64-linux-gnu/libsuitesparseconfig.so.5
0x00007ffff02e9080  0x00007ffff02f04e8  Yes (*)     /lib/x86_64-linux-gnu/libccolamd.so.2
0x00007ffff02dd0c0  0x00007ffff02e3b39  Yes (*)     /lib/x86_64-linux-gnu/libcamd.so.2
0x00007ffff007a5f0  0x00007ffff00c8fd3  Yes (*)     /lib/x86_64-linux-gnu/libmetis.so.5
0x00007fffef9d2ef0  0x00007fffeff77e8e  Yes (*)     /usr/local/lib/liblapack.so.3
0x00007fffef95a100  0x00007fffef9a6f3e  Yes (*)     /usr/local/lib/libblas.so.3
0x00007fffef6af160  0x00007fffef921819  Yes (*)     /lib/x86_64-linux-gnu/libgfortran.so.5
0x00007fffef672ba0  0x00007fffef684d4c  Yes (*)     /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
0x00007fffef65c720  0x00007fffef65fd70  Yes         /lib/x86_64-linux-gnu/librt.so.1
0x00007fffef654220  0x00007fffef655179  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x00007fffef629d20  0x00007fffef64a5e7  Yes         /home/xx/workshop/prj/opensource/AliceVision/AliceVision/build/Linux-x86_64/libvlsift.so.2
0x00007fffef412ae0  0x00007fffef58a17b  Yes (*)     /lib/x86_64-linux-gnu/libicui18n.so.66
0x00007fffef1a4920  0x00007fffef288897  Yes (*)     /lib/x86_64-linux-gnu/libicuuc.so.66
0x00007fffef1312e0  0x00007fffef135fa0  Yes (*)     /lib/x86_64-linux-gnu/libIex-2_3.so.24
--Type <RET> for more, q to quit, c to continue without paging--
0x00007fffef0da100  0x00007fffef0da636  Yes (*)     /lib/x86_64-linux-gnu/libHalf.so.24
0x00007fffee6714c0  0x00007fffeef43456  Yes (*)     /usr/local/lib/libOpenImageIO.so.2.3.2
0x00007fffee59c3c0  0x00007fffee5b33a6  Yes (*)     /lib/x86_64-linux-gnu/liblzma.so.5
0x00007fffee552a80  0x00007fffee57eecd  Yes (*)     /lib/x86_64-linux-gnu/libquadmath.so.0
0x00007fffeca8f040  0x00007fffeca8f0f9  Yes (*)     /lib/x86_64-linux-gnu/libicudata.so.66
0x00007fffec7e9f00  0x00007fffec87de7a  Yes (*)     /lib/x86_64-linux-gnu/libIlmImf-2_3.so.24
0x00007fffec7945e0  0x00007fffec7a4edc  Yes (*)     /usr/local/lib/libz.so.1
0x00007fffeb797900  0x00007fffec408391  Yes (*)     /usr/local/lib/libopencv_core.so.4.1
0x00007fffe90f6740  0x00007fffeb21cda0  Yes (*)     /usr/local/lib/libopencv_imgproc.so.4.1
0x00007fffe8f52420  0x00007fffe8f8d497  Yes (*)     /usr/local/lib/libopencv_videoio.so.4.1
0x00007fffe7cb9890  0x00007fffe8421a6e  Yes (*)     /usr/local/lib/libavcodec.so.57
0x00007fffe7a64420  0x00007fffe7bc7ad5  Yes (*)     /usr/local/lib/libavformat.so.57
0x00007fffe79c19c0  0x00007fffe79f783a  Yes (*)     /usr/local/lib/libavutil.so.55
0x00007fffe79373c0  0x00007fffe7999c1c  Yes (*)     /usr/local/lib/libswscale.so.4
0x00007fffe792c280  0x00007fffe7930926  Yes (*)     /lib/x86_64-linux-gnu/libgif.so.7
0x00007fffe78ed210  0x00007fffe791cc77  Yes (*)     /usr/local/lib/libpng16.so.16
0x00007fffe78779e0  0x00007fffe78ba477  Yes (*)     /usr/local/lib/libjpeg.so.62
0x00007fffe781e530  0x00007fffe785ebe7  Yes (*)     /lib/x86_64-linux-gnu/libopenjp2.so.7
0x00007fffe7712660  0x00007fffe77a744e  Yes (*)     /usr/local/lib/libraw_r.so.20
0x00007fffe7676fe0  0x00007fffe76bb7d5  Yes         /usr/local/lib/libtiff.so.5
0x00007fffe7405070  0x00007fffe74561d4  Yes (*)     /lib/x86_64-linux-gnu/libwebp.so.6
0x00007fffe71feca0  0x00007fffe7200952  Yes (*)     /lib/x86_64-linux-gnu/libwebpdemux.so.2
0x00007fffe714b790  0x00007fffe71ca205  Yes (*)     /lib/x86_64-linux-gnu/libfreetype.so.6
0x00007fffe71374a0  0x00007fffe7138ec5  Yes (*)     /lib/x86_64-linux-gnu/libIlmThread-2_3.so.24
0x00007fffe6ae3f80  0x00007fffe7058622  Yes (*)     /usr/local/lib/libopencv_imgcodecs.so.4.1
0x00007fffe6a139e0  0x00007fffe6a3491c  Yes (*)     /lib/x86_64-linux-gnu/libdc1394.so.22
0x00007fffe69f7400  0x00007fffe6a039e5  Yes (*)     /usr/local/lib/libswresample.so.2
0x00007fffe67424b0  0x00007fffe68bcef7  Yes (*)     /lib/x86_64-linux-gnu/libx264.so.155
0x00007fffe668f240  0x00007fffe6720d0a  Yes (*)     /lib/x86_64-linux-gnu/libzstd.so.1
0x00007fffe647e0a0  0x00007fffe64865b5  Yes (*)     /lib/x86_64-linux-gnu/libjbig.so.0
0x00007fffe63fc540  0x00007fffe643f469  Yes (*)     /lib/x86_64-linux-gnu/libjpeg.so.8
0x00007fffe61ec570  0x00007fffe61f382e  Yes (*)     /lib/x86_64-linux-gnu/libraw1394.so.11
--Type <RET> for more, q to quit, c to continue without paging--
0x00007fffe61d1b00  0x00007fffe61de89c  Yes (*)     /lib/x86_64-linux-gnu/libusb-1.0.so.0
0x00007fffe61a3fe0  0x00007fffe61be4f0  Yes (*)     /lib/x86_64-linux-gnu/libudev.so.1

Thanks for your comments!

Regards

**Comment by wangziji** [comment]
I have the same issue, any solution?
