### ISSUE TITLE
: error while loading shared libraries: libswresample.so.3: 

### ISSUE THREAD

**Issue by jochenstier** [alicevision/AliceVision#1014]
Hello, 

I installed aliceVision using the "Building the project with embedded dependencies" path described in the Install.md on Ubuntu 18.04. Here is the exact sequence of commands I used:

snap install cmake --classic
sudo apt-get install gfortran

sudo apt-get install -y nasm
sudo apt-get install m4
sudo apt-get install libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev

git clone https://github.com/alicevision/AliceVision.git --recursive
mkdir build 
cd build
cmake -DALICEVISION_BUILD_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=$PWD/../install ../AliceVision
make

The compile went all the way through with a few warnings and created a number of directories including /install/bin and /install/lib. The first thing I tired was to see if one of the executables would start and just typed 

>./aliceVision_cameraInit

in the /install/bin. The result was the following error. 

: error while loading shared libraries: libswresample.so.3: cannot open shared object file: No such file or directory. 

Then it tried

>ldd aliceVision_cameraInit 

which produced the following output:

        linux-vdso.so.1 (0x00007fff6b59d000)
        libaliceVision_sensorDB.so.2 => /root/install/bin/./../lib/libaliceVision_sensorDB.so.2 (0x00007fc6d15d0000)
        libaliceVision_sfmDataIO.so.2 => /root/install/bin/./../lib/libaliceVision_sfmDataIO.so.2 (0x00007fc6d12c0000)
        libboost_program_options.so.1.70.0 => /root/install/bin/./../lib/libboost_program_options.so.1.70.0 (0x00007fc6d103d000)
        libboost_filesystem.so.1.70.0 => /root/install/bin/./../lib/libboost_filesystem.so.1.70.0 (0x00007fc6d0e22000)
        libaliceVision_sfmData.so.2 => /root/install/bin/./../lib/libaliceVision_sfmData.so.2 (0x00007fc6d0be2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc6d09c3000)
        libOpenImageIO.so.2.2 => /root/install/bin/./../lib/libOpenImageIO.so.2.2 (0x00007fc6cfdbf000)
        libaliceVision_system.so.2 => /root/install/bin/./../lib/libaliceVision_system.so.2 (0x00007fc6cfb87000)
        libboost_log.so.1.70.0 => /root/install/bin/./../lib/libboost_log.so.1.70.0 (0x00007fc6cf894000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc6cf50b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc6cf16d000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fc6cef3e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc6ced26000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc6ce935000)
        libboost_regex.so.1.70.0 => /root/install/bin/./../lib/../lib/libboost_regex.so.1.70.0 (0x00007fc6ce679000)
        libAlembic.so.1.7 => /root/install/bin/./../lib/../lib/libAlembic.so.1.7 (0x00007fc6ce2b1000)
        libaliceVision_feature.so.2 => /root/install/bin/./../lib/../lib/libaliceVision_feature.so.2 (0x00007fc6ce029000)
        libaliceVision_image.so.2 => /root/install/bin/./../lib/../lib/libaliceVision_image.so.2 (0x00007fc6cdde9000)
        libaliceVision_numeric.so.2 => /root/install/bin/./../lib/../lib/libaliceVision_numeric.so.2 (0x00007fc6cdbcd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc6d1a54000)
        libIlmImf-2_5.so.25 => /root/install/lib/libIlmImf-2_5.so.25 (0x00007fc6cd6e5000)
        libImath-2_5.so.25 => /root/install/lib/libImath-2_5.so.25 (0x00007fc6cd4cc000)
        libHalf-2_5.so.25 => /root/install/lib/libHalf-2_5.so.25 (0x00007fc6cd289000)
        libIex-2_5.so.25 => /root/install/lib/libIex-2_5.so.25 (0x00007fc6cd01e000)
        libz.so.1 => /root/install/lib/libz.so.1 (0x00007fc6cce01000)
        libavcodec.so.58 => /root/install/lib/libavcodec.so.58 (0x00007fc6cb6d7000)
        libavformat.so.58 => /root/install/lib/libavformat.so.58 (0x00007fc6cb270000)
        libavutil.so.56 => /root/install/lib/libavutil.so.56 (0x00007fc6cadbf000)
        libswscale.so.5 => /root/install/lib/libswscale.so.5 (0x00007fc6cab31000)
        libpng16.so.16 => /root/install/lib/libpng16.so.16 (0x00007fc6ca8ee000)
        libjpeg.so.62 => /root/install/lib/libjpeg.so.62 (0x00007fc6ca657000)
        libraw_r.so.20 => /root/install/lib/libraw_r.so.20 (0x00007fc6ca33c000)
        libtiff.so.5 => /root/install/lib/libtiff.so.5 (0x00007fc6ca0d2000)
        libboost_thread.so.1.70.0 => /root/install/lib/libboost_thread.so.1.70.0 (0x00007fc6c9eae000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc6c9caa000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc6c9aa2000)
        libaliceVision_gpu.so.2 => /root/install/bin/./../lib/../lib/../lib/libaliceVision_gpu.so.2 (0x00007fc6c9897000)
        libvlsift.so.2 => /root/install/bin/./../lib/../lib/../lib/libvlsift.so.2 (0x00007fc6c9672000)
        libCCTag.so.1.0.0 => /root/install/bin/./../lib/../lib/../lib/libCCTag.so.1.0.0 (0x00007fc6c8eed000)
        libpopsift.so.1.0.0 => /root/install/bin/./../lib/../lib/../lib/libpopsift.so.1.0.0 (0x00007fc6c79a0000)
        libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007fc6c7711000)
        libopencv_features2d.so.4.5 => /root/install/bin/./../lib/../lib/../lib/libopencv_features2d.so.4.5 (0x00007fc6c744f000)
        libopencv_core.so.4.5 => /root/install/bin/./../lib/../lib/../lib/libopencv_core.so.4.5 (0x00007fc6c6344000)
        libIlmThread-2_5.so.25 => /root/install/lib/../lib/libIlmThread-2_5.so.25 (0x00007fc6c613c000)
        libswresample.so.3 => not found
        libvpx.so.6 => not found
        libboost_serialization.so.1.70.0 => not found
        libtbb.so.2 => not found
        libopencv_imgproc.so.4.5 => not found
        libopencv_flann.so.4.5 => /root/install/lib/libopencv_flann.so.4.5 (0x00007fc6c5ed4000)
        libopencv_imgproc.so.4.5 => /root/install/lib/libopencv_imgproc.so.4

libswresample.so.3 is not found, even though it is in /install/lib. The same is true for libboost_serialization.so.1.70.0 and libvpx.so.6. I am confused about the paths listed above. Some point directly to the files in /install/lib while others seem to have a longer path to the same directory and some are not found at all. I know that I could probably change the LIBRARY_PATH to include /install/lib but I wonder if this is not a rpath issue which should be defined during linking ? I am little rusty with Linux and would appreciate some help with this. 

Thanks!

**Comment by richa211200** [comment]
for Ubuntu:

if libavresample.so.3 is present in FFmpeg folder, please follow below steps:
sudo apt-get update
sudo apt-get install locate
locate libavresample.so.3
export LD_LIBRARY_PATH=/home/neoastra/FFmpeg/FFmpeg/libswresample/libswresample.so.3
sudo ldconfig

**Comment by AndreiCherniaev** [comment]
Still [the same](https://stackoverflow.com/questions/77096790/why-c-app-fail-because-of-shared-library) problem...
error while loading shared libraries: libswresample.so.4: cannot open shared object file: No such file or directory
