### ISSUE TITLE
KeyFrameSelecrion on Ubuntu18.04

### ISSUE THREAD

**Issue by littleanti** [alicevision/AliceVision#1020]
The KeyFrameSelection of meshroom prebuilt binary and library for linux is not working on ubuntu18.04.

In addition, docker build version's KeyFrameSelection of aliceVision is not working on ubuntu18.04.

Is there any update or issue number related on this situation? 

The log of KeyFrameSelection on ubuntu18.04 is "could not open file". 
I think this issue is related on opencv library of docker and prebuilt bin & library.

**Comment by natowi** [comment]
https://github.com/alicevision/AliceVision/issues/852
