### ISSUE TITLE
Error: gcc versions later than 9

### ISSUE THREAD

**Issue by mcginnly** [alicevision/AliceVision#1032]
Hi, I'm trying to compile from source on ubuntu 20.10 groovy gorilla.
I've finally got all the dependencies to a point where cmake runs without error.
When I 'make' it runs to 76% and then gives this error:

```
[ 76%] Building NVCC (Device) object src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 9 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  139 | #error -- unsupported GNU version! gcc versions later than 9 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
CMake Error at aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o.Release.cmake:220 (message):
  Error generating
  /home/russ/git-repos/build/src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/./aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o


make[2]: *** [src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/build.make:65: src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o] Error 1
make[2]: Leaving directory '/home/russ/git-repos/build'
make[1]: *** [CMakeFiles/Makefile2:3325: src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/all] Error 2
make[1]: Leaving directory '/home/russ/git-repos/build'
make: *** [Makefile:130: all] Error 2
```

Is it wise to use the nvcc flag mentioned "-allow-unsuported-compiler". And if so what do I type where and when? Is it when I'm running cmake, or do I need to edit a config file. (I know nothing about nvcc)

Many thanks
Russ

**Comment by simogasp** [comment]
which version of cuda are u using? Normally cuda >= 11.1 should support gcc versions higher than 9

In any case you can try to add the flag here
https://github.com/alicevision/AliceVision/blob/fbbce2886f8759f95c7836e12495817370606966/src/CMakeLists.txt#L770
like:
```cmake
set(CUDA_NVCC_FLAGS         "${CUDA_NVCC_FLAGS};--default-stream;legacy;-allow-unsupported-compiler")
```

**Comment by mcginnly** [comment]
wierdly, I have 11.2 installed:

```
russ@ubuntu20:~/git-repos/build$ nvidia-smi
Fri Apr 23 01:02:10 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 750 Ti  Off  | 00000000:01:00.0  On |                  N/A |
| 29%   40C    P0     3W /  38W |    234MiB /  2000MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3846      G   /usr/lib/xorg/Xorg                133MiB |
|    0   N/A  N/A      4000      G   /usr/bin/gnome-shell               68MiB |
|    0   N/A  N/A     95129      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A    112127      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A    217394      G   ...llation/ubuntu12_32/steam       10MiB |
|    0   N/A  N/A    217404      G   ./steamwebhelper                    1MiB |
|    0   N/A  N/A    217416      G   ...-token=432351394689190831        7MiB |
|    0   N/A  N/A    221680      G   /usr/bin/nvidia-settings            1MiB |
+-----------------------------------------------------------------------------+

It is still failing at 76% but giving some more information:
```

`[ 76%] Building NVCC (Device) object src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/c++/10/type_traits(1396): error: type name is not allowed

/usr/include/c++/10/type_traits(1396): error: type name is not allowed

/usr/include/c++/10/type_traits(1396): error: identifier "__is_same_as" is undefined

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6547): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6552): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6557): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6562): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6567): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=char, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6573): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=char, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6577): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=char, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6581): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6678): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6683): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6688): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6693): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6698): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6704): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6708): here

/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10/bits/basic_string.h(6712): here

19 errors detected in the compilation of "/home/russ/git-repos/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu".
CMake Error at aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/russ/git-repos/build/src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/./aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o


make[2]: *** [src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/build.make:65: src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/cuda/planeSweeping/aliceVision_depthMap_generated_plane_sweeping_cuda.cu.o] Error 1
make[2]: Leaving directory '/home/russ/git-repos/build'
make[1]: *** [CMakeFiles/Makefile2:3325: src/aliceVision/depthMap/CMakeFiles/aliceVision_depthMap.dir/all] Error 2
make[1]: Leaving directory '/home/russ/git-repos/build'
make: *** [Makefile:130: all] Error 2
```



```

**Comment by simogasp** [comment]
Are you sure you don't have another version of cuda installed that may conflict with 11.2? 
I'm running ubuntu 20.04, gcc 9.3 and cuda 11.2 and in my cuda version of `host_config.h` (which is not in `/usr/include` but in `/usr/local/cuda-11.2/targets/x86_64-linux/include/`) says:
```c++
#error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compila
tion failure or incorrect run time execution. Use at your own risk.
```

Can you go back at the cmake step and tell us which version is reported to be found during that step?
