### ISSUE TITLE
--help arguments out of date

### ISSUE THREAD

**Issue by Ambrosiussen** [alicevision/AliceVision#1037]
Hi,

I was recently updating the AliceVision integration in SideFX Houdini, and noticed that the --help printout did not get updated between the included binaries for Meshroom 2020 and 2021. An example is the alicevision_meshFiltering. Some missing arguments are:

--smoothingSubset
--smoothingBoundariesNeighbours
--smoothingIterations
--smoothingLambda
--filteringSubset
--filteringIterations
--filterLargeTrianglesFactor
--filterTrianglesRatio

Additionally, some arguments got removed but are still present in the help.

**Comment by fabiencastan** [comment]
Hi @Ambrosiussen !
I'm not sure to understand the problem or how it's possible. The documentation is generated from the arguments used:
See the code here: https://github.com/alicevision/AliceVision/blob/v2.4.0/src/software/pipeline/main_meshFiltering.cpp#L132
