### ISSUE TITLE
--boundingBox in aliceVision_meshing.exe

### ISSUE THREAD

**Issue by Ambrosiussen** [alicevision/AliceVision#1038]
Would it be possible to make note of the default measure of unit of the bounding box at scale 1,1,1 in the documentation?

Currently the help is limited to:
Specifies a bounding box to reconstruct: position, rotation (Euler ZXY) and scale.

I am hoping to feed a custom bounding box on commandline, but I don't know how to convert the unit sizes between eg Houdini/AliceVision. How big is the bounding box at default settings in meters?

**Comment by natowi** [comment]
> How big is the bounding box at default settings in meters?

The ratio can differ, that is why there is no mention of a "MR unit" ratio.
You would need to place cctags in your scene and scale the model first. Then you have consistent units you can work with.
(UI documentation https://github.com/alicevision/meshroom/wiki/CCTAG-scaling )

**Comment by Ambrosiussen** [comment]
Thanks for the suggestion.

I am running AV from Houdini (commandline). So I can see my initial pointcloud. I now create a Houdini box (1u = 1m) which I move to any position to isolate a set of points.

Once done, I extract the transformations of that box so that I can feed translate, rot, scale into AV using the correct format.
The problem however is not knowing what size that box is relative to what AV expects. In order to properly extract the transforms of my Houdini box, I need to know what measure of unit it is scaled against.

Notice in the images below that both the box in Houdini and Meshroom have default settings (rot, scale).
To get the box in Meshroom to be the same scale as in Houdini, my Houdini box would need to be scaled up (~10x?)

If the coordinate scale is unknown during computation, would it be possible to export some sort of reference size to disk which I can measure against? Eg a file that tells me that the default "box" in Meshroom is X units.

![AV_Box1](https://user-images.githubusercontent.com/23486196/117371276-75c5b100-ae7c-11eb-93b9-55eaecb34585.JPG)
![AV_Box2](https://user-images.githubusercontent.com/23486196/117371280-78c0a180-ae7c-11eb-9ac8-440b93a830b1.JPG)

**Comment by natowi** [comment]
**The coordinate system scale is 100mm per unit**. As Meshroom has no references by default, the model/point cloud is not correctly scaled within this coordinate system (But you should be able to create a BBox by applying the scaling factor). Here is a similar issue https://www.sidefx.com/forum/topic/42683/?page=1#post-199010

**Comment by Ambrosiussen** [comment]
Ah perfect! I misunderstood what you meant in your previous reply :) The BBox then appears to be 200x200x200mm by default, which is what I was after. Thanks for the help.
