### ISSUE TITLE
IlmBase::Imath, IlmBase::IlmThread, IlmBase::IexMath, IlmBase::IexMath can not be linked

### ISSUE THREAD

**Issue by HarrisZhou** [alicevision/AliceVision#1040]
I have sucessfully installed AliceVision in my system, but when I tried to target_link_libraries to aliceVision_image and aliceVision feature modules, IlmBase::Imath, IlmBase::IlmThread, IlmBase::IexMath, IlmBase::IexMathm can not be found and impose Cmake Error, all the other targets are linked successfuly though. How can I solve this problem?

**Comment by simogasp** [comment]
Are you using alicevision as third party?
If so, can you join the `AliceVisionTargets.cmake` file that is used to find alicevision.
It could, among other things, be related to this https://github.com/alembic/alembic/pull/337.

Also, which version of openexr did you use to build alicevision?

**Comment by HarrisZhou** [comment]
Hi simogasp, yes I am using alicevision as third party. The AliceVisionTargets.cmake file can be joined successfully.  Thank you for the solutions and I end up with adding find_package(IlmBase REQUIRED) to the root CMakelist. I am using openexr in version 2.5.0#2 from vcpkg
