### ISSUE TITLE
Error while installing on windows 10

### ISSUE THREAD

**Issue by ostepan2006** [alicevision/AliceVision#1059]
Hello. I have got error while installing process.  

command:

`vcpkg install geogram --triplet x64-windows`

or

`vcpkg install ceres[suitesparse,cxsparse] --triplet x64-windows`

The error strings are the followings: 

````
``
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
```
Error: Building package lapack:x64-windows failed with: BUILD_FAILED
```

**Comment by natowi** [comment]
I don´t know about this problem, but when I build AliceVision in the past, I used the following workflow:

1) Use vcpkg and Visual Studio 2017 (use x64 Native Tools Command Prompt for VS 2017, run as admin) Use the English language version only!

Install vcpkg install all vcpkg packages as described in the alicevision readme

2) 

```
cd [PATH-TO-FOLDER]

git clone --recursive https://github.com/alicevision/aliceVision.git

cd alicevision

mkdir build

cd build

set VCPKG_ROOT=C:\vcpkg

cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64
```

I made notes [here](https://github.com/natowi/meshroom_external_plugins/wiki/3-Build) maybe you find them useful.

I did not build alicevision for some time now, so I don´t know if this process still works smoothly

**Comment by ostepan2006** [comment]
@natowi thanks. I had solved this problem by updating MS Visual Studio 2017.

**Comment by natowi** [comment]
The build pipeline is really sensitive and slight changes can cause it to fail - that´s why I never touched my build pipeline again, once I got it up and running :D
I´m hoping we´ll get the nightly builds back up running, so it is easier to test out recent changes
