### ISSUE TITLE
Need examples of using AliceVision

### ISSUE THREAD

**Issue by ostepan2006** [alicevision/AliceVision#1064]
Hello. Could you provide me examples of using AliceVision? I know that Meshroom is one of that great project. But could you recommend me projects with code from wich  I could understand what AliceVision and Meshroom have inside? 
Thanks

**Comment by natowi** [comment]
> Hello. Could you provide me examples of using AliceVision?

You can simply run the Alicevision binaries from the command line.
https://github.com/alicevision/AliceVision/wiki/CLI-Parameters
To get examples, simply take a look in the cli window that meshroom opens in the background. Run a test reconstruction and observe which cli parameters are used by each node.

>But could you recommend me projects with code from which I could understand what AliceVision and Meshroom have inside?

I don´t know what you mean with that. 
Here is a high level overview of the technology stack:
https://youtu.be/7L6tj6MUP6M?t=935
And here is an explanation of the different methods and algorithms used:
https://www.youtube.com/watch?v=H69gpAm3SAY

**Comment by ostepan2006** [comment]
@natowi hello. Thanks for your reply and useful links. Could you give me a link to the Meshroom and AliceVision community site? Thanks

**Comment by natowi** [comment]
> Could you give me a link to the Meshroom and AliceVision community site?

https://github.com/alicevision/meshroom -> Discussions / Issues
https://github.com/alicevision/meshroom/wiki#how-to-get-help

**Comment by ostepan2006** [comment]
Thanks

**Comment by natowi** [comment]
If you have any other questions feel free to ask.
