### ISSUE TITLE
errors with alicevision on ubuntu via Houdini

### ISSUE THREAD

**Issue by frading** [alicevision/AliceVision#1070]
Hello,

This issue is related to Houdini Labs, but after a few emails with their support, they advised me to ask here as well.

So after downloading meshrom from sidefx tutorial page (https://www.sidefx.com/tutorials/alicevision-plugin/), as soon as I run their alicevision tool suite (on ubuntu), but I immediately get errors like those ones:

![alicevision_errors](https://user-images.githubusercontent.com/59701/124675629-e86eff00-deb4-11eb-8ce1-0fae7f924434.jpg)

So it seems that files that are in the lib folder are not found by the executables.

I attempted a work around by creating symlinks for each of the files that generated an error, such as this:

`libaliceVision_sensorDB.so.2 -> ../lib/libaliceVision_sensorDB.so.2`

and then alicevision appear to run fine, with only the following error this time:

![alicevision_error2](https://user-images.githubusercontent.com/59701/124675661-f6bd1b00-deb4-11eb-8e2a-91a11aafa748.jpg)

And while it generated a mesh, point clouds and camera transforms, I realised shortly after that the mesh did not have uvs, and therefore could not have the texture assigned properly. So maybe my workaround with symlinks just offset the problem. Here is another screenshot, for those familiar with houdini, with the generated geometry:

![alicevision_output](https://user-images.githubusercontent.com/59701/124675721-12c0bc80-deb5-11eb-987d-dfbc232fc0f8.jpg)

Would you have any advice on how to solve this?
Could it be that the linux prebuilt version for ubuntu is missing files or symlinks?
Happy to run more tests if that can help give more info.

**Comment by diorn** [comment]
Having the same issues here on Linux Mint

**Comment by natowi** [comment]
Sorry for the late reply. Does the alicevision standalone work? You can download the linux files here https://github.com/alicevision/meshroom/releases/tag/v2021.1.0 

Someone is working on a Flathub submisson https://github.com/alicevision/meshroom/releases/tag/v2021.1.0 which will simplify the AliceVision / Meshroom installation on Linux.

**Comment by frading** [comment]
hi @natowi. And yes, I confirm Meshroom works fine as a standalone.

**Comment by diorn** [comment]
Hello @natowi - yes, just pushed out some test scans on the standalone and it works well.

Albeit there is a slight issue, when requesting Meshroom to open the textures or mesh folders i get this prompt
- could be related to Meshroom not searching for paths correctly that creats the problem here Inside Houdini
![image](https://user-images.githubusercontent.com/26219491/132885509-5e2ea3db-8978-4e68-81aa-7b07f6afa45a.png)

-if i navigate to those folders with file explorer everything is there


Problem is we can't get it to work inside Houdini, keep getting this errors. Houdini dev's checked and advised to write here
![image](https://user-images.githubusercontent.com/26219491/132885780-aaa7c86c-2a2b-4093-b9f7-d4a56d908f05.png)

**Comment by diorn** [comment]
Sadly, same issue is still standing after a new Houdini release, i'm quite sure by the errors that this is on alicevision side

**Comment by MattiBRNDMR** [comment]
Hello @diorn @frading If its still an issue: I gave meshroom in houdini a go today on my linux mint machine (mint 20.1, houdini 19.5.332 Py3.9) and encountered the same issues as you had. After adding aliceVision/bin and aliceVisio/lib to my PATH and LD_LIBRARY_PATH, it worked. Got a similar error though "05_structure_from_motion failed!" but the mesh had nice uvs and looked fine overall.

`export PATH=$PATH:/home/matti/work/pipeline/meshroom_2021/aliceVision/bin`
`export LD_LIBRARY_PATH=/home/matti/work/pipeline/meshroom_2021/aliceVision/lib:$LD_LIBRARY_PATH`

...before sourcing houdini in the same terminal (or set them in your bashrc/bashprofile). 

![image](https://user-images.githubusercontent.com/33371968/185790052-26717f30-0800-4575-bed2-719eab0d043c.png)

**Comment by frading** [comment]
very good to know @MattiBRNDMR, thanks a lot for taking the time to write this.

I haven't tried since my issue above, as I could make progress with the standalone. But it's very encouraging that you got it working, I'll keep it in mind next time I need it.

**Comment by diorn** [comment]
Thank you @MattiBRNDMR for posting a solution! Will give it a try on the next Photogr project.
