### ISSUE TITLE
MacOS Xcode build / installation instructions / AliceVision latest version

### ISSUE THREAD

**Issue by JasonCoombs** [alicevision/AliceVision#1071]
A command-line build guide for MacOS was provided (2020) by @freshnewegg here:
https://github.com/alicevision/AliceVision/issues/931

Solutions for problems building on MacOS (2018) were shared by @TomHeaven here:
https://github.com/alicevision/AliceVision/issues/525

An open issue requests removing AliceVision's CUDA dependency entirely in the future:
https://github.com/alicevision/AliceVision/issues/439

Knowledge shared here by @patniemeyer about CUDA depth map computation for dense mesh:
https://github.com/alicevision/AliceVision/issues/444

For building with Xcode the steps are somewhat different from what we see today in INSTALL.md
https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

This Issue is meant to invite discussion before amendments are published to that file, to encourage more reporting of recent build failures with AliceVision on MacOS Big Sur (11.4) with Xcode 12.5+

INSTALL.md currently contains the following for MacOS (out-of-date, these instructions presume a CUDA build with old Mac hardware that included an NVIDIA GPU) --

```
git clone --recursive https://github.com/alicevision/AliceVision.git
mkdir build && cd build
```

followed by cmake:

```
cmake -DCMAKE_BUILD_TYPE=Release -G "Xcode" ../AliceVision
```

or, alternatively, to include unit tests and examples:

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DALICEVISION_BUILD_TESTS=ON -DALICEVISION_BUILD_EXAMPLES=ON \
-G "Xcode" ../AliceVision
```

My steps to build successfully were the following (build notes and discussions in various places clarify that a build on MacOS today cannot include CUDA because Mac hardware now provides us with an AMD GPU) --

```
$ brew install eigen
$ brew link eigen
$ xcode-select --install
$ brew install ceres-solver
$ brew install geogram
$ brew install openimageio
$ brew uninstall open-mesh
$ brew install openexr@2
$ brew unlink openexr
$ brew unlink imath
$ brew link ilmbase --force
$ brew link --overwrite openexr@2
$ brew link --overwrite imath
$ brew install opencv
$ vim ../AliceVision/CMakeLists.txt  [ To add the following lines below project(aliceVision) ]
include_directories("/usr/local/include")
link_directories("/usr/local/lib")
link_libraries("omp")
$ vim ../AliceVision/src/CMakeLists.txt  [ To change Clang to AppleClang as required by CMake 3.0+ ]
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "AppleClang")
// See: https://cmake.org/cmake/help/latest/policy/CMP0025.html
$ git clone https://github.com/laurentkneip/opengv
$ cd opengv && mkdir build && cd build && cmake ../
$ make install
$ git clone https://github.com/alembic/alembic
$ cd alembic && mkdir build && cd build
$ cmake ../
$ make install

Then invoke cmake in your AliceVision build directory with:
$ cmake -DCMAKE_BUILD_TYPE=Release -DALICEVISION_USE_CUDA=OFF -DALICEVISION_USE_ALEMBIC=ON \
-DALICEVISION_BUILD_TESTS=ON -DALICEVISION_BUILD_EXAMPLES=ON -DALICEVISION_USE_OPENCV=ON \
-DALICEVISION_USE_OPENGV=ON -DALICEVISION_USE_OPENMP=ON -G "Xcode" ../AliceVision
```

The cmake result of the above steps --

```
** AliceVision version: 2.4.0
** Target architecture: kaby-lake
** Build Shared libs: ON
** Build SfM part: ON
** Build MVS part: ON
** Build AliceVision tests: ON
** Build AliceVision documentation: 0
** Build AliceVision samples programs: ON
** Build AliceVision+OpenCV samples programs: 1
** Build UncertaintyTE: 0
** Build MeshSDFilter: 1
** Build Alembic exporter: 1
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: 1
** Use CUDA: 0
** Use OpenCV SIFT features: 0
** Use PopSift feature extractor: 0
** Use CCTAG markers: 0
** Use OpenGV for rig localization: 1
```

Open the Xcode project file and click Automatically Create Schemes when prompted.

Select the ALL_BUILD target in Xcode and then compile and link by choosing from the menu Product->Build.

This is my first time building AliceVision. My intent is to use Meshroom without dense mesh Multi View Stereo (MVS) enabled.
https://alicevision.org/#photogrammetry/depth_maps_estimation

(CUDA is required for the MVS part of the AliceVision Photogrammetry Pipeline, but draft meshing with the CPU still works.)
https://meshroom-manual.readthedocs.io/en/bibtex1/install/requirements/requirements.html

Without CUDA on MacOS the AliceVision Photogrammetry Pipeline still gives us Structure-from-Motion (SfM)
https://alicevision.org/#photogrammetry/sfm

Presumably the executables and binary shared library files must be installed manually from the Xcode build directory for Meshroom to find them. There is an "install" target in the Xcode project -- it might automate installation correctly for you. Building the "install" target did copy the resulting binaries to /usr/local/bin and libraries to /usr/local/lib and created /usr/local/include/aliceVision for me as expected.

**Comment by JasonCoombs** [comment]
Meshroom requires a few minor fixes for MacOS:

https://github.com/alicevision/meshroom/pull/1307#issuecomment-875907260

**Comment by JasonCoombs** [comment]
Testing Meshroom on MacOS:

`$ git clone https://github.com/alicevision/dataset_monstree`

<img width="1674" alt="Screen Shot 2021-07-07 at 10 35 39 AM" src="https://user-images.githubusercontent.com/16699430/124825418-4af4e900-df0f-11eb-847c-8ac447c02ca5.png">

**Comment by JayFoxRox** [comment]
@simogasp looks like the bot ignored the "do not close".  Also potentially affects many other issues: https://github.com/alicevision/AliceVision/issues?q=label%3A%22do+not+close%22+is%3Aclosed

Not sure about the current state on macOS though and wether the instructions need updating / are still necessary.
