### ISSUE TITLE
error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"

### ISSUE THREAD

**Issue by PPPHUB** [alicevision/AliceVision#1077]
my system is ubuntu20.0.4. When I run `sudo make` it come out an error that  
`/AliceVision/src/nonFree/sift/vl/imopv_sse2.c:15:2: error: #error "Compiling with SSE2 enabled, but no __SSE2__ defined"
` 
and `
error: ‘VSIZE’ undeclared (first use in this function)` 
what should I do?
And, if I just want to run the source code of the meshroom, do I need to compiler this project or I just need to add the release version to path?

**Comment by chunibyo-wly** [comment]
same problem

**Comment by PPPHUB** [comment]
> same problem

try to add `add_definitions( -DVL_DISABLE_SSE2 )` in  alicevision/cmakelists.txt

**Comment by chunibyo-wly** [comment]
Thanks for your reply, that is a good solution. I use virtual machine to compile this project, and it looks like vm prevent me to use sse2 instruction set.
