### ISSUE TITLE
Incremental: Fix bundle adjustment to avoid drift

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#11]
- The result of the reconstruction is always in a random position and orientation. We would like to keep it centered in 0.
- Fix the UP: currently the reconstruction are always flipped vertically
- Sometimes the reconstruction is discretised in a grid. It seems to come from floating point precision at the reconstruction scale. So one solution could be to add a constraint in the bundle to work in [0,1] value range. (see also  openMVG/openMVG#471)

**Comment by simogasp** [comment]
https://ieeexplore.ieee.org/document/9687232
