### ISSUE TITLE
Database entry request for Samsung Galaxy A71 - SM-A715F camera chip data - cameraSensors.db

### ISSUE THREAD

**Issue by h0yer** [alicevision/AliceVision#1140]
Additional line for cameraSensors.db:

`Samsung;SM-A715F;7.4;camerafv5`

Autodetects radial3 camera type and seems to work well.
Data from camerafv5.com

**Comment by Whitestripe7773** [comment]
I'll add it

**Comment by Whitestripe7773** [comment]
This issue can be closed (resolved).
