### ISSUE TITLE
AliceVision needs to be updated for modern OpenEXR

### ISSUE THREAD

**Issue by papadop** [alicevision/AliceVision#1167]
It seems that the AliceVision has been made to work with OpenEXR 2.x. But now OpenEXR 3.x seems to be here for almost a year. It would be nice to be able to work with it....

**Comment by fabiencastan** [comment]
It's here for Linux: https://github.com/alicevision/AliceVision/pull/1127
For windows, things seems to be stuck on vcpkg: https://github.com/microsoft/vcpkg/pull/20957

**Comment by simogasp** [comment]
vcpkg is now updated https://github.com/microsoft/vcpkg/pull/26862
