### ISSUE TITLE
Failed to estimate space from SfM: The space bounding box is too small.

### ISSUE THREAD

**Issue by l-janzen** [alicevision/AliceVision#1168]
Hey guys, 
I have a problem with the Meshing. I created a 3D object in blender and took several photos from different positions. When I load them into meshroom, the round icon in the photos is red(Camera intrinsics: Unknown), but I can start the pipeline and it goes until Meshing and then I get the following error in the meshing step: "Failed to estimate space from SfM: The space bounding box is too small". I tried unchecking "Estimate space from SfM", it doesn't work.  I had the idea to add the camera parameters to the database, I'm not sure which camera I should add. I manually entered the camera parameters in CameraInit, that I took from the camera settings in blender, but that doesn't remove the error either. At the same time the point cloud is created.
Please, help me!

Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * colorizeOutput = 0
 * contributeMarginFactor = 2
 * densifyNbBack = 0 (default)
 * densifyNbFront = 0 (default)
 * densifyScale = 1 (default)
 * depthMapsFolder = ""
 * estimateSpaceFromSfM = 0
 * estimateSpaceMinObservationAngle = 10 (default)
 * estimateSpaceMinObservations = 3 (default)
 * exportDebugTetrahedralization = 0
 * fullWeight = 1
 * helperPointsGridSize = 10
 * input = "D:/TU/BA/Meshroom-2021.1.0-win64/MeshroomCache/StructureFromMotion/bd093cd440cbbf04baf6b3283e916179fe4cb90e/sfm.abc"
 * invertTetrahedronBasedOnNeighborsNbIterations = 10
 * maskBorderSize = 1 (default)
 * maskHelperPointsWeight = 0 (default)
 * maxInputPoints = 50000000
 * maxNbConnectedHelperPoints = 50
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minSolidAngleRatio = 0.2
 * minStep = 2
 * minVis = 2 (default)
 * nPixelSizeBehind = 4
 * nbSolidAngleFilteringIterations = 2
 * output = "D:/TU/BA/Meshroom-2021.1.0-win64/MeshroomCache/Meshing/f3a03918ec8cdc37389d3d0d2f37bf7d6bf6a5d0/densePointCloud.abc"
 * outputMesh = "D:/TU/BA/Meshroom-2021.1.0-win64/MeshroomCache/Meshing/f3a03918ec8cdc37389d3d0d2f37bf7d6bf6a5d0/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * saveRawDensePointCloud = 0
 * seed =  Unknown Type "unsigned int"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteFilteringForWeaklySupportedSurfaces = 1
 * voteMarginFactor = 4

[11:02:07.664610][info] Found 1 image dimension(s):
[11:02:07.665610][info]         - [1920x1080]
[11:02:07.666611][info] Overall maximum dimension: [1920x1080]
[11:02:07.666611][warning] repartitionMode: 1
[11:02:07.666611][warning] partitioningMode: 1
[11:02:07.666611][info] Meshing mode: multi-resolution, partitioning: single block.
[11:02:07.666611][info] Estimate space from SfM.
[11:02:07.666611][fatal] Failed to estimate space from SfM: The space bounding box is too small.

**Comment by travex** [comment]
Old post but here's my answer. In my experience it depends on the object you are trying to reconstruct and the camera view positions. You can try setting estimateSpaceMinObservationAngle to a lower value or 0, and see if that helps.
