### ISSUE TITLE
Error cmake OpenEXR Ubuntu 18.04 version 50.0

### ISSUE THREAD

**Issue by informatter** [alicevision/AliceVision#1188]
Hi,

I am attempting to build the `develop` branch because it has a feature that I currently need: `computeNewCoordinateSystemFromGpsData` in `alignment.cpp`

Unfortunately, I  am not getting past  `cmake -DCMAKE_BUILD_TYPE=Release . ../AliceVision` I always get the following error:

```
CMake Error at src/CMakeLists.txt:293 (find_package):
  By not providing "FindOpenEXR.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenEXR", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenEXR" with any
  of the following names:

    OpenEXRConfig.cmake
    openexr-config.cmake

  Add the installation prefix of "OpenEXR" to CMAKE_PREFIX_PATH or set
  "OpenEXR_DIR" to a directory containing one of the above files.  If
  "OpenEXR" provides a separate development package or SDK, be sure it has
  been installed.
```

I am attempting to compile Alice Vision on **Ubuntu 18.04 v50.0**

These are the steps I have followed :

1. `sudo apt-get install libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev`
2.  `sudo apt install libopenexr-dev ` after reading https://github.com/alicevision/AliceVision/issues/889
3.  `git clone --recursive -b develop --single-branch https://github.com/alicevision/AliceVision.git`
4. `mkdir build && cd build`
5. `cmake -DCMAKE_BUILD_TYPE=Release . ../AliceVision`

I have also ran  `sudo apt list --installed | grep openexr` to make sure `openexr` is installed, and it is:

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libopenexr-dev/bionic-updates,bionic-security,now 2.2.0-11.1ubuntu1.9 amd64 [installed]
libopenexr22/bionic-updates,bionic-security,now 2.2.0-11.1ubuntu1.9 amd64 [installed,automatic]
```
Any help will be much appreciated, I am also curious to know when is the next release planned for?

Thank you for your time.

**Comment by sanchayanghosh** [comment]
Hi. Would you be comfortable with using docker to do the build of alicevision dependencies?

you don't have openexr/ceres, etc installed which is causing this issue with you.

The docker scripts will help you build alicevision.
