### ISSUE TITLE
Alice Vision failed to build ( Windows )

### ISSUE THREAD

**Issue by nguyen1998pr** [alicevision/AliceVision#1192]
I'm having problem with imath library while building Alice Vision with VS 2017, is there any solution to this problem?
![image](https://user-images.githubusercontent.com/55442292/180360843-14a26a3f-4635-4052-b4b9-ab0e9bf3c549.png)

**Comment by sanchayanghosh** [comment]
Can you update Visual Studio to 2019 and check?
