### ISSUE TITLE
MSVC build in debug is broken

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#1261]
Reach limit of 65535 objects in the library.
Not clear when/how this problem has been introduced.

**Comment by fabiencastan** [comment]
@p12tic Do you have an idea?

**Comment by p12tic** [comment]
@fabiencastan May be fixed by https://github.com/alicevision/AliceVision/pull/1265.

**Comment by fabiencastan** [comment]
Maybe introduced during the externalization of clp, coinUtils and osi which does not provide dll files but only lib files in vcpkg:

-rw-r--r-- 1 castanf 197121  42M Oct  5 11:51 Clp.lib
-rw-r--r-- 1 castanf 197121  29M Oct  5 11:50 CoinUtils.lib
-rw-r--r-- 1 castanf 197121 7.7M Oct  5 11:50 Osi.lib
-rw-r--r-- 1 castanf 197121 2.8M Oct  5 11:42 metis.lib
-rw-r--r-- 1 castanf 197121 2.4M Oct  5 11:42 GKlib.lib
-rw-r--r-- 1 castanf 197121 623K Oct  5 16:07 OpenImageIO_d.lib
-rw-r--r-- 1 castanf 197121 434K Oct  5 11:27 boost_program_options-vc140-mt-gd.lib
-rw-r--r-- 1 castanf 197121 413K Oct  5 16:06 OpenImageIO_Util_d.lib
-rw-r--r-- 1 castanf 197121 310K Oct  5 11:37 lapack.lib
-rw-r--r-- 1 castanf 197121 301K Oct  5 11:14 openblas.lib
-rw-r--r-- 1 castanf 197121 286K Oct  5 11:26 boost_log-vc140-mt-gd.lib
-rw-r--r-- 1 castanf 197121 157K Oct  5 11:47 ceres-debug.lib

**Comment by fabiencastan** [comment]
`vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`
https://github.com/microsoft/vcpkg/blob/master/ports/clp/portfile.cmake#L1

**Comment by simogasp** [comment]
yes but on windows you are using the vcpkg ones, no? So they are built statically by vcpkg. Or did you build them from scratch without vcpkg?

**Comment by fabiencastan** [comment]
That's the problem, they are built statically, so then included in aliceVision_sfm.dll.

**Comment by fabiencastan** [comment]
https://github.com/microsoft/vcpkg/pull/27129

**Comment by fabiencastan** [comment]
https://github.com/microsoft/vcpkg/pull/27130
