### ISSUE TITLE
Vs open sln lack aliceVision_sfm.lib

### ISSUE THREAD

**Issue by kk518** [alicevision/AliceVision#1263]
I try to bulid AliceVision in my pc
git code and vcpkg all Dependence and cmake project successfully
but when i use VS open sln miss aliceVison_sfm.lib and aliceVision_localization.lib and aliceVision_rig.lib

**Comment by fabiencastan** [comment]
Are you building in Release?
We have an issue in debug: https://github.com/alicevision/AliceVision/issues/1261

**Comment by kk518** [comment]
yes i use vcpkg build all release  and use cmake the project successfully

**Comment by kk518** [comment]
> Are you building in Release? We have an issue in debug: #1261
yes i use vcpkg build all release and use cmake the project successfully

**Comment by fabiencastan** [comment]
Yes, but in Visual Studio, it's unfortunately always setup on Debug by default. Did you manually changed it to Release?

**Comment by kk518** [comment]
> Yes, but in Visual Studio, it's unfortunately always setup on Debug by default. Did you manually changed it to Release?

I tring to build the project in Release but hava other errors 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	aliceVision_sfm	D:\AliceVision\build\src\aliceVision\sfm\Clp.lib(ClpPackedMatrix.cpp.obj)	1	

and
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __std_find_trivial_4 referenced in function "int const * __cdecl std::_Find_unchecked<int const *,int>(int const *,int const * const,int const &)" (??$_Find_unchecked@PEBHH@std@@YAPEBHPEBHQEBHAEBH@Z)	aliceVision_sfm	D:\AliceVision\build\src\aliceVision\sfm\CoinUtils.lib(CoinPackedVectorBase.cpp.obj)	1	

how can i solve these problems  my friend  ?

**Comment by kk518** [comment]
> Yes, but in Visual Studio, it's unfortunately always setup on Debug by default. Did you manually changed it to Release?

I try to use VS 2022 donot hava the error but hava a new error that tell me must use vs2015 - vs 2019 buliding the deep.lib
when i use vs2019 the front error arise
