### ISSUE TITLE
ImageMatching broken on develop branch

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#1279]
"imageMatches.txt" is exported in json (instead of one line per image) and not read as json, so the default pipeline is unusable.

@p12tic Any idea how this has been introduced?

**Comment by fabiencastan** [comment]
Probably here:
https://github.com/alicevision/AliceVision/pull/1270/files#diff-539dbd36c413011ccb9cd64d14d45e29b90268f1f585ce6f031f472581fa4eceL88
the override of the formatting has been removed and there is maybe a default one for std containers.

**Comment by p12tic** [comment]
@fabiencastan Looking
