### ISSUE TITLE
building error: 'cvMatBGRToImageRGBA': is not a member of 'aliceVision::image'

### ISSUE THREAD

**Issue by RufinoN** [alicevision/AliceVision#1338]
Hello,
when i build Alice vision using Visual studio 17 2022 i get the following errors:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/99747505/213724813-d0446dac-39f4-4db0-89d3-3264e9fef78e.png">

seems like I'm missing some code?

**Comment by cbentejac** [comment]
Hi @RufinoN,

Have you enabled OpenCV in your cmake command? You can do so by adding `-DALICEVISION_USE_OPENCV=ON` to the cmake command you used to generate the Visual Studio solution.

The functions you're showing need it to compile.

**Comment by RufinoN** [comment]
GREAT!, thanks that works!!

**Comment by simogasp** [comment]
Maybe we should include
```c++
#include <aliceVision/config.hpp>
```
at the top of https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/image/convertionOpenCV.hpp without relying on other includes to import the macro `ALICEVISION_IS_DEFINED`
