### ISSUE TITLE
Script to export all descriptors from a 3D reconstruction

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#135]
The goal is to collect descriptors from successful reconstructions in order to use them to build a voctree using only meaningful descriptors.

**Comment by pmoulon** [comment]
You can read the code from SfM_Localization_Single_3DTrackObservation_Database in order to see the way I have used to parse all the descriptor that relates the current reconstruction.

**Comment by fabiencastan** [comment]
Thx for the tip!
