### ISSUE TITLE
CoinUtils error

### ISSUE THREAD

**Issue by skinkie** [alicevision/AliceVision#1362]
Following the manual on compilation I am consistently ending up in this error. It will also fail for Clp and Osi.

What would be the way to force a Coin build from the AliceVision repo?

```
CMake Error at src/CMakeLists.txt:433 (find_package):
  By not providing "FindCoinUtils.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CoinUtils", but CMake did not find one.

  Could not find a package configuration file provided by "CoinUtils" with
  any of the following names:

    CoinUtilsConfig.cmake
    coinutils-config.cmake

  Add the installation prefix of "CoinUtils" to CMAKE_PREFIX_PATH or set
  "CoinUtils_DIR" to a directory containing one of the above files.  If
  "CoinUtils" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by simogasp** [comment]
We recently moved away from having Coin libraries embedded in the project source.
You should build the libraries from here
https://github.com/alicevision/Clp
https://github.com/alicevision/CoinUtils
https://github.com/alicevision/osi_clp
and install them somewhere (but not in a system directory) and either add their install location to `CMAKE_PREFIX_PATH` or individually provide the `CoinUtils_DIR`, `Clp_DIR` and `osi_clp_DIR` path at cmake time.

And yes, the doc is not up-to-date with that...

**Comment by skinkie** [comment]
I'll check if I can get this to work ;)

**Comment by skinkie** [comment]
@simogasp that does not do the trick yet. I am able to install the osi_clp repo, but Clp by itself does not.

```
cmake -DCMAKE_INSTALL_PREFIX=/opt/alicevision ..
CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "FindOsi.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Osi", but
  CMake did not find one.

  Could not find a package configuration file provided by "Osi" with any of
  the following names:

    OsiConfig.cmake
    osi-config.cmake

  Add the installation prefix of "Osi" to CMAKE_PREFIX_PATH or set "Osi_DIR"
  to a directory containing one of the above files.  If "Osi" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by simogasp** [comment]
And sorry again I gave you the wrong repo before, the osi_clp was the old embedded version, you should remove it completely and uninstall it

**Comment by skinkie** [comment]
Then we start over ;)

**Comment by skinkie** [comment]
So: CoinUtils, Osi, Clp with cmake -DCMAKE_INSTALL_PREFIX=/opt/alicevision does the trick

But then compiling AliceVision...

/usr/bin/ld: /opt/alicevision/lib/libOsi.a(OsiPresolve.cpp.o): warning: relocation against `_ZTI17make_fixed_action' in read-only section `.text'
/usr/bin/ld: /opt/alicevision/lib/libClp.a(ClpModel.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTI15ClpPackedMatrix' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value

**Comment by simogasp** [comment]
yes or just build shared libs with `-DBUILD_SHARED_LIBS:BOOL=ON` 

@p12tic do you remember if there was a reason for not settin `BUILD_SHARED_LIBS` to `ON` by default in the `CMakeLists.txt` of all the 3 libs?
