### ISSUE TITLE
debian 11: CMake can't find expat

### ISSUE THREAD

**Issue by triveria** [alicevision/AliceVision#1386]
Hi,
I'm trying to compile AliceVision on a fresh Debian 11 system but cmake can't find expat:

```
~/programming/AliceVision/build $ cmake -DCMAKE_BUILD_TYPE=Release -DALICEVISION_BUILD_TESTS=ON -DALICEVISION_BUILD_EXAMPLES=ON ..
 ...

CMake Error at src/CMakeLists.txt:341 (find_package): 
  Could not find a package configuration file provided by "expat" with any of 
  the following names: 
 
    expatConfig.cmake 
    expat-config.cmake 
 
  Add the installation prefix of "expat" to CMAKE_PREFIX_PATH or set 
  "expat_DIR" to a directory containing one of the above files.  If "expat" 
  provides a separate development package or SDK, be sure it has been 
  installed. 
 
 
-- Configuring incomplete, errors occurred! 
See also "/home/admin/programming/AliceVision/build/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log](https://github.com/alicevision/AliceVision/files/11015755/CMakeOutput.log)

I installed the following packages:
`sudo apt install libexpat1-dev expat`

and I can see the header and the .so-file:
```
$ ls /usr/include/expat* 
/usr/include/expat.h  /usr/include/expat_external.h
```

```
$ ls /usr/lib/x86_64-linux-gnu/libexpat* 
/usr/lib/x86_64-linux-gnu/libexpat.a   /usr/lib/x86_64-linux-gnu/libexpat.so.1       /usr/lib/x86_64-linux-gnu/libexpatw.a   /usr/lib/x86_64-linux-gnu/libexpatw.so.1 
/usr/lib/x86_64-linux-gnu/libexpat.so  /usr/lib/x86_64-linux-gnu/libexpat.so.1.6.12  /usr/lib/x86_64-linux-gnu/libexpatw.so  /usr/lib/x86_64-linux-gnu/libexpatw.so.1.6.12
```

I'm on the “develop” branch.

Do I still need some packages? Or must I tell cmake somehow where it should look for expat?

Further information:

```
$ cat /etc/os-release  
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" 
NAME="Debian GNU/Linux" 
VERSION_ID="11" 
VERSION="11 (bullseye)" 
VERSION_CODENAME=bullseye 
ID=debian 
HOME_URL="https://www.debian.org/" 
SUPPORT_URL="https://www.debian.org/support" 
BUG_REPORT_URL="https://bugs.debian.org/"

```

The machine is a freshly instantiated AWS machine, so no much configuration was done yet.

**Comment by simogasp** [comment]
can you check if you have this file `/usr/lib/x86_64-linux-gnu/cmake/expat-2.5.0/expat-config.cmake`
as listed here
https://packages.debian.org/sid/amd64/libexpat1-dev/filelist
If so, you can add `-Dexpat_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/expat-2.5.0` to the cmake command line
(note that depending on the version that is actually installed the path could different according to the version)

**Comment by triveria** [comment]
Those files (specifically expat-config.cmake) don't exist on my system, as those files only exist in debian sid apparently.
These are the files that come with my libexpat1-dev on debian bullseye:
https://packages.debian.org/bullseye/amd64/libexpat1-dev/filelist

**Comment by simogasp** [comment]
Since there is at least the .pc file you could try to write a few cmake line to generate the cmake target from it instead of searching
https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

Probably  you are better off removing the package, building and installing it on a separate directory, and launching AliceVision cmake with that line I put above pointing to the install directory you choose (avoid system directory though)
