### ISSUE TITLE
cmake can't find CoinUtils, Clp or Osi

### ISSUE THREAD

**Issue by triveria** [alicevision/AliceVision#1396]
Hi,

I'm  trying to compile the rc3.0 branch (commit 9a16c3), but cmake can't find CoinUtils, Clp or Osi:

```
~/AliceVision/build on rc3.0 $ cmake \ 
-DCMAKE_BUILD_TYPE=Release \ 
-D{COINUTILS,CLP,OSI}_INCLUDE_DIR_HINTS=/usr/include/coin \
-DCMAKE_INSTALL_PREFIX=/usr \ 
-DCMAKE_INSTALL_LIBDIR=lib \ 
-DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann \ 
-DLEMON_INCLUDE_DIR_HINTS=/usr/include/lemon \ 
-DALICEVISION_USE_CUDA=OFF \ 
-DALICEVISION_USE_OPENGV=ON \ 
-DALICEVISION_USE_OPENCV=ON \ 
-DALICEVISION_BUILD_DOC=ON \ 
-G Ninja \ 
..
...
CMake Error at src/CMakeLists.txt:443 (find_package): 
  By not providing "FindCoinUtils.cmake" in CMAKE_MODULE_PATH this project 
  has asked CMake to find a package configuration file provided by 
  "CoinUtils", but CMake did not find one. 
 
  Could not find a package configuration file provided by "CoinUtils" with 
  any of the following names: 
 
    CoinUtilsConfig.cmake 
    coinutils-config.cmake 
 
  Add the installation prefix of "CoinUtils" to CMAKE_PREFIX_PATH or set 
  "CoinUtils_DIR" to a directory containing one of the above files.  If 
  "CoinUtils" provides a separate development package or SDK, be sure it has 
  been installed.
```
Similar error messages show up for Clp or Osi.

However, CoinUtils, Clp and Osi are installed:
```
$ ls /usr/include/coin  
CbcOrClpParam.cpp            ClpDynamicMatrix.hpp     ClpPEDualRowDantzig.hpp        ClpSimplex.hpp              CoinFileIO.hpp            CoinPackedVectorBase.hpp     CoinPresolveSingleton.hpp    CoinStructuredModel.hpp      OsiChooseVariable.hpp 
CbcOrClpParam.hpp            ClpEventHandler.hpp      ClpPEDualRowSteepest.hpp       ClpSimplexDual.hpp          CoinFinite.hpp            CoinParam.hpp                CoinPresolveSubst.hpp        CoinTime.hpp                 OsiClpSolverInterface.hpp 
ClpCholeskyBase.hpp          ClpFactorization.hpp     ClpPEPrimalColumnDantzig.hpp   ClpSimplexNonlinear.hpp     CoinFloatEqual.hpp        CoinPragma.hpp               CoinPresolveTighten.hpp      CoinTypes.hpp                OsiColCut.hpp 
ClpCholeskyDense.hpp         ClpGubDynamicMatrix.hpp  ClpPEPrimalColumnSteepest.hpp  ClpSimplexOther.hpp         CoinHelperFunctions.hpp   CoinPresolveDoubleton.hpp    CoinPresolveTripleton.hpp    CoinUtility.hpp              OsiCollections.hpp 
ClpCholeskyPardiso.hpp       ClpGubMatrix.hpp         ClpPESimplex.hpp               ClpSimplexPrimal.hpp        CoinIndexedVector.hpp     CoinPresolveDual.hpp         CoinPresolveUseless.hpp      CoinUtilsConfig.h            OsiConfig.h 
ClpConfig.h                  ClpInterior.hpp          ClpPackedMatrix.hpp            ClpSolve.hpp                CoinLpIO.hpp              CoinPresolveDupcol.hpp       CoinPresolveZeros.hpp        CoinWarmStart.hpp            OsiCut.hpp 
ClpConstraint.hpp            ClpLinearObjective.hpp   ClpParameters.hpp              Clp_C_Interface.h           CoinMessage.hpp           CoinPresolveEmpty.hpp        CoinRational.hpp             CoinWarmStartBasis.hpp       OsiCuts.hpp 
ClpConstraintLinear.hpp      ClpMatrixBase.hpp        ClpPdcoBase.hpp                CoinAlloc.hpp               CoinMessageHandler.hpp    CoinPresolveFixed.hpp        CoinSearchTree.hpp           CoinWarmStartDual.hpp        OsiPresolve.hpp 
ClpConstraintQuadratic.hpp   ClpMessage.hpp           ClpPlusMinusOneMatrix.hpp      CoinBuild.hpp               CoinModel.hpp             CoinPresolveForcing.hpp      CoinShallowPackedVector.hpp  CoinWarmStartPrimalDual.hpp  OsiRowCut.hpp 
ClpDualRowDantzig.hpp        ClpModel.hpp             ClpPresolve.hpp                CoinDenseFactorization.hpp  CoinModelUseful.hpp       CoinPresolveImpliedFree.hpp  CoinSignal.hpp               CoinWarmStartVector.hpp      OsiRowCutDebugger.hpp 
ClpDualRowPivot.hpp          ClpNetworkMatrix.hpp     ClpPrimalColumnDantzig.hpp     CoinDenseVector.hpp         CoinMpsIO.hpp             CoinPresolveIsolated.hpp     CoinSimpFactorization.hpp    Coin_C_defines.h             OsiSolverBranch.hpp 
ClpDualRowSteepest.hpp       ClpNode.hpp              ClpPrimalColumnPivot.hpp       CoinDistance.hpp            CoinOslFactorization.hpp  CoinPresolveMatrix.hpp       CoinSmartPtr.hpp             Idiot.hpp                    OsiSolverInterface.hpp 
ClpDummyMatrix.hpp           ClpNonLinearCost.hpp     ClpPrimalColumnSteepest.hpp    CoinError.hpp               CoinPackedMatrix.hpp      CoinPresolveMonitor.hpp      CoinSnapshot.hpp             OsiAuxInfo.hpp               OsiSolverParameters.hpp 
ClpDynamicExampleMatrix.hpp  ClpObjective.hpp         ClpQuadraticObjective.hpp      CoinFactorization.hpp       CoinPackedVector.hpp      CoinPresolvePsdebug.hpp      CoinSort.hpp                 OsiBranchingObject.hpp       OsiUnitTests.hpp 
```
 
The only way I got cmake to successfully finish, can be seen in my fork: https://github.com/triveria/AliceVision/tree/make-compilable-on-debian.
Here, the files src/cmake/FindClp.cmake, src/cmake/FindCoinUtils.cmake, src/cmake/FindOsi.cmake are readded from commit c78196db406b78d0ca4254e4839b7e377322a389.

I get exactly the same behaviour on Debian 12 (bookworm) and on Manjaro.

So I wonder, how do you people compile AliceVision? Do I need to add some more cmake flags so that CoinUtils and OR-tools can be found?

**Comment by simogasp** [comment]
You are better off removing the libraries from the system directory and build them with our forks
https://github.com/alicevision/Clp
https://github.com/alicevision/CoinUtils
https://github.com/alicevision/Osi
those will install the proper `*Config.cmake ` files that are needed in cmake

**Comment by triveria** [comment]
Yes indeed, I installed them via apt.

So 2 questions:

1. In the INSTALL.md the libraries are listed as optional. Furthermore, it says that one should only compile the forks if one needs to (interpreted as: "Only compile if package manager does not provide CoinUtils and such").
But apparently, AliceVision strictly depends on these forks.
So wouldn't it be more straightforward to rephrase that part in the INSTALL.md and have them included as submodules, just as they were before commit [Always use external CoinUtils, Osi and Clp](https://github.com/alicevision/AliceVision/commit/66c3f983705f06cad49a489d85d2bb8f0c268027) removed them?

2. I've now already adjusted my AliceVision to use the coin-or-tools from the standard debian repository. Do they just work fine or should I switch to your coin forks?

**Comment by simogasp** [comment]
> Yes indeed, I installed them via apt.
> 
> So 2 questions:
> 
> 1. In the INSTALL.md the libraries are listed as optional. Furthermore, it says that one should only compile the forks if one needs to (interpreted as: "Only compile if package manager does not provide CoinUtils and such").
>    But apparently, AliceVision strictly depends on these forks.
>    So wouldn't it be more straightforward to rephrase that part in the INSTALL.md and have them included as submodules, just as they were before commit [Always use external CoinUtils, Osi and Clp](https://github.com/alicevision/AliceVision/commit/66c3f983705f06cad49a489d85d2bb8f0c268027) removed them?

Yes, you are right, those 3 lines are misplaced, they should go into the required libraries.
And we will specify that they have to be built from our forks. I don't know about submodules, it's always tricky to have submodules and nested cmake projects.

> 2. I've now already adjusted my AliceVision to use the coin-or-tools from the standard debian repository. Do they just work fine or should I switch to your coin forks?

If you managed to make it work with the find*.cmake it's all fine, the only thing that is different between our forks and the original is just the cmake building system (which, incidentally, is inspired by the one used by vckpg). So there should be no difference using one system rather than the other.
