### ISSUE TITLE
cmake can't find sphinx/rst/conf.py 

### ISSUE THREAD

**Issue by YuMeiWangddup** [alicevision/AliceVision#1405]
Hi,
I'm trying to compile alicevision2023.3.0.0 on windows10 system but cmake can't find AliceVision/docs/sphinx/rst/conf.py,the log is as follow:

PS E:\Code\04_cc\AliceVision-3.0.0-git\AliceVision\build> cmake .. -DCMAKE_TOOLCHAIN_FILE=D:\ProfesSoftware\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.16.27048.0
-- The CXX compiler identification is MSVC 19.16.27048.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Force CMAKE_INSTALL_DO_STRIP in Release
-- ----------------------------------------
-- ALICEVISION_BUILD_DEPENDENCIES: OFF
-- ALICEVISION_BUILD_TESTS: OFF
--
-- AV_BUILD_CUDA: OFF
-- AV_BUILD_ZLIB: OFF
-- AV_BUILD_ASSIMP: ON
-- AV_BUILD_TIFF: ON
-- AV_BUILD_JPEG: ON
-- AV_BUILD_PNG: ON
-- AV_BUILD_LIBRAW: ON
-- AV_BUILD_CCTAG: ON
-- AV_BUILD_APRILTAG: ON
-- AV_BUILD_POPSIFT: ON
-- AV_BUILD_OPENGV: ON
-- AV_BUILD_OPENCV: ON
-- AV_BUILD_LAPACK: ON
-- AV_BUILD_SUITESPARSE: ON
-- AV_BUILD_FFMPEG: ON
-- AV_BUILD_VPX: ON
-- AV_USE_CUDA: ON
-- AV_USE_OPENMP: OFF
-- AV_BUILD_COINUTILS: ON
-- AV_BUILD_OSI: ON
-- AV_BUILD_CLP: ON
-- AV_BUILD_PCL: ON
-- AV_BUILD_DEPENDENCIES_PARALLEL: 1
--
-- CMAKE_BUILD_TYPE: Release
-- DEPS_CMAKE_BUILD_TYPE: Release
-- CMAKE_INSTALL_LIBDIR: lib
-- CMAKE_INSTALL_PREFIX: C:/Program Files/aliceVision
-- CMAKE_INSTALL_RPATH:
-- CMAKE_INSTALL_DO_STRIP: TRUE
-- ----------------------------------------
CMake version: 3.23
-- ** ALICEVISION_BUILD_DOC: 'AUTO'
-- ** ALICEVISION_USE_OPENMP: 'ON'
-- ** ALICEVISION_USE_CCTAG: 'AUTO'
-- ** ALICEVISION_USE_APRILTAG: 'AUTO'
-- ** ALICEVISION_USE_POPSIFT: 'AUTO'
-- ** ALICEVISION_USE_OPENGV: 'AUTO'
-- ** ALICEVISION_USE_ALEMBIC: 'AUTO'
-- ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
-- ** ALICEVISION_USE_CUDA: 'ON'
-- ** ALICEVISION_USE_OPENCV: 'OFF'
-- ** ALICEVISION_USE_OPENCV_CONTRIB: 'AUTO'
-- Force CMAKE_INSTALL_DO_STRIP in Release
-- target changed from "" to "auto"
-- Detected Host CPU: skylake
-- Performing Test check_c_compiler_flag__arch_AVX2
-- Performing Test check_c_compiler_flag__arch_AVX2 - Success
-- Performing Test check_cxx_compiler_flag__arch_AVX2
-- Performing Test check_cxx_compiler_flag__arch_AVX2 - Success
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- OpenMP found.
-- Boost 1_78 found.
-- Found Threads: TRUE
-- Found ZLIB: optimized;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- OpenEXR found. (Version 2.5.0)
-- Found ZLIB: optimized;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found suitable version "1.2.11", minimum required is "1.2.11")
-- OpenImageIO found.
-- Expat found.
-- Did not find MOSEK header
-- Did not find MOSEK library
-- Could not find mosek library on this machine.
-- Trying to find package Ceres for aliceVision:
-- By default, Ceres required SuiteSparse to ensure best performances. if you explicitly need to build without it, you can use the option: -DALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE=OFF
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- Ceres include dirs
-- Ceres libraries Ceres::ceres
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- Found AMD headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found AMD library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libamd.lib
-- Found CAMD headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found CAMD library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcamd.lib
-- Found COLAMD headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found COLAMD library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcolamd.lib
-- Found CCOLAMD headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found CCOLAMD library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libccolamd.lib
-- Found CHOLMOD headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found CHOLMOD library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcholmod.lib
-- Found SUITESPARSEQR headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found SUITESPARSEQR library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libspqr.lib
-- Found TBB library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbb.lib
-- Found Intel Thread Building Blocks (TBB) library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbb.lib, assuming SuiteSparseQR was compiled with TBB.
-- Found TBB_MALLOC library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbbmalloc.lib
-- Found Intel Thread Building Blocks (TBB) Malloc library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbbmalloc.lib
-- Found SUITESPARSE_CONFIG headers in: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/suitesparse
-- Found SUITESPARSE_CONFIG library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/suitesparseconfig.lib
-- Found METIS library: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/metis.lib
-- Found SuiteSparse: TRUE (found version "5.8.0")
-- SUITESPARSE_LIBRARIES: SuiteSparse::suitesparseconfig;SuiteSparse::amd;SuiteSparse::btf;SuiteSparse::camd;SuiteSparse::ccolamd;SuiteSparse::colamd;SuiteSparse::cholmod;SuiteSparse::cxsparse;SuiteSparse::klu;SuiteSparse::ldl;SuiteSparse::umfpack;SuiteSparse::spqr;metis;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libspqr.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbb.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbbmalloc.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcholmod.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libccolamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcolamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/lapack.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/openblas.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/openblas.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/suitesparseconfig.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/metis.lib
-- CERES_LIBRARIES: Ceres::ceres;SuiteSparse::suitesparseconfig;SuiteSparse::amd;SuiteSparse::btf;SuiteSparse::camd;SuiteSparse::ccolamd;SuiteSparse::colamd;SuiteSparse::cholmod;SuiteSparse::cxsparse;SuiteSparse::klu;SuiteSparse::ldl;SuiteSparse::umfpack;SuiteSparse::spqr;metis;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libspqr.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbb.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/tbbmalloc.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcholmod.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libccolamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libcolamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/libamd.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/lapack.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/openblas.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/openblas.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/suitesparseconfig.lib;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/metis.lib
-- CERES_INCLUDE_DIRS:
-- Flann 1.9.1 found (include: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/flann)
-- Lemon  found (include: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include/lemon)
-- Found ZLIB: optimized;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Assimp: , ,
-- Alembic version 1.7.14 found.
-- Could NOT find opengv (missing: opengv_DIR)
-- Looking for UncertaintyTE.
-- UncertaintyTE headers not found!
-- UncertaintyTE library include not found
-- UncertaintyTE library not found
-- Could NOT find UncertaintyTE (missing: UNCERTAINTYTE_LIBRARY UNCERTAINTYTE_INCLUDE_DIR)
-- Found Geogram: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/geogram.lib
-- Geogram: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/debug/lib/geogram.lib, D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/include
MSVC compiler found.
OpenMP found. OpenMP activated in release.
-- BUILD_SHARED_LIBS ON
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4 (found suitable version "11.4", minimum required is "7.0")
-- CUDA found.
Build Mode: Release
-- CUDA Version is 11.4
-- Could NOT find apriltag (missing: apriltag_DIR)
-- PopSIFT found.
generatedDir: E:/Code/04_cc/AliceVision-3.0.0-git/AliceVision/build/src/generated
-- Found Sphinx: E:/software/python378/Scripts/sphinx-build.exe
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Sphinx found.
CMake Error: File E:/Code/04_cc/AliceVision-3.0.0-git/AliceVision/docs/sphinx/rst/conf.py does not exist.
CMake Error at src/CMakeLists.txt:870 (configure_file):
  configure_file Problem configuring file

** AliceVision version: 3.0.0
** Target architecture: skylake
** Build Shared libs: ON
** Build SfM part: ON
** Build MVS part: ON
** Build AliceVision tests: OFF
** Build AliceVision documentation: 1
** Build AliceVision samples programs: OFF
** Build AliceVision+OpenCV samples programs: 0
** Build UncertaintyTE: 0
** Build MeshSDFilter: 1
** Build Alembic exporter: 1
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: 1
** Use CUDA: 1
** Use OpenCV SIFT features: 0
** Use PopSift feature extractor: 1
** Use CCTAG markers: 0
** Use AprilTag markers: 0
** Use OpenGV for rig localization: 0

-- EIGEN:
-- CERES: 2.0.0
-- FLANN: 1.9.1 (internal)
-- CLP: 1.16.11
-- COINUTILS: 2.10.14
-- OSI: 0.107.9
-- LEMON:  (internal)

CMake Deprecation Warning at src/dependencies/lemon/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found PythonInterp: D:/ProfesSoftware/dev/vcpkg/installed/x64-windows/tools/python3/python.exe (found version "3.10.2")
-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
CMake Deprecation Warning at src/dependencies/vectorGraphics/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "E:/Code/04_cc/AliceVision-3.0.0-git/AliceVision/build/CMakeFiles/CMakeOutput.log".
See also "E:/Code/04_cc/AliceVision-3.0.0-git/AliceVision/build/CMakeFiles/CMakeError.log".

actually,I really didn't find the conf.py file under the path E:/Code/04_cc/AliceVision-3.0.0-git/AliceVision/docs/sphinx/rst.so where should i to get the file?

**Comment by zeuner** [comment]
I encountered similar errors, which were fixed here: https://github.com/alicevision/AliceVision/pull/1500
