### ISSUE TITLE
CMake Error at src/CMakeLists.txt:431 (find_package):

### ISSUE THREAD

**Issue by LostFool** [alicevision/AliceVision#1437]
Necessary FindCoinUtils.cmake file missing from /AliceVision/src/cmake

CMake Error at src/CMakeLists.txt:431 (find_package):
  By not providing "FindCoinUtils.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CoinUtils", but CMake did not find one.

  Could not find a package configuration file provided by "CoinUtils" with
  any of the following names:

    CoinUtilsConfig.cmake
    coinutils-config.cmake

  Add the installation prefix of "CoinUtils" to CMAKE_PREFIX_PATH or set
  "CoinUtils_DIR" to a directory containing one of the above files.  If
  "CoinUtils" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by simogasp** [comment]
https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#dependencies

- CoinUtils >= 2.9.3 use [our fork](https://github.com/alicevision/CoinUtils) with a CMake build system so that it can be easily found
- Coin-or linear programming (Clp) use [our fork](https://github.com/alicevision/Clp) with a CMake build system
- Open Solver Interface (Osi) >= 0.106.10 use [our fork](https://github.com/alicevision/Osi)) with a CMake build system

**Comment by LostFool** [comment]
I apologize, I should have followed the dependencies more closely. I am new to this and practicing with GPT guided tasks at the same time. Thank you for the quick resposne.
Unfortunately I ran into another issue, but i've done so much random stuff trying to do this I don't think it's easily solved. 
If you (or anyone) happens to have time to respond and guide, I'd appreciate it, but again I may have deviated so far it's pointless. Feel free to close this if not.


CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CoinUtils (missing: COINUTILS_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/FindCoinUtils.cmake:6 (find_package_handle_standard_args)
  src/CMakeLists.txt:431 (find_package)

**Comment by LostFool** [comment]
I am going through the dependencies again first. I'm sure I missed something.

**Comment by simogasp** [comment]
My advice is to start fresh and build all the dependencies with the option provided by the project
https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#building-the-project-with-embedded-dependencies

```bash
git clone https://github.com/alicevision/AliceVision.git --recursive
mkdir build && cd build
cmake -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../install ../AliceVision
make -j2
```
(do not use more than `2` parallel jobs as you may run out of resources)

That will build all the required dependencies, install them in an `install` folder at the root of the project and then build AV

**Comment by LostFool** [comment]
Still struggling. Joy of Ubuntu I guess. I might do a fresh install and try redhat, as per suggestion of a friend.

**Comment by LostFool** [comment]
I never solved all of my issues. I do not know the true underlying problem and do not have the time to continue to play with it at this time. Unfortunately I must close this issue. Instead I'm moving the graphics card to a windows machine and running meshroom there.
