### ISSUE TITLE
How to use custom markers?

### ISSUE THREAD

**Issue by bennie-codemonk** [alicevision/AliceVision#1494]
I want to user a custom marker such as ranging rod and add them to the the available marker type for a custom use case.
I am trying to integrate it as a part of the pipeline, using sfm_Tramsform. 
Can any body guide me?

**Comment by natowi** [comment]
Here is a similar project, wip (extending Meshroom) https://github.com/PIX3LFLUX/MeshroomDFM

If you want to implement something on the AliceVision side, you can take a look at the arpiltag implementation https://github.com/alicevision/AliceVision/pull/950
