### ISSUE TITLE
Build failures on Linux platforms

### ISSUE THREAD

**Issue by zeuner** [alicevision/AliceVision#1499]
The current `develop` branch has compilation issues at least on Arch Linux and Ubuntu Linux. E.g., `cmake` fails:

```
CMake Error at src/CMakeLists.txt:450 (find_package):
  By not providing "FindCoinUtils.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CoinUtils", but CMake did not find one.

  Could not find a package configuration file provided by "CoinUtils" with
  any of the following names:

    CoinUtilsConfig.cmake
    coinutils-config.cmake

  Add the installation prefix of "CoinUtils" to CMAKE_PREFIX_PATH or set
  "CoinUtils_DIR" to a directory containing one of the above files.  If
  "CoinUtils" provides a separate development package or SDK, be sure it has
  been installed.
```

(of course, `CoinUtils` are installed)

**Comment by simogasp** [comment]
We are using Coins libraries from our repository in which CMake exports the targets in modern cmake. You can build and install those, see here https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#dependencies

**Comment by zeuner** [comment]
Is there any perspective for your customized libraries going into Coins mainline? These seem to be active projects, and it doesn't seem favourable having to install multiple versions of the same library, thereby sacrificing the benefit of shared libraries.
