### ISSUE TITLE
Compression of feat/desc files

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#15]
Zip provide a 1.5 compression ratio.

**Comment by pmoulon** [comment]
desc are binary files
feat are ascii ones. So I think the major gain that you can have is only due to compression of the .feat files.

**Comment by fabiencastan** [comment]
NIK_5620.desc (deflated 24%)
NIK_5620.feat (deflated 58%)

**Comment by pmoulon** [comment]
Something like ?
- https://github.com/ariya/FastLZ
- (do you have other ideas)

**Comment by simogasp** [comment]
zlib? It's already in the dependencies, isn't it?

**Comment by pmoulon** [comment]
was just thinking about ask to see if some other alternatives could be faster
