### ISSUE TITLE
Novice question about AliceVision SfM

### ISSUE THREAD

**Issue by evilADevil** [alicevision/AliceVision#1507]
Hello, is there a place where the AliceVision scene data is documented? I'm trying to understand the JSON output of the ConvertSfMFormat, things like observations' scale, pose center related to the actual camera position, etc.? It would be nice to have a description of the reference system to which this data refers.
Thanks a lot for any info that can be provided.

**Comment by natowi** [comment]
[Rotation format](https://github.com/alicevision/meshroom/issues/300#issuecomment-573386855)

The "old notes" may be interesting for you
