### ISSUE TITLE
Not worked: aliceVision_split360Images

### ISSUE THREAD

**Issue by XinyueZ** [alicevision/AliceVision#1554]
--outSfMData, what is that?

**Comment by natowi** [comment]
The Split360Images will increase the amount of views in the SfMData.
This class converts the number of input views into the number of split output views. (outSfMData)

SfMData File
Description: Output SfMData file
Default value in Meshroom: Node.internalFolder + "rig.sfm",
https://github.com/alicevision/Meshroom/blob/develop/meshroom/nodes/aliceVision/Split360Images.py
