### ISSUE TITLE
Error installing dependencies - OpenImageIO has moved

### ISSUE THREAD

**Issue by HughMacdonald** [alicevision/AliceVision#1560]
OpenImageIO has recently (on Friday 29th September) moved from https://github.com/OpenImageIO/oiio to https://github.com/AcademySoftwareFoundation/OpenImageIO

I'm not sure who is necessarily responsible for the location that vcpkg looks, but as the AliceVision fork is quite begind the Microsoft one, it's certainly, I'd imagine, going to be out of date.

**Comment by cbentejac** [comment]
Hi @HughMacdonald,

Thanks for the heads up! I'll have a look at that and check whether our fork needs to be updated accordingly.

**Comment by HughMacdonald** [comment]
I believe that the GitHub repo automatically forwards, but the hash has changed, which is why it fails

**Comment by softlion** [comment]
How to fix that hash quickly to build the ubuntu docker version ?

```
  MD5 does not match expected value
    expected: 'c7df7aaf576e3dbbea7dd89fd2b71871'
      actual: '30e8b433bb71a262a51f56a41fc50ac7'
```

Ok fixed in CMakeLists.txt in "add OpenImageIO". For some reason github does not find the MD5 in the search box.  
 I replaced both the url and the MD5

**Comment by cbentejac** [comment]
Hi,

Both the hash for OIIO in the CMakeLists.txt and our vcpkg fork have been updated, so we're good to go :)
Thanks again for bringing this to our attention!
