### ISSUE TITLE
Is there working app?

### ISSUE THREAD

**Issue by ktulhu2000** [alicevision/AliceVision#1574]
Hi all! 
I need a version supported canon CR3.

But, program cannot be compiled anywhere. I tried Mac, WSL, Ubuntu, Debian, Docker, Windows compiled.
It fails everywhere.

I'll be happy to have one executable that works. BeOS, OS/2 Warp, Minix, whatever that just works -)

**Comment by natowi** [comment]
Download the release here https://github.com/alicevision/Meshroom/releases/tag/v2023.2.0 and add the camera as described here https://github.com/alicevision/Meshroom/wiki/Add-Camera-to-database
