### ISSUE TITLE
Cannot build the programm with vcpkg

### ISSUE THREAD

**Issue by Sweru-bit** [alicevision/AliceVision#1715]
Building the Programm as shown in [INSTALL.md](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md) results in an error because the repository is not available anymore. 

The file in [the vcpkg repo](https://github.com/alicevision/vcpkg) under ports\libzma\portfile.cmake should be changed
from -> REPO bminor/xz
to -> REPO tukaani-project/xz
in line 3.

**Comment by cbentejac** [comment]
This has been fixed on May 22, so I'm now closing this issue. Thanks for reporting it.
