### ISSUE TITLE
Meshroom ad camera to cameraSensor.db

### ISSUE THREAD

**Issue by BoatPelle54** [alicevision/AliceVision#1762]
I can not ad the information Canon EOS R100 22,3 to Meshroom  cameraSensor.db
Not possible to edit after I have open the db. 
The tutorial video is missing and I have tried to follow the instructions

https://github.com/alicevision/Meshroom/wiki/Add-Camera-to-database

BR
Pelle

**Comment by natowi** [comment]
Navigate to the camerasensors.db file using your explorer.
Open the file in Notepad
Add the following in a new line:

`Canon;Canon EOS R100;22.3;usercontribution`

Save 

Did you check that your camera is using exactly this name Canon EOS R100 in the Exif data? Where did you get the sensor width information from?

**Comment by BoatPelle54** [comment]
Hi. I have bought this camera and I got problems to load pics into Meshroom
The sensor width comes from Microsoft Copilot / https://www.digicamdb.com/specs/canon_r100/

Canon EOS R100 Sensor Info & Specs<https://www.digicamdb.com/specs/canon_r100/>
Canon EOS R100 specs and sensor info: 22.3 x 14.9 mm CMOS sensor with 26.82 mm diagonal and crop factor of 1.61. Pixel pitch is 3.71 µm.
www.digicamdb.com
I have update the database and it works.

/pelle

________________________________

**Comment by natowi** [comment]
camera support will be included with the next release
