### ISSUE TITLE
[rig] remove the constraint that main camera has the same reference system of the rig

### ISSUE THREAD

**Issue by simogasp** [alicevision/AliceVision#210]
Currently, we assume that the pose of the rig is the same as the pose of the main camera. Let the main camera have its own subpose (possibly the [I 0]).
This affects:
- [ ] `rigResection`
- [ ] `refineRig`
- [ ] all the `localizeRig()`
- [ ] calibration
- [ ] load/save calibration files
- [ ] all the doc

See comments in PR alicevision/AliceVision#190 as a guide

**Comment by alexs7** [comment]
@simogasp Hello, I wanted to ask about the `rigResection` and the `vec_subPoses` variable. The definition of a `subPose` currently is " the subposes are always wrt the main camera". The main camera is assigned to the identity matrix. The `subPoses` will have to be the relative poses from the origin (the identity matrix, main camera) then ?

**Comment by simogasp** [comment]
Yes, the subPoses are always expressed wrt the main camera, so that the main camera will have as sub-pose the Identity matrix and all the others will have a subPose expressed wrt the main.

The main camera (which basically represents the whole rig) has a pose P expressed wrt the world reference. To get the absolute pose of a camera of the rig you have to multiply  P by the relevant subPose.

**Comment by alexs7** [comment]
Ok thanks!
