### ISSUE TITLE
[cmake] Update and clean CMakeLists

### ISSUE THREAD

**Issue by simogasp** [alicevision/AliceVision#219]
- [x] remove the `include_directories()` and use `target_include_directories()`
- [x] remove the `link_directories()` and use `target_link_directories()`
- [x] change requirement to CMake 3.0 (the minimal for above features)
- [x] update .travis.yml to use a more recent CMake
- [x] remove all `GLOB RECURSE` and use explicit file list
- [x] check external usage

**Comment by fabiencastan** [comment]
Seems to be done now, isn't it?

**Comment by simogasp** [comment]
no first two are not done yet

**Comment by simogasp** [comment]
fix by #440
