### ISSUE TITLE
[CI] Multiple builds on travis

### ISSUE THREAD

**Issue by simogasp** [alicevision/AliceVision#238]
Build the code in travis with different combinations of optional flags in order to detect possible breaks:
- [ ] full
- [ ] without CCTAG, Alembic...

**Comment by fabiencastan** [comment]
Yes, maybe just 2: one with all possible dependencies and one with the minimal dependencies?

**Comment by simogasp** [comment]
At the moment the optional stuff are Boost (which basically enable all popart contributions), CCTag, OpenGV, Alembic and Opencv. Of course we cannot do all the combinations :) Maybe some of them can be removed as optional and made required (Boost?). But yes maybe 2 will do the job
