### ISSUE TITLE
Alignment based on CCTags

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/AliceVision#283]
Currently the "Align" software allows to align a reconstruction on another one if it contains common views.
The goal of this task is to align 2 reconstructions based on common CCTags.

See `src/software/SfM/main_Align.cpp`.

**Comment by mistamun** [comment]
@fabiencastan I'm interested in this. However I can't find the file you're pointing to.

**Comment by fabiencastan** [comment]
Fixed by https://github.com/alicevision/AliceVision/pull/695
