### ISSUE TITLE
Solution generation problem

### ISSUE THREAD

**Issue by kahlan78** [alicevision/AliceVision#345]
Hi all,
I tried to generate the AliceVision solution in my Window 10 machine following the building instructions.
I use VS2017 and CMake 3.10, but CMake failed during the configuration.
Any idea?
Tks

--------------
Detected: Vendor ID 'GenuineIntel'   CPU Family '6'  CPU Model '30'  CPU Flags  ''
Detected CPU: westmere
Checking for C++11 compiler
Checking for C++11 compiler - available
Found OpenMP: /openmp  
OpenMP found.
-- Did not find MOSEK header
-- Did not find MOSEK library
Could not find mosek library on this machine.
Eigen 3.2.4 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/eigen)
Trying to find package Ceres for aliceVision: Ceres_DIR-NOTFOUND
No external CERES detected, using the embedded one.
Flann 1.8.4 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/flann/src/cpp/flann)
CoinUtils 2.9.3 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.15.11 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/osi_clp/Clp/src)
Osi 0.106.10 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/osi_clp/Osi/src/Osi)
Lemon 1.3 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/lemon/lemon)
CMake Warning at CMakeLists.txt:284 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:765 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:311 (find_package)

Boost 1_65_1 found.
Looking for Alembic. 1.5.8
trying to found the all-in-one libAlembic.so
all-in-one not found, try finding individual ones --  ABC_LIBRARY_ALLINONE-NOTFOUND
ABC_LIBRARIES: ABC_LIBRARY-NOTFOUND;ABC_GEOM-NOTFOUND;ABC_COREHDF5-NOTFOUND;ABC_COREABSTRACT-NOTFOUND;ABC_UTIL-NOTFOUND;ABC_COREFACTORY-NOTFOUND;ABC_OGAWA-NOTFOUND;ABC_COREOGAWA-NOTFOUND;ABC_COLLECTION-NOTFOUND;ABC_HDF5-NOTFOUND;ABC_HDF5_HL-NOTFOUND;-ldl;ABC_OPENEXR_LIBS-NOTFOUND;ABC_ILMBASE_IEX-NOTFOUND;ABC_ILMBASE_HALF-NOTFOUND
ABC_INCLUDE_DIR: ABC_INCLUDE_DIR-NOTFOUND;ABC_HALF_INCLUDE_DIR-NOTFOUND
Could NOT find Alembic (missing:  ABC_LIBRARIES ABC_LIBRARY_DIR ABC_INCLUDE_DIR ABC_HDF5_LIBS) 
Alembic NOT FOUND
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
Could NOT find Wget (missing:  WGET_EXECUTABLE) 
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE) 
Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
Eigen 3.2.4 found (include: D:/Progetti/AliceVision/aliceVision/src/dependencies/eigen)
-- Found Eigen version 3.2.4: D:/Progetti/AliceVision/aliceVision/src/dependencies/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Building without LAPACK.
-- Building without SuiteSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
-- Found unordered_map/set in std namespace.
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
-- Do not build any example.
CMake Warning (dev) at dependencies/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at dependencies/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Configured Eigen 3.2.4

CMake Warning at CMakeLists.txt:394 (find_package):
  Could not find a package configuration file provided by "PopSift" with any
  of the following names:

    PopSiftConfig.cmake
    popsift-config.cmake

  Add the installation prefix of "PopSift" to CMAKE_PREFIX_PATH or set
  "PopSift_DIR" to a directory containing one of the above files.  If
  "PopSift" provides a separate development package or SDK, be sure it has
  been installed.

Looking for OpenGV.
OpenGV headers not found!
Could NOT find OpenGV (missing:  OPENGV_LIBRARY OPENGV_INCLUDE_DIR) 
CMake Warning at cmakeFindModules/FindOpenEXR.cmake:56 (message):
  GENERIC_INCLUDE_PATHS: /include;/include
Call Stack (most recent call first):
  cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  CMakeLists.txt:436 (find_package)

CMake Warning at cmakeFindModules/FindOpenEXR.cmake:57 (message):
  Test if file exist:
  D:/vcpkg/packages/openexr_x64-windows/include/OpenEXR/ImfMultiPartInputFile.h
Call Stack (most recent call first):
  cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  CMakeLists.txt:436 (find_package)

CMake Warning at cmakeFindModules/FindOpenEXR.cmake:62 (message):
  Yes, file exist
Call Stack (most recent call first):
  cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  CMakeLists.txt:436 (find_package)

-- Failed to find OpenImageIO - Could not find OpenImageIO include directory, set OPENIMAGEIO_INCLUDE_DIR to directory containing OpenImageIO/imageio.h
-- Failed to find OpenImageIO - Could not find OpenImageIO library, set OPENIMAGEIO_LIBRARY to full path to libopenimageio.
OpenImageIO found.
generatedDir: D:/Progetti/AliceVision/build/generated
CMake Error at aliceVision/camera/CMakeLists.txt:29 (UNIT_TEST):
  Unknown CMake command "UNIT_TEST".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!
See also "D:/Progetti/AliceVision/build/CMakeFiles/CMakeOutput.log".
See also "D:/Progetti/AliceVision/build/CMakeFiles/CMakeError.log".

**Comment by yann-lty** [comment]
It looks like you ran CMake on src/CMakeLists.txt instead of the root CMakeLists.txt. I get the same errors by doing so. Can you confirm this and let me know ? 
We're currently working on improving Windows build by the way, I'll commit some fixes in the next few days !

**Comment by kahlan78** [comment]
Hi,
thanks for your answer.
Hi tried as you suggested and the solution is succesfully generated, but the solution building fails with the following output:

> Errore	C2784	'const Eigen::internal::permut_sparsematrix_product_retval<Eigen::PermutationBase<PermutationDerived>,SparseDerived,1,true> Eigen::operator *(const Eigen::Transpose<Eigen::PermutationBase<PermutationDerived>> &,const Eigen::SparseMatrixBase<Derived> &)': impossibile dedurre un argomento di modello per 'const Eigen::Transpose<Eigen::PermutationBase<PermutationDerived>> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::permut_sparsematrix_product_retval<Eigen::PermutationBase<PermutationDerived>,SparseDerived,2,true> Eigen::operator *(const Eigen::SparseMatrixBase<Derived> &,const Eigen::Transpose<Eigen::PermutationBase<PermutationDerived>> &)': impossibile dedurre un argomento di modello per 'const Eigen::SparseMatrixBase<Derived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::permut_sparsematrix_product_retval<Eigen::PermutationBase<PermutationDerived>,SparseDerived,1,false> Eigen::operator *(const Eigen::PermutationBase<PermutationDerived> &,const Eigen::SparseMatrixBase<Derived> &)': impossibile dedurre un argomento di modello per 'const Eigen::PermutationBase<PermutationDerived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::permut_sparsematrix_product_retval<Eigen::PermutationBase<PermutationDerived>,SparseDerived,2,false> Eigen::operator *(const Eigen::SparseMatrixBase<Derived> &,const Eigen::PermutationBase<PermutationDerived> &)': impossibile dedurre un argomento di modello per 'const Eigen::SparseMatrixBase<Derived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'internal::matrix_type_times_scalar_type<VectorsType::Scalar,OtherDerived>::Type Eigen::operator *(const Eigen::MatrixBase<Derived> &,const Eigen::HouseholderSequence<VectorsType,CoeffsType,Side> &)': impossibile dedurre un argomento di modello per 'const Eigen::MatrixBase<Derived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'internal::enable_if<!Eigen::internal::is_same<Derived::Scalar,Derived::RealScalar>::value,const Eigen::ScaledProduct<Derived>>::type Eigen::operator *(const Derived::RealScalar &,const Eigen::ProductBase<Derived,_Lhs,_Rhs> &)': impossibile dedurre un argomento di modello per 'const Eigen::ProductBase<Derived,_Lhs,_Rhs> &' da 'const aliceVision::Mat3'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::ScaledProduct<Derived> Eigen::operator *(const Derived::Scalar &,const Eigen::ProductBase<Derived,_Lhs,_Rhs> &)': impossibile dedurre un argomento di modello per 'const Eigen::ProductBase<Derived,_Lhs,_Rhs> &' da 'const aliceVision::Mat3'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'internal::enable_if<!Eigen::internal::is_same<Derived::Scalar,Derived::RealScalar>::value,const Eigen::ScaledProduct<Derived>>::type Eigen::operator *(const Eigen::ProductBase<Derived,_Lhs,_Rhs> &,const Derived::RealScalar &)': impossibile dedurre un argomento di modello per 'const Eigen::ProductBase<Derived,_Lhs,_Rhs> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::ScaledProduct<Derived> Eigen::operator *(const Eigen::ProductBase<Derived,_Lhs,_Rhs> &,const Derived::Scalar &)': impossibile dedurre un argomento di modello per 'const Eigen::ProductBase<Derived,_Lhs,_Rhs> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::transposition_matrix_product_retval<TranspositionDerived,Derived,1,false> Eigen::operator *(const Eigen::TranspositionsBase<TranspositionsDerived> &,const Eigen::MatrixBase<Derived> &)': impossibile dedurre un argomento di modello per 'const Eigen::TranspositionsBase<TranspositionsDerived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::transposition_matrix_product_retval<TranspositionsDerived,Derived,2,false> Eigen::operator *(const Eigen::MatrixBase<Derived> &,const Eigen::TranspositionsBase<TranspositionsDerived> &)': impossibile dedurre un argomento di modello per 'const Eigen::MatrixBase<Derived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::permut_matrix_product_retval<PermutationDerived,Derived,1,false> Eigen::operator *(const Eigen::PermutationBase<PermutationDerived> &,const Eigen::MatrixBase<Derived> &)': impossibile dedurre un argomento di modello per 'const Eigen::PermutationBase<PermutationDerived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2784	'const Eigen::internal::permut_matrix_product_retval<PermutationDerived,Derived,2,false> Eigen::operator *(const Eigen::MatrixBase<Derived> &,const Eigen::PermutationBase<PermutationDerived> &)': impossibile dedurre un argomento di modello per 'const Eigen::MatrixBase<Derived> &' da 'double'	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2677	'*' binario: non è stato trovato alcun operatore globale che accetti il tipo 'const aliceVision::Mat3'. È anche possibile che non vi siano conversioni accettabili.	aliceVision_geometry	d:\progetti\alicevision\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp	26	
> Errore	C2065	'M_PI': identificatore non dichiarato	aliceVision_multiview	D:\Progetti\AliceVision\aliceVision\src\aliceVision\numeric\polynomial.hpp	69	
> Errore	C2065	'M_PI': identificatore non dichiarato	aliceVision_multiview	D:\Progetti\AliceVision\aliceVision\src\aliceVision\numeric\polynomial.hpp	70	
> Errore	C1083	Non è possibile aprire il file inclusione: 'OpenEXR/ImathVec.h': No such file or directory	aliceVision_image	d:\vcpkg\packages\openimageio_x64-windows\include\openimageio\simd.h	56	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_undistoBrown	D:\Progetti\AliceVision\build\src\samples\undistoBrown\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_repeatabilityDataset	D:\Progetti\AliceVision\build\src\samples\featuresRepeatability\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_describeAndMatch	D:\Progetti\AliceVision\build\src\samples\imageDescriberMatches\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_kvldFilter	D:\Progetti\AliceVision\build\src\samples\kvldFilter\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustHomography	D:\Progetti\AliceVision\build\src\samples\robustHomography\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustFundamentalGuided	D:\Progetti\AliceVision\build\src\samples\robustFundamentalGuided\LINK	1	
> Errore	C2666	'std::fpos<_Mbstatet>::operator ==': 3 overload presentano conversioni simili	aliceVision_sfm	D:\Progetti\AliceVision\aliceVision\src\aliceVision\sfm\LocalBundleAdjustmentCeres.cpp	222	
> Errore	C2666	'std::fpos<_Mbstatet>::operator ==': 3 overload presentano conversioni simili	aliceVision_sfm	D:\Progetti\AliceVision\aliceVision\src\aliceVision\sfm\LocalBundleAdjustmentData.cpp	117	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_siftMatching	D:\Progetti\AliceVision\build\src\samples\siftPutativeMatches\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustHomographyGuided	D:\Progetti\AliceVision\build\src\samples\robustHomographyGuided\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustFundamental	D:\Progetti\AliceVision\build\src\samples\robustFundamental\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_exportMatches	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportMVE2	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportMVSTexturing	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportMatlab	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_exportKeypoints	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_exportCameraFrustums	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	C1083	Non è possibile aprire il file inclusione: 'OpenEXR/ImathVec.h': No such file or directory	aliceVision_keyframe	d:\vcpkg\packages\openimageio_x64-windows\include\openimageio\simd.h	56	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_multiview.lib'	aliceVision_featureMatching	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_globalSfM	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportUndistortedImages	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_exportTracks	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	C2059	errore di sintassi: 'costante'	aliceVision_samples_robustEssentialBA	D:\Progetti\AliceVision\aliceVision\src\dependencies\ceres-solver\internal\ceres\miniglog\glog\logging.h	114	
> Errore	C2059	errore di sintassi: 'costante'	aliceVision_samples_robustEssentialBA	D:\Progetti\AliceVision\aliceVision\src\dependencies\ceres-solver\internal\ceres\miniglog\glog\logging.h	128	
> Errore	C2589	'costante': token non valido a destra di '::'	aliceVision_samples_robustEssentialBA	D:\Progetti\AliceVision\aliceVision\src\dependencies\ceres-solver\internal\ceres\miniglog\glog\logging.h	128	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportMeshlab	D:\Progetti\AliceVision\build\src\software\export\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_imageMatching	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_featureExtraction	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustEssential	D:\Progetti\AliceVision\build\src\samples\robustEssential\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_incrementalSfM	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_qualityEvaluation	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_prepareDenseScene	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_utils_sfmColorHarmonize	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_sfmAlignment	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_samples_robustEssentialSpherical	D:\Progetti\AliceVision\build\src\samples\robustEssentialSpherical\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_frustumFiltering	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_convertUID	D:\Progetti\AliceVision\build\src\software\convert\LINK	1	
> Errore	C1083	Non è possibile aprire il file inclusione: 'OpenEXR/ImathVec.h': No such file or directory	aliceVision_utils_keyframeSelection	d:\vcpkg\packages\openimageio_x64-windows\include\openimageio\simd.h	56	
> Errore	C1083	Non è possibile aprire il file inclusione: 'OpenEXR/ImathVec.h': No such file or directory	aliceVision_utils_split360Images	d:\vcpkg\packages\openimageio_x64-windows\include\openimageio\simd.h	56	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_convertRAW	D:\Progetti\AliceVision\build\src\software\convert\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_voctreeCreation	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_cameraLocalization	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_voctreeQueryUtility	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_sfmLocalization	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_utils_voctreeStatistics	D:\Progetti\AliceVision\build\src\software\utils\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_rigCalibration	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_cameraInit	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_rigLocalization	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_computeSfMColor	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_convertFloatDescriptorToUchar	D:\Progetti\AliceVision\build\src\software\convert\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_convertSfMFormat	D:\Progetti\AliceVision\build\src\software\convert\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_sfm.lib'	aliceVision_computeStructureFromKnownPoses	D:\Progetti\AliceVision\build\src\software\pipeline\LINK	1	
> Errore	LNK1181	impossibile aprire il file di input '..\..\..\Windows-AMD64-Release\Release\aliceVision_image.lib'	aliceVision_exportPMVS	D:\Progetti\AliceVision\build\src\software\export\LINK	1	

Any idea?
Tks

**Comment by yann-lty** [comment]
I see that you're using vcpkg. The version of eigen it builds (3.3) is actually not yet supported and generates the first error in your build log.  
But AliceVision comes with a few embedded [dependencies ](https://github.com/alicevision/AliceVision/tree/develop/src/dependencies) in case they are not available externally, and eigen is one of them.
Could you try re-configuring your project without vcpkg's eigen by either removing it or (if this is not possible for you) use **vcpkg export** command to create an isolated environment with only a subset of libraries (without eigen) and use this environment to build AliceVision ?
This could be done with something like that : 
```
# from a Visual 2017 x64 command line
# create isolated environment for AliceVision
cd path/to/vcpkg/
vcpkg.exe export boost openimageio --raw --triplet x64-windows --output=env-alicevision
set VCPKG_ROOT=path/to/vcpkg/env-alicevision
cd path/to/AliceVision
mkdir build && cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64
# and then open aliceVision.sln inside this 'build' folder
```
It seems that you also have an issue with OpenEXR headers. This is unexpected, as it is declared as a build dependency of OpenImageIO in vcpkg. Was OpenEXR correctly built and installed on your side (headers should be in vcpkg\installed\x64-windows\include\\**OpenEXR**) ?
