### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by embeh** [alicevision/AliceVision#368]
Any chance of providing a pre-built Windows binary for AliceVision?
Looking at the 16 (+ 10 optional) [dependencies](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md), this might be a major effort to build on Windows for those that don't meet those requirements yet.

**Comment by yann-lty** [comment]
Yes, we're planning to provide prebuilt binaries at some point (hopefully very soon). Our goal is to release a complete package with a user interface called Meshroom (a video preview is available  [here](https://www.youtube.com/watch?v=v_O6tYKQEBA)).

In the meantime, regarding Windows build, I would highly recommend to use [vcpkg](https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/) to get all the required dependencies. Everything is available (boost, openimageio, alembic, geogram, eigen, ceres...). 
We have a fork [here](https://github.com/alicevision/vcpkg/tree/alicevision_master) - branch alicevision_master - where we updated some library versions when needed. At this point, openimageio v1.8.9 is the last one not being merged in Microsoft's repository [yet](https://github.com/Microsoft/vcpkg/pull/3051).

We also need to update build instructions for Windows to make this more clear.

**Comment by embeh** [comment]
Thanks! Looking into vcpkg now...

**Comment by fabiencastan** [comment]
@embeh Does it work for you with VCPKG?

**Comment by embeh** [comment]
Not yet.

**Comment by s-wtnb** [comment]
I used vcpkg to create minimal dependency libraries, but fails CMAKE of AliceVision.
The created libraries are other than Internal.
They are below.
Boost> = 1.60.0
Eigen> = 3.3.4
Ceres> = 1.10.0
OpenEXR> = 2.2.0
OpenImageIO> = 1.8.7
Geogram> = 1.5.4 (https://gforge.inria.fr/frs/?group_id=5833)
zlib

These libraries were created with vcpkg (https://github.com/alicevision/vcpkg/tree/alicevision_master) Folked by AliceVision.
CMAKE(GUI) is 3.10.2. and VisualStudio  is 2017.
The following error message appears, it seems Boost is not recognized.
Also, the CPU(Core i7 7700K) is not recognized.

```
The C compiler identification is MSVC 19.13.26129.0
The CXX compiler identification is MSVC 19.13.26129.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
----------------------------------------
ALICEVISION_BUILD_DEPENDENCIES: OFF
ALICEVISION_BUILD_TESTS: OFF
AV_BUILD_JPEG: ON
AV_BUILD_PNG: ON
CMAKE_BUILD_TYPE: Release
DEPS_CMAKE_BUILD_TYPE: Release
CMAKE_INSTALL_PREFIX: C:/Program Files/aliceVision
----------------------------------------
CMake version: 3.10
** ALICEVISION_BUILD_DOC: 'AUTO'
** ALICEVISION_USE_OPENMP: 'ON'
** ALICEVISION_USE_CCTAG: 'AUTO'
** ALICEVISION_USE_POPSIFT: 'AUTO'
** ALICEVISION_USE_OPENGV: 'AUTO'
** ALICEVISION_USE_ALEMBIC: 'AUTO'
** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
** ALICEVISION_USE_CUDA: 'ON'
** ALICEVISION_USE_OPENCV: 'OFF'
target changed from "" to "auto"
Detected: Vendor ID 'GenuineIntel'   CPU Family '6'  CPU Model '158'  CPU Flags  ''
CMake Warning at src/cmake/OptimizeForArchitecture.cmake:88 (message):
  Your CPU (family 6, model 158) is not known.  Auto-detection of
  optimization flags failed and will use the 65nm Core 2 CPU settings.
Call Stack (most recent call first):
  src/cmake/OptimizeForArchitecture.cmake:150 (AutodetectHostArchitecture)
  src/CMakeLists.txt:143 (OptimizeForArchitecture)


Detected CPU: merom
Performing Test check_c_compiler_flag__arch_SSE2
Performing Test check_c_compiler_flag__arch_SSE2 - Success
Performing Test check_cxx_compiler_flag__arch_SSE2
Performing Test check_cxx_compiler_flag__arch_SSE2 - Success
Checking for C++11 compiler
Checking for C++11 compiler - available
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
OpenMP found.
CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Warning at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:224 (find_package)


CMake Error at src/CMakeLists.txt:229 (message):
  Failed to find Boost.


CMake Error at src/CMakeLists.txt:230 (message):
  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.


CMake Error at C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/SWTNB/Desktop/tool/cmake-3.10.2-win64-x64/share/cmake-3.10/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/cmake/FindOpenEXR.cmake:22 (find_package)
  src/CMakeLists.txt:254 (find_package)


Configuring incomplete, errors occurred!
See also "E:/github/AliceVision/CMakeFiles/CMakeOutput.log".
See also "E:/github/AliceVision/CMakeFiles/CMakeError.log".
```

**Comment by MarjorieCoulin** [comment]
I there, I get exactly the same Boost issue (CMake 3.11.2, VS 2017, vcpkg alicevision branch).
Did anyone solve it ?

**Comment by MarjorieCoulin** [comment]
@embeh @s-wtnb I there, I get exactly the same Boost issue (CMake 3.11.2, VS 2017, vcpkg alicevision branch).
Did anyone solve it ?

**Comment by fabiencastan** [comment]
Does anyone still have the problem?

It seems that none of the vcpkg libraries are detected. Are you sure to provide the correct path to CMAKE_TOOLCHAIN_FILE?

**Comment by s-wtnb** [comment]
vcpkg(https://github.com/Microsoft/vcpkg) accepted to OIIO verup, I built using it.
Although Boost's problem was solved, the problem of #355 came to occur.

```
----------------------------------------
ALICEVISION_BUILD_DEPENDENCIES: OFF
ALICEVISION_BUILD_TESTS: OFF
AV_BUILD_JPEG: ON
AV_BUILD_PNG: ON
CMAKE_BUILD_TYPE: Release
DEPS_CMAKE_BUILD_TYPE: Release
CMAKE_INSTALL_PREFIX: C:/Program Files/aliceVision
----------------------------------------
CMake version: 3.11
** ALICEVISION_BUILD_DOC: 'AUTO'
** ALICEVISION_USE_OPENMP: 'ON'
** ALICEVISION_USE_CCTAG: 'AUTO'
** ALICEVISION_USE_POPSIFT: 'AUTO'
** ALICEVISION_USE_OPENGV: 'AUTO'
** ALICEVISION_USE_ALEMBIC: 'AUTO'
** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
** ALICEVISION_USE_CUDA: 'ON'
** ALICEVISION_USE_OPENCV: 'OFF'
Detected Host CPU: kaby-lake
Checking for C++11 compiler
Checking for C++11 compiler - available
OpenMP found.
Boost 1_67 found.
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR: E:/AliceVision/installed/x64-windows/
Call Stack (most recent call first):
  src/CMakeLists.txt:267 (find_package)


OpenEXR found. (Version 2.2.0)
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR: E:/AliceVision/installed/x64-windows/
Call Stack (most recent call first):
  src/cmake/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:277 (find_package)


OpenImageIO found.
CMake Error at src/cmake/FindMosek.cmake:5 (if):
  if given arguments:

    "EXISTS" "AND" "EXISTS"

  Unknown arguments specified
Call Stack (most recent call first):
  src/CMakeLists.txt:294 (find_package)


Configuring incomplete, errors occurred!
See also "E:/AliceVisionDev/install/CMakeFiles/CMakeOutput.log".
See also "E:/AliceVisionDev/install/CMakeFiles/CMakeError.log".
```

**Comment by fabiencastan** [comment]
That's strange.
Could you try to add quotes like that in `src/cmake/FindMosek.cmake`:
`if(EXISTS "${MOSEK_INCLUDE}" AND EXISTS "${MOSEK_LIB}")`
To see if it changes something.

**Comment by s-wtnb** [comment]
MOSEK library is not essential, I did CMAKE without including MOSEK.
I can create .sln without problems and build it!
thx.

**Comment by MarjorieCoulin** [comment]
@s-wtnb May I ask how you overcame your Boost problem ?
I just pulled AliceVision to the latest and stil get the same CMake Warning list as before

PS C:\Users\ICO-Workstation-03\Documents\Marjorie\AliceVision\build> cmake -DCMAKE_TOOLCHAIN_FILE=..\..\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 14 2015" -A x64 -T v140,host=x64 ..
-- Selecting Windows SDK version  to target Windows 10.0.16299.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ----------------------------------------
-- ALICEVISION_BUILD_DEPENDENCIES: OFF
-- ALICEVISION_BUILD_TESTS: OFF
-- AV_BUILD_JPEG: ON
-- AV_BUILD_PNG: ON
-- CMAKE_BUILD_TYPE: Release
-- DEPS_CMAKE_BUILD_TYPE: Release
-- CMAKE_INSTALL_PREFIX: C:/Program Files (x86)/aliceVision
-- ----------------------------------------
CMake version: 3.11
-- ** ALICEVISION_BUILD_DOC: 'AUTO'
-- ** ALICEVISION_USE_OPENMP: 'ON'
-- ** ALICEVISION_USE_CCTAG: 'AUTO'
-- ** ALICEVISION_USE_POPSIFT: 'AUTO'
-- ** ALICEVISION_USE_OPENGV: 'AUTO'
-- ** ALICEVISION_USE_ALEMBIC: 'AUTO'
-- ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
-- ** ALICEVISION_USE_CUDA: 'ON'
-- ** ALICEVISION_USE_OPENCV: 'OFF'
-- target changed from "" to "auto"
-- Detected Host CPU: ivy-bridge
-- Performing Test check_c_compiler_flag__arch_AVX
-- Performing Test check_c_compiler_flag__arch_AVX - Success
-- Performing Test check_cxx_compiler_flag__arch_AVX
-- Performing Test check_cxx_compiler_flag__arch_AVX - Success
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- OpenMP found.
CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:238 (find_package)


CMake Error at src/CMakeLists.txt:243 (message):
  Failed to find Boost.


CMake Error at src/CMakeLists.txt:244 (message):
  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.


CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/cmake/FindOpenEXR.cmake:22 (find_package)
  src/CMakeLists.txt:267 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/ICO-Workstation-03/Documents/Marjorie/AliceVision/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/ICO-Workstation-03/Documents/Marjorie/AliceVision/build/CMakeFiles/CMakeError.log".

**Comment by s-wtnb** [comment]
@MarjorieCoulin sorry, I changed the environment, it is described below.
VS2015(**NOT VS2017**), vcpkg(**NOT Alicevision folk ver**, use original ver), CMAKE3.11.2(GUI).
Because latest VS2017(15.7.3) is not supported by CUDA.

As I see your error message, CMAKE does not seem to be able to find zlib and boost paths.
If install boost different from the ones you installed with vcpkg, the path seems to conflict.
Therefore, I checked and fixed all paths on CMAKE.

It is my paths of vcpkg.
```
E:/
|-- AliceVision/
    |-- buildtreess/
    |-- docs/
    |-- downloads/
    |-- installed/
    |-- etc/
    |-- vcpkg.exe
```

It is an image of CMAKE with my paths.
![ws000119](https://user-images.githubusercontent.com/25291845/41697389-7e7d2504-7553-11e8-9ceb-caa6b792e760.JPG)
![ws000120](https://user-images.githubusercontent.com/25291845/41697400-8f5362ee-7553-11e8-8e48-0deb84ac4b0a.JPG)

**Comment by MarjorieCoulin** [comment]
@s-wtnb Thanks for your help !
The situation improved a lot by providing, as you said, the vcpkg include directory to Boost and ZLib (vcpkg\installed\x64-windows\include), and wherever CMake could not make it up itself (OpenEXR, OIIO, Geogram, Eigen3, CUDA, etc.), then running Configure again.
I encountered your MOSEK issue, commented most of FindMosek.cmake as hinted by @fabiencastan, which at least made CMake bypass the mosek library requirement.

Now I've been able to generate (and build) a VS solution :)

Moreover I had no issue building the project using VS2017 15.7.4 and CUDA 9.2. What kind of problem did you encounter @s-wtnb ?

**Comment by MarjorieCoulin** [comment]
Alright, thanks for the info. That's weird, I used VS2017 15.7.4 and encountered no such error during AliceVision build. Is it supposed to be an issue later on ?

**Comment by s-wtnb** [comment]
Since I encountered this VS2017 + CUDA VERSION's error during AliceVision build, there seems to be no problem if the build is successful.

**Comment by MarjorieCoulin** [comment]
Did you select the 2015.3 v14.00 (140) toolkit when you installed VS2017 ?

**Comment by s-wtnb** [comment]
@MarjorieCoulin It seems to be selected.
(Image is in Japanese, sorry)
![vsinstaller](https://user-images.githubusercontent.com/25291845/41825603-1c652c60-785d-11e8-895e-3775ae09d2fc.jpg)
