### ISSUE TITLE
configuring project in CMake by -DAV_BUILD_PNG=OFF does not work

### ISSUE THREAD

**Issue by mshafiei** [alicevision/AliceVision#377]
### Problem
Hi all,

According to Install.md I should be able to configure the project
by CMake by disabling AV_BUILD_PNG. But in this case I get the
following error in CMake,

> CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2295 (get_property):
>   get_property could not find TARGET png.  Perhaps it has not yet been
>   created.

I am using Windows 7, Visual Studio 2013 and CMake-gui.

Apparently another dependency in the project (openimageio) requires PNG
and that is making this issue.

**Comment by fabiencastan** [comment]
That's a mistake. I will fix it.
By the way, we have to clarify the `install.md` but the option to build an all-in-one version has been done and tested only on Linux.
On Windows, we recommend using VCPKG to install all the dependencies.
