### ISSUE TITLE
Can't compile under Linux Mint 18.3

### ISSUE THREAD

**Issue by SteffenDuenner** [alicevision/AliceVision#386]
Hi there,

I'm trying to make AliceVision under Linux Mint 18.3 using the method proposed in the install.md called "Building the project with embedded dependencies". I'm not a coder, so please be gentle ;)

All downloads and compiles without problems, expect for the link to boost ("The requested URL returned error: 404 Not Found") and the link to libpng ("HTTP/1.1 301 Moved Permanently").

Is that something that needs to get fixed on your side (e.g. by updating the URLs)?

Cheers,
Steffen

**Comment by fabiencastan** [comment]
Hi Steffen,

I just tried to rebuild it from scratch with embedded dependencies and it works fine.
I don't know what to change because there are already 3 fallbacks for boost and libpng (including a fallback on our github as github seems to be more stable than the others).

Could you provide your full log to see if it really tries all the URLs?

**Comment by SteffenDuenner** [comment]
Thanks for your reply,

I just tried making again on a completely different system and it fails in the same way.
I hope this is the right log and it helps to resolve problems:

[log.txt](https://github.com/alicevision/AliceVision/files/1961329/log.txt)

Regards
Steffen

**Comment by fabiencastan** [comment]
Which version of cmake are you using?
It seems that the `URL` argument of `ExternalProject_Add` supports multiple URLs only from cmake 3.7 :(
cmake 3.7: https://cmake.org/cmake/help/v3.7/module/ExternalProject.html
cmake 3.6: https://cmake.org/cmake/help/v3.6/module/ExternalProject.html

**Comment by fabiencastan** [comment]
So you can try to update cmake or just remove the alternative URLs (it's only used for png and boost).
