### ISSUE TITLE
Texturing Bug with small "Texture Side" values

### ISSUE THREAD

**Issue by paulparneix** [alicevision/AliceVision#395]
### Problem

"Info" logging level with default UV unwrap method writes huges log files and slow down process a lot.
(1 Go log with 5 photos / 200K polys mesh)

**Possible Workaround:** 

move : 
```
[16:15:05.926196][info] Filled with 0 charts.
[16:15:05.926196][info] 	- texture atlas 2254369
[16:15:05.926196][info] Filled with 0 charts.
[16:15:05.926196][info] 	- texture atlas 2254370
...
```
prints to debug level.

### Versions

* AliceVision branch/version: develop
* OS: Windows 10 x64
* C++ compiler: MSVC 2017 v140

**Comment by yann-lty** [comment]
This actually looks like a bug during the texturing process. It fails to fill up texture atlases with charts and keeps generating empty ones; a test is missing here.
Have you made any change to the "Texturing" node parameters or only using default values ?
Could you try to increase the "Texture Side" parameter ?

**Comment by paulparneix** [comment]
Hi yann,

You're right, I reduced the Texture Side to make the process faster. no problem with default 8K resolution.
