### ISSUE TITLE
Windows build, followed instructions, still missing dependencies

### ISSUE THREAD

**Issue by antithing** [alicevision/AliceVision#399]
### Problem

I have followed the instructions for a windows build using vcpkg. 

I have installed the following:

`vcpkg install zlib boost openimageio openexr alembic geogram eigen3 ceres`

When i now run the cmake command, I get:

-- EIGEN: 3.3.4
-- CERES: 1.14.0
-- FLANN: 1.8.4 (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)

```
-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY)
-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)

```

### Steps to Reproduce

1. [First Step]
git clone https://github.com/alicevision/AliceVision.git --recursive

2. [Second Step]

vcpkg install zlib boost openimageio openexr alembic geogram eigen3 ceres

3. [Third step]

cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T v140,host=x64

Do I need to enable something to install these last dependencies?

**Comment by fabiencastan** [comment]
Yes, we need to clean the cmake messages.
These dependencies are not required, you should be able to build the full project without problem.

**Comment by antithing** [comment]
Ah I see. maybe it is another issue. My full build log is:

E:\AliceVision\AliceVision\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=E:\vcpkg-master\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T v140,host=x64
-- ----------------------------------------
-- ALICEVISION_BUILD_DEPENDENCIES: OFF
-- ALICEVISION_BUILD_TESTS: OFF
-- AV_BUILD_JPEG: ON
-- AV_BUILD_PNG: ON
-- CMAKE_BUILD_TYPE: Release
-- DEPS_CMAKE_BUILD_TYPE: Release
-- CMAKE_INSTALL_PREFIX: C:/Program Files/aliceVision
-- ----------------------------------------
CMake version: 3.11
-- ** ALICEVISION_BUILD_DOC: 'AUTO'
-- ** ALICEVISION_USE_OPENMP: 'ON'
-- ** ALICEVISION_USE_CCTAG: 'AUTO'
-- ** ALICEVISION_USE_POPSIFT: 'AUTO'
-- ** ALICEVISION_USE_OPENGV: 'AUTO'
-- ** ALICEVISION_USE_ALEMBIC: 'AUTO'
-- ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
-- ** ALICEVISION_USE_CUDA: 'ON'
-- ** ALICEVISION_USE_OPENCV: 'OFF'
-- Detected Host CPU: haswell
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Found OpenMP: TRUE
-- OpenMP found.
-- Boost 1_67 found.
-- OpenEXR found. (Version 2.2.0)
-- OpenImageIO found.
-- Did not find MOSEK header
-- Did not find MOSEK library
-- Could not find mosek library on this machine.
-- Trying to find package Ceres for aliceVision: E:/vcpkg-master/vcpkg-master/installed/x64-windows/share/ceres
-- Found installed version of Eigen: E:/vcpkg-master/vcpkg-master/installed/x64-windows/share/eigen3
-- Found required Ceres dependency: Eigen version 3.3.4 in E:/vcpkg-master/vcpkg-master/installed/x64-windows/include/eigen3
-- Found required Ceres dependency: glog
-- Ceres version 1.14.0 detected here: E:/vcpkg-master/vcpkg-master/installed/x64-windows was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
-- Found Ceres version: 1.14.0 installed in: E:/vcpkg-master/vcpkg-master/installed/x64-windows with components: [SchurSpecializations, C++11, OpenMP, Multithreading]
-- Ceres include dirs E:/vcpkg-master/vcpkg-master/installed/x64-windows/include;E:/vcpkg-master/vcpkg-master/installed/x64-windows/include/eigen3;E:/vcpkg-master/vcpkg-master/installed/x64-windows/include
-- Ceres libraries ceres
-- Flann 1.8.4 found (include: E:/AliceVision/AliceVision/src/dependencies/flann/src/cpp/flann)
-- CoinUtils 2.9.3 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.15.11 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/Clp/src)
-- Osi 0.106.10 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: E:/AliceVision/AliceVision/src/dependencies/lemon/lemon)
-- Alembic version 1.7.8 found.
-- Could NOT find PopSift (missing: PopSift_DIR)
-- Looking for OpenGV.
-- OpenGV headers not found!
-- Could NOT find OpenGV (missing: OPENGV_LIBRARY OPENGV_INCLUDE_DIR)
-- Looking for UncertaintyTE.
-- UncertaintyTE headers not found!
-- UncertaintyTE library include not found
-- UncertaintyTE library not found
-- Could NOT find UncertaintyTE (missing: UNCERTAINTYTE_LIBRARY UNCERTAINTYTE_INCLUDE_DIR)
-- Geogram: E:/vcpkg-master/vcpkg-master/installed/x64-windows/debug/lib/geogram.lib, E:/vcpkg-master/vcpkg-master/installed/x64-windows/include
MSVC compiler found.
OpenMP found. OpenMP activated in release.
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
CMake Error at src/CMakeLists.txt:634 (message):
  Failed to find CUDA (>= 7.0).


-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
generatedDir: E:/AliceVision/AliceVision/build/src/generated


** AliceVision version: 0.9.5
** Build Shared libs: OFF
** Build SfM part: ON
** Build MVS part: ON
** Build AliceVision tests: OFF
** Build AliceVision documentation: 0
** Build AliceVision samples programs: ON
** Build AliceVision+OpenCV samples programs: 0
** Build UncertaintyTE: 0
** Build MeshSDFilter: 1
** Build Alembic exporter: 1
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: 1
** Use CUDA: 0
** Use OpenCV SIFT features: 0
** Use CCTAG markers: 0
** Use OpenGV for rig localization: 0


-- EIGEN: 3.3.4
-- CERES: 1.14.0
-- FLANN: 1.8.4 (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY)
-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)
CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "E:/AliceVision/AliceVision/build/CMakeFiles/CMakeOutput.log".
See also "E:/AliceVision/AliceVision/build/CMakeFiles/CMakeError.log".

E:\AliceVision\AliceVision\build>CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if):
CMake Error: The source directory "E:/AliceVision/AliceVision/build/(if):" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

E:\AliceVision\AliceVision\build>

**Comment by antithing** [comment]
Ah, Its the CUDA error, right? i am on a new build machine, and have not installed CUDA yet.

**Comment by antithing** [comment]
Built. Thank you for your time.

**Comment by fabiencastan** [comment]
Great. Looking forward to get your feedback on your results. ;)

**Comment by antithing** [comment]
Hey again, sorry, on trying to build teh visual studio sln, i get many, many errors. in aliceVision_sfm:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0145	member "boost::filesystem::path::separator" may not be initialized	aliceVision_sfm	e:\vcpkg-master\vcpkg-master\installed\x64-windows\include\boost\filesystem\path.hpp	65	
Error (active)	E0145	member "boost::filesystem::path::preferred_separator" may not be initialized	aliceVision_sfm	e:\vcpkg-master\vcpkg-master\installed\x64-windows\include\boost\filesystem\path.hpp	66	
Error (active)	E0145	member "boost::filesystem::path::dot" may not be initialized	aliceVision_sfm	e:\vcpkg-master\vcpkg-master\installed\x64-windows\include\boost\filesystem\path.hpp	67	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function	aliceVision_track	e:\alicevision\alicevision\src\alicevision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\LocalBundleAdjustmentData.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\pipeline\sequential\ReconstructionEngine_sequentialSfM.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\LocalBundleAdjustmentCeres.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\pipeline\structureFromKnownPoses\StructureEstimationFromKnownPoses.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\pipeline\global\GlobalSfMTranslationAveragingSolver.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\pipeline\global\GlobalSfMRotationAveragingSolver.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\pipeline\global\ReconstructionEngine_globalSfM.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\FrustumFilter.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	
Error	C2668	'boost::container::find_if': ambiguous call to overloaded function (compiling source file E:\AliceVision\AliceVision\src\aliceVision\sfm\utils\syntheticScene.cpp)	aliceVision_sfm	E:\AliceVision\AliceVision\src\aliceVision\track\Track.hpp	340	


also, the #include to `half.h` is missing from a few of the projects.

**Comment by fabiencastan** [comment]
Yes, I'm working on the setup of appveyor and get similar issues:
https://github.com/alicevision/AliceVision/pull/396

**Comment by antithing** [comment]
Ah it looks like it is an ambiguous call between boost::container::fin_if, and std::find_if, as there is no namespace. I have added the namespace boost::container::

here

https://github.com/alicevision/AliceVision/blob/f7a5e7273c0e618ae0a503e392fea269a1ebe9e3/src/aliceVision/track/Track.hpp#L340

and it compiles

**Comment by dreness** [comment]
Same!

    ========== Build: 103 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Thanks @fabiencastan and @antithing :)

**Comment by fabiencastan** [comment]
Great to hear that!

**Comment by natowi** [comment]
I am testing the [Build instructions](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md)  on Win10x64 with Vcpkg (to test new features in Meshroom). So I set up the environment and built the required dependencies, but I don´t get the Alicevision build. CUDA v9 is installed. Any suggestions?

`-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)`
`-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)`
`-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")`
`-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)`
`-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY)`
`-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)`
`-- Looking for sys/types.h`
`-- Looking for sys/types.h - found`
`-- Looking for stdint.h`
`-- Looking for stdint.h - found`
`-- Looking for stddef.h`
`-- Looking for stddef.h - found`
`-- Check size of long long`
`-- Check size of long long - done`

`CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if) Policy CMP0054 is not set: Only interpret if() arguments as variables or keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy details.  Use the cmake_policy command to set the policy and suppress thiswarning.
[err.txt](https://github.com/alicevision/AliceVision/files/2604904/err.txt)
[err.txt](https://github.com/alicevision/AliceVision/files/2604909/err.txt)
[err.txt](https://github.com/alicevision/AliceVision/files/2604911/err.txt)


`

`  Quoted variables like "MSVC" will no longer be dereferenced when the policy is set to NEW.  Since the policy is not set the OLD behavior will be used. This warning is for project developers.  Use -Wno-dev to suppress it.`

`CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:22 (if): Policy CMP0054 is not set: Only interpret if() arguments as variables or keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy details.  Use the cmake_policy command to set the policy and suppress this warning.`

`  Quoted variables like "MSVC" will no longer be dereferenced when the policy is set to NEW.  Since the policy is not set the OLD behavior will be used.`
`This warning is for project developers.  Use -Wno-dev to suppress it.`

`-- Configuring incomplete, errors occurred!`
