### ISSUE TITLE
Compiling on an old CPU

### ISSUE THREAD

**Issue by SteffenDuenner** [alicevision/AliceVision#401]
i there,

I'm a complete noob when it comes to compiling stuff but at least I can successfully compile Blender and Colmap on Linux Mint 18.3 ;)

I'm getting relatively far with compiling AliceVision using the "Building the project with embedded dependencies" instructions, but now I'm stuck at an error message like this:
```
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9231): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9244): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9255): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9268): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9279): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9292): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9303): error: argument of type "const void *" is incompatible with parameter of type "const double *"
```

etc.

I searched this whole "forum" but the only hint I found is that someone wasn't able to compile OIIO with the avx512 thingy set.
I think this might be the same problem or at least related.

My CPU is a 10+ years old X5365 and it doesn't support avx512 of course. The maximum is SSSE3.

How can I tell cmake to use SSSE3 as a maximum arch for compiling?

Or am I on the wrong track?

Thanks!!

**Comment by fabiencastan** [comment]
Hi,
This is maybe a problem in the detection of the flags for your platform in:
https://github.com/alicevision/AliceVision/blob/develop/src/cmake/OptimizeForArchitecture.cmake

You should try to compile with: `cmake -DTARGET_ARCHITECTURE=core`

**Comment by SteffenDuenner** [comment]
Thanks for your reply. Sadly this doesn't seem to make any change.
In the coming days I will try to compile on my workstation which is a brand new system.

**Comment by fabiencastan** [comment]
Are you sure it's not because of the cmake cache? You should try to remove the build folder and retry.
You can also try: `cmake -DTARGET_ARCHITECTURE=generic` which disables more stuff.

**Comment by fabiencastan** [comment]
Your last problem is that you need to have CUDA >= 7.0 installed.

**Comment by SteffenDuenner** [comment]
I have CUDA 9.1 installed (both Blender and Colmap successfully find it during compilation).
But I don't know how to tell AliceVision where to find it.

**Comment by fabiencastan** [comment]
You are right, it's missing from the [INSTALL.md](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md):
`cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.1`

**Comment by SteffenDuenner** [comment]
I already wondered why it is shown as a BOOLEAN in cmake-gui instead of a path.

**Comment by simogasp** [comment]
if you add it in cmake gui from `Add entry`, select `PATH` as type. Or at command line use `-DCUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda-9.1`

**Comment by SteffenDuenner** [comment]
Thanks again. I'm just giving it another try :)

**Comment by fabiencastan** [comment]
did it work in the end?
