### ISSUE TITLE
Bounding Box / Accuracy filter for sfm point cloud

### ISSUE THREAD

**Issue by pypoulp** [alicevision/AliceVision#405]
Quick feature suggestions : 

- **bbox filter node:** Would be nice to have the ability to remove sfm points outside a defined bbox. Using sharp pictures shooted with short lens can lead to a lot of features detected in the background. It can be pretty useful for sfm step, but it can slow down depth maps / meshing steps, + increase required RAM.
Writting the logic of that filter doesn't seem too complicated, maybe a nice adjustable bbox gizmo in meshroom can be the complicated part.

- **accuracy filter :**  It's a pretty cool feature in Agisoft Photoscan, allowing to select and remove points based of reprojection error, reconstruction uncertainly etc... helping to remove "bad" points before depth maps generation and meshing.

**Comment by natowi** [comment]
Partially implemented in v2020.1
