### ISSUE TITLE
compiled binaries for platforms

### ISSUE THREAD

**Issue by argotan** [alicevision/AliceVision#409]
Good to all, I do not have enough knowledge to make a compilation and more of AliceVision, which has many dependencies. I've tried, but I'm a denial.
I ask those responsible for the project who could provide **binaries compiled with embedded dependencies**, for linux, windows and mac (in my particular case it would be linux64). If you provide these binaries, users would have better access to the tool. And they would have a **greater mass of users** reporting and helping to grow the project.

**Comment by fabiencastan** [comment]
Hi @argotan,
Thanks for the message. We are working on it and we plan to release linux and windows binaries at the end of June.
And we will see later for MacOS...

**Comment by snarkrans** [comment]
Thanks, look forward

**Comment by argotan** [comment]
Thanks

**Comment by MrMinimal** [comment]
Can't wait, this should make the project more accessible for newcomers as well!

**Comment by ChemicalXandco** [comment]
Any news on those binaries? August and still no sign of them...

**Comment by MrMinimal** [comment]
I'd love to try out the project but don't have the time to compile everything. Can't wait to get into this for game development.
