### ISSUE TITLE
[Linux] OSI: undeclared vars

### ISSUE THREAD

**Issue by italic-r** [alicevision/AliceVision#411]
### Problem
CMake config gives error and building OSI fails. Maybe related, but I'm not sure.
`CMake Error: install(EXPORT "aliceVision-targets" ...) includes target "aliceVision_linearProgramming" which requires target "lib_Osi_Msk" that is not in the export set.`  
Building OSI fails with two undeclared tokens: [build.log, CMakeCache.txt, Makefile](https://gist.github.com/italic-r/a045c122ef4a8be4a6357c937f45e393)

### Steps to Reproduce

Built or downloaded all libs I could get (EXR, boost, oiio, opengv, opencv, geogram, eigen, cuda, atlas, ceres, devil, magma, uncertainty, cctag (without cuda))  
CMake config AliceVision with the resulting libs.  
Try to build AliceVision without building deps (building deps makes it download everything).

### Versions

* AliceVision branch/version: develop (4b761726cbd53b71ea752846a3b83c830d554fb9)
* OS: Centos 7.5
* C++ compiler: GCC 6.3.1 (devtoolset-6)

**Comment by simogasp** [comment]
Hi,

yes this may be a bug related to a missing target install when mosek library is available.
You can try to patch it real quick by adding this line

```cmake
INSTALL(TARGETS lib_Osi_Msk DESTINATION lib EXPORT aliceVision-targets)
``` 
after the line 16 of src/dependencies/Osi/src/OsiMsk/CMakeLists.txt
https://github.com/alicevision/osi_clp/blob/38ab28d1c5a53de13c8684cdc272b1deb8cef459/Osi/src/OsiMsk/CMakeLists.txt#L16

We will patch it on the repository

S.

**Comment by italic-r** [comment]
That patch fixes the cmake error. I'm still getting errors referencing undefined vars. I found three total when building with six threads. You can see them all in [#build2.log](https://gist.github.com/italic-r/a045c122ef4a8be4a6357c937f45e393#file-build2-log). I kept retrying the build with six threads until it refused to go any further and these are all I came up with.

I also discovered that geogram misplaces its headers under `include/geogram1/{geogram, geogram_gfx}` and had to move them up one directory. I'm not sure if this is geogram's installer or my fault, but it was an easy fix.

**Comment by italic-r** [comment]
Looks like this error was from using mosek 8 instead of 6. Downgrading fixed the missing declarations (mostly). I've run into other build errors for which I will open another issue.
