### ISSUE TITLE
Crashing on Feature Extraction & DepthMap

### ISSUE THREAD

**Issue by ViperMousey** [alicevision/AliceVision#419]
### Problem

We import the images (Varying datasets from 50, 75 to 4 images. They import into the meshroom UI all good (Occasionally complains about exif) then we hit start, it starts to process the first few images (usually 4) then force crashes with not responding. 

It was built on a Ryzen 1800 Machine (Running a 1080), the AliceVision binaries were then brought onto a few devices, i7 laptops, desktops etc and all work with Meshroom installations however it crashes on our Dual Xeon 2690 v2 machine whether ran with CLI or via the gui. I've recompiled with the _AVX_ and _AVX2) preprocessor definitions stripped out with no luck. 

Heres the crash log on [CLI](https://pastebin.com/raw/Fy5hFMtq) 
### Versions

* AliceVision branch/version: June 7 
* OS: Windows 10
* C++ compiler:  2015

### Edit

So, I've managed to fix this issue, its now failing on the DepthMap but not crashing (Error on node computation?)!

**Comment by lachs0r** [comment]
The build system by default applies CPU-specific optimizations. This will cause undefined behavior and program exits on other machines. You can try applying this patch (using `git am`) and rebuilding: https://0x0.st/sfmr.patch
Note that you might have to delete `CMakeCache.txt` before rebuilding for this to be effective.

**Comment by fabiencastan** [comment]
Yes, I use `-DTARGET_ARCHITECTURE=core` when I need to move the binaries from one machine to another.
@ViperMousey : What is the problem on the DepthMap? Can you provide the log?

**Comment by natowi** [comment]
Closed due to inactivity.
