### ISSUE TITLE
CMake: Should use GNUInstallDirs

### ISSUE THREAD

**Issue by lachs0r** [alicevision/AliceVision#430]
First of all, CMake was a mistake and needs to die in a fire. It is a packager’s second-worst nightmare for many reasons I will not discuss at length here.

Secondly, on GNU and most other platforms that aren’t Windows, the preferred install locations should be taken from CMake’s GNUInstallDirs module. This automatically handles e.g. the `lib64` case. See documentation: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by fabiencastan** [comment]
Yes, good point! We will fix that.

**Comment by simogasp** [comment]
fixed by #440
