### ISSUE TITLE
Check failed: size == existing_size Core dumped

### ISSUE THREAD

**Issue by riematrix** [alicevision/AliceVision#434]
Core dumped at structure from motion step.
BUG

### Problem

[13:57:31.642496][info] AutomaticInitialPairChoice, test I: 2130908429, J: 2146485851, nbCommonTracks: 308
*
[13:57:31.643868][info] AutomaticInitialPairChoice, test I: 2140548709, J: 2146485851, nbCommonTracks: 140
[13:57:31.682983][info] Initial pair is:
  A - view id: 77159844 - filepath: /home/zj/data/szyl_segment/images/DJI_0158.JPG
  B - view id: 793985669 - filepath: /home/zj/data/szyl_segment/images/DJI_0160.JPG
[13:57:31.683931][info] 802 matches in the image pair for the initial pose estimation.
problem_impl.cc:101 Check failed: size == existing_size Tried adding a parameter block with the same double pointer, 0x165d370, twice, but with different block sizes. Original size was 7 but new size is 3
Aborted (core dumped)

### Conditions

Prepare data set with more than 100 images. Problem may not occur if the amount of images is small.
I've tried with amount 3, 29 and 120, only the 120 dataset failed with image size 5472x3648.

### Steps to Reproduce

1. PYTHONPATH=$PWD python meshroom/ui
2. Compute StructureFromMotion

### Versions

* AliceVision branch/version: develop head
* OS: ubuntu14.04
* C++ compiler: gcc

**Comment by riematrix** [comment]
After some code analysis I added two logs in BundleAdjustmentCeres.cpp at about line 283 and line 404.
Seems that there is a mistake of using ceres-solver, just as the error log shows.

283
    double * parameter_block = &map_intrinsics[idIntrinsics][0];
    problem.AddParameterBlock(parameter_block, map_intrinsics[idIntrinsics].size());
    ALICEVISION_LOG_DEBUG("--------------------AddParameterBlock ");
    ALICEVISION_LOG_DEBUG( parameter_block );
    ALICEVISION_LOG_DEBUG(" Size ");
    ALICEVISION_LOG_DEBUG( map_intrinsics[idIntrinsics].size());
    ALICEVISION_LOG_DEBUG( " & " );
    ALICEVISION_LOG_DEBUG(&parameter_block);
    ALICEVISION_LOG_DEBUG("--------------------" );


404
        ceres::CostFunction* costFunction = createCostFunctionFromIntrinsics(sfm_data.intrinsics[view->getIntrinsicId()].get(), observationIt.second.x);

        ALICEVISION_LOG_DEBUG("--------------------start AddResidualBlock int " );
        ALICEVISION_LOG_DEBUG( &map_intrinsics[view->getIntrinsicId()][0] );
        ALICEVISION_LOG_DEBUG( " pose ");
        ALICEVISION_LOG_DEBUG( &map_poses[view->getPoseId()][0] );
        ALICEVISION_LOG_DEBUG( " x " );
        ALICEVISION_LOG_DEBUG( landmarkIt.second.X.data());
        ALICEVISION_LOG_DEBUG("--------------------" );

Here is the out put:

[11:51:58.207050][debug] 518993753, 1782016916 |        +27452.1 |         +1218.0 |           +22.5 |            1214
[11:51:58.207238][info] Initial pair is:
  A - view id: 319589866 - filepath: /home/zj/data/szyl_segment/images/DJI_0181.JPG
  B - view id: 1845795821 - filepath: /home/zj/data/szyl_segment/images/DJI_0183.JPG
[11:51:58.215213][info] 853 matches in the image pair for the initial pose estimation.
[11:52:11.374769][debug] A-Contrario initial pair residual: 52.6677
[11:52:11.647555][debug] BundleAdjustmentCeres: DENSE_SCHUR
[11:52:11.647591][debug] Global BundleAdjustment dense
[11:52:11.647603][debug] BundleAdjustmentCeres: DENSE_SCHUR
[11:52:11.647908][debug] --------------------AddParameterBlock 
[11:52:11.647928][debug] 0x627b950
[11:52:11.647942][debug]  Size 
[11:52:11.647951][debug] 7
[11:52:11.647960][debug]  & 
[11:52:11.647970][debug] 0x7ffe014a7030
[11:52:11.647980][debug] --------------------
[11:52:11.648010][debug] --------------------start AddResidualBlock int 
[11:52:11.648021][debug] 0x627b950
[11:52:11.648032][debug]  pose 
[11:52:11.648040][debug] 0x627bc00
[11:52:11.648049][debug]  x 
[11:52:11.648057][debug] 0x7fe4a4003bc8
[11:52:11.648066][debug] --------------------
problem_impl.cc:101 Check failed: size == existing_size Tried adding a parameter block with the same double pointer, 0x627b950, twice, but with different block sizes. Original size was 7 but new size is 3
The program has unexpectedly finished.
/home/zj/exp/photogrammetry/build-AliceVision-Desktop-Default/Linux-x86_64/aliceVision_incrementalSfM crashed

**Comment by gregoire-dl** [comment]
Hi,

Thank you for your detail analysis.
It's a great start for our investigation.
Is it possible to send us your images and meshroom scene file? 
(you can do it privately using alicevision-team@googlegroups.com)

**Comment by riematrix** [comment]
Hi,
I've already shared the data via email. 

PS
File cameraInit.sfm in MeshroomCache contains "intrinsics": [
        {
            "intrinsicId": "2851613064",
            "width": "5472",
            "height": "3648",
            "type": "pinhole",
            "serialNumber": "c9dbe393a1e134e2cd33ae245d5e1ceb",
            "pxInitialFocalLength": "-1",
            "pxFocalLength": "8.8000000000000007",
            "principalPoint": [
                "2736",
                "1824"
            ],
            "distortionParams": [
                "0",
                "0",
                "0",
                "0"
            ],
            "locked": "false"
        }
    ]

Although distortionParams are zeros, they are add to camera model at Pinhole.hpp line 112

    params.insert(params.end(), _distortionParams.begin(), _distortionParams.end());

so the result vector size of getParams() will return 7, which will not match size 3 defined by the pinhole cost function.

**Comment by fabiencastan** [comment]
Do you manually changed the camera model on the CameraInit to Pinhole in Meshroom?

**Comment by fabiencastan** [comment]
No, you are correct, it is definitely a bug! There is an old PR to fix it that has never been merged.
I just updated it:
https://github.com/alicevision/AliceVision/pull/347
Can you try it?

**Comment by fabiencastan** [comment]
I just tried your dataset and it works for me with the PR.

**Comment by fabiencastan** [comment]
It's now merged in the "develop" branch.

**Comment by riematrix** [comment]
Fixed with [#347](https://github.com/alicevision/AliceVision/pull/347)
