### ISSUE TITLE
CMake Error on ubuntu14.04

### ISSUE THREAD

**Issue by riematrix** [alicevision/AliceVision#456]
Build failed on develop branch.

### Problem

...(about 60 more similar cmake error)

CMake Error at cmake/Helpers.cmake:184 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "aliceVision_utils_split360Images".
Call Stack (most recent call first):
  software/utils/CMakeLists.txt:146 (alicevision_add_software)

make[2]: *** [/home/zj/exp/photogrammetry/AliceVision/src/aliceVision-stamp/aliceVision-configure] Error 1
make[1]: *** [CMakeFiles/aliceVision.dir/all] Error 2
make: *** [all] Error 2
09:57:28: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project aliceVision (kit: Desktop)
When executing step 'Make'

**Expected behavior:**  build success

**Actual behavior:**  build failed

[log](https://gist.github.com/riematrix/d8dd739970d28f69f7b78b0a3c8644d1)

### Steps to Reproduce

1. cmake -DALICEVISION_BUILD_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=$PWD/../install ../AliceVision
2. make -j10

### Versions

* AliceVision branch/version: develop
* OS: ubuntu14.04
* C++ compiler: gcc4.8.4

**Comment by gregoire-dl** [comment]
Hi,

Which version of CMake are you using?
Can you check with #457?
It's a small fix which should correct this problem.

**Comment by riematrix** [comment]
My cmake version is 3.5.1
I update my branch with [#457](https://github.com/alicevision/AliceVision/pull/457) but the error still exists.

**Comment by riematrix** [comment]
@fabiencastan  Ahhh..I see. So will this configuration work for embedded dependency build?
I still can not build with -DALICEVISION_BUILD_DEPENDENCIES=ON

**Comment by fabiencastan** [comment]
You should remove your build folder, git pull, and rebuild from scratch.
I'm convinced that it will work but if you still have issues please re-upload the new log.

**Comment by fabiencastan** [comment]
It does not depend on the fact that you use ALICEVISION_BUILD_DEPENDENCIES or not.

**Comment by riematrix** [comment]
Solved with [#457](https://github.com/alicevision/AliceVision/pull/457) and a fresh build.
