### ISSUE TITLE
Really this difficult to build?

### ISSUE THREAD

**Issue by AFWSI** [alicevision/AliceVision#459]
Is it really this difficult to build? So, I thought I would try to build this and I haven't gotten through the first step yet.

For whatever reason, I can't seem to follow instructions for vcpkg. I can't seem to find anymore information on how you setup/install/use it.

I have done this
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
```
but nothing happens when I run this
```
.\bootstrap-vcpkg.bat
```
or this
```
.\vcpkg integrate install
```

OK, I solved that issue, the .\bootstrap-vcpkg.bat was blank.

Why the heck is it installing 100 things when I do this?
```
vcpkg install ^
          boost-algorithm boost-accumulators boost-atomic boost-container boost-date-time boost-exception boost-filesystem boost-graph boost-log ^
          boost-program-options boost-property-tree boost-ptr-container boost-regex boost-serialization boost-system boost-test boost-thread ^
          openexr ^
          openimageio[libraw] ^
          alembic ^
          geogram ^
          eigen3 ^
          ceres[suitesparse] ^
          cuda ^
          --triplet x64-windows
```

**Comment by fabiencastan** [comment]
> Why the heck is it installing 100 things when I do this?

It install the dependencies of all these libraries.

Yes, it is difficult to build. We make our best to make it stable and multi-platform. It relies on many strong and standard libraries as well as on standard file format to foster interoperability with other softwares.
Unfortunately the c++ language lack of a good multi-platform build and packaging system. So each library use a different system and each developer or distrib or packaging system use different versions of each library which makes things complex for nothing.
So if you want to build it yourself, you need to follow the documentation carefully. You can also have a look at the continuous integration files.

In all case, we will provide binaries for linux and windows.

@AFWSI Do you have another question? If not, you can close the issue.

**Comment by AFWSI** [comment]
@fabiencastan yeah, I finally figured out what was going on. I thought at first it was installing a bunch of random stuff ,but I noticed it was installing what was needed. I finally was able to make the .sln file.

Is this error caused by visual studio or something related to alicevision? I have never seen this error before ,but I did update visual studio yesterday.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133
```
I see somebody has gotten similar error for blender https://blender.stackexchange.com/questions/96895/blender-as-python-module-is-not-able-to-compile-and-not-able-to-get-bin-bpy-pyd so I'm assuming it's a visual studio thing.

I guess the fun begins trying to figure out what's causing it.
