### ISSUE TITLE
[localization] Resectioning for camera RIG externally not calibrated

### ISSUE THREAD

**Issue by simogasp** [alicevision/AliceVision#47]
Resectioning from camera RIG externally not calibrated:
- N unknown extrinsics + M known extrinsics (N+M=3)
- every camera does the localization
- BA with rig constraint to refine everything

This is should be (relatively) easy once poparteu/openMVG#12 is done

**Comment by fabiencastan** [comment]
Status?

**Comment by simogasp** [comment]
I'd wait for poparteu/openMVG#93 (rig localization with generic camera) to be finished to start this one.
