### ISSUE TITLE
AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [alicevision/AliceVision#475]
https://github.com/alicevision/AliceVision/blob/996dda576113810d5bb8214db81c97f6df469c78/src/cmake/MakeBundle.cmake#L10

Please provide the AppImage for download on GitHub Releases. Then we can include it in the AppImageHub central directory of available AppImages. Thanks.

**Comment by ShalokShalom** [comment]
Will this ever happen?
