### ISSUE TITLE
CameraInit fails on drop of images

### ISSUE THREAD

**Issue by pbowmar** [alicevision/AliceVision#479]
### Problem

When I drop some JPG images into the Images pane, nothing happens in the GUI. In the shell is the following however:

```
/bin/sh: /opt/software/meshroom/2018.1.0/Meshroom-2018.1.0/lib/libreadline.so.6: no version information available (required by /bin/sh)                                                                                                                                         
/bin/sh: relocation error: /bin/sh: symbol rl_filename_stat_hook, version READLINE_6.3 not defined in file libreadline.so.6 with link time reference                                                                                                                            
ERROR:root:Error while building intrinsics : Traceback (most recent call last):                                                                                                                                                                                                 
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 384, in buildIntrinsics
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 129, in buildIntrinsics
RuntimeError: CameraInit failed with error code 127. Command was: "aliceVision_cameraInit  --sensorDatabase "/opt/software/meshroom/2018.1.0/Meshroom-2018.1.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "/tmp/tmp1d934tpk/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmp1d934tpk/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"
```

### Versions

* AliceVision branch/version: 2018.1.0 (prebuilt)
* OS: Linux (OpenSuse 42.3, Linux XXX 4.4.140-62-default #1 SMP Tue Jul 17 12:14:34 UTC 2018 (951943d) x86_64 x86_64 x86_64 GNU/Linux)

**Comment by Arenaward** [comment]
i've had the exact same error as you, i tried another picture with a lower resolution and it worked all fine, so i downsized all the images from almost 16 megapixels to just 5 megapixels and it worked (5 is the minimum requirement for an image in meshroom)

**Comment by fabiencastan** [comment]
@Arenaward : What do you mean by "5 is the minimum requirement for an image in meshroom"?
The software is not supposed to have contraints on the image resolution.

@Arenaward @pbowmar : Do you have sample images that you can share with me to try to reproduce your problems? With too large and/or too small images?
You can send datasets via https://fromsmash.com to "alicevision-team@googlegroups.com".

**Comment by Arenaward** [comment]
@fabiencastan oh, well i was just watching a video on youtube for CG Geek and he said 5 megapixels is the minimum requirements for the software (if thats not correct then im sorry but thats what i thought, after all i downloaded the whole software because of him so i know that much) and i can send you the image i used to get the error and the exact same one that i resized and it worked. bear in mind i took the images with a galaxy note 5.

**Comment by fabiencastan** [comment]
There is no minimum resolution contraint. The maximal resolution will be limited by the RAM available to extract features in images but that's only for very very large images.

So yes, I'm interested to get the images to be able to reproduce it and hopefully fix it.

**Comment by Arenaward** [comment]
@fabiencastan the images i used are sent :) (they were a total of 67 images like the one i sent) hopefully that would be of any help :) thanks for your quick response!

**Comment by pbowmar** [comment]
This is still the same in 2019.1.0.

Note that instead of drag and drop, I edited the .mg file directly to add the images. However when processing I still get:

/bin/sh: /opt/software/meshroom/2019.1.0/lib/libreadline.so.6: no version information available (required by /bin/sh)
/bin/sh: relocation error: /bin/sh: symbol rl_filename_stat_hook, version READLINE_6.3 not defined in file libreadline.so.6 with link time reference
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 382, in buildIntrinsics
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 127. Command was: "aliceVision_cameraInit  --sensorDatabase "/opt/software/meshroom/2019.1.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/tmp/tmpwm3sd7ns/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmpwm3sd7ns/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
