### ISSUE TITLE
DepthMap Performance

### ISSUE THREAD

**Issue by ChemicalXandco** [alicevision/AliceVision#481]
In https://scanbox.xyz/blog/alicevision-opensource-photogrammetry/ review, there is a chart comparing the computation speed to Reality Capture and Photoscan:

![capture101](https://user-images.githubusercontent.com/32775248/43960262-6b6a5b08-9ca9-11e8-80ba-39aee7c3603b.PNG)

There is a big difference between Alicevision and the other 2.

When I look at the GPU + CPU usage on task manager it is all over the place: GPU is mostly on ~25% and peaks to ~75%. The CPU is much the same but mostly on ~50%

![capture102](https://user-images.githubusercontent.com/32775248/43962653-2daa312e-9cb0-11e8-9a03-cbc41e98759f.PNG)

![capture103](https://user-images.githubusercontent.com/32775248/43962669-35383dfa-9cb0-11e8-8dbc-d1145505f814.PNG)

It needs optimising so that it uses as much available power as possible. I reckon it would get at least a 25% performance boost if it just uses all of the available processing _**power**_. 

Platform: Windows x64
Hardware: i7 4790 
                 GTX 1050 Ti
Version: 2.0.0

**Comment by snarkrans** [comment]
I got a similar result. Meshroom have good quality, but very slow. Agisoft only on cpu works faster.

**Comment by snarkrans** [comment]
[https://i.imgur.com/4hIQ5k5.png](url)

**Comment by fabiencastan** [comment]
Yes, we are aware that the depth map computation does not make an optimal usage of the GPU. As [you can see](https://github.com/alicevision/AliceVision/pull/478), we are working on it but that's not trivial to change.
If you have good CUDA knowledge, help on this aspect would be much appreciated.

**Comment by vilemduha** [comment]
is there a way for usual users to test this patch? Or would I have to build Alicevision from scratch?

**Comment by fabiencastan** [comment]
Yes, the only way is to build it.
I recommend you to wait at least for a merge in the "develop" branch before spending time on testing it, except if you are interested to contribute to it.

**Comment by nickpolet** [comment]
Would be great to hear if there has been any progress made on this front? I cannot believe how great the framework is, especially being able to run all the steps individually from code. Really flexible. The only issue is the speed. But I have patience, just wondering if there has been movement here.

**Comment by ChemicalXandco** [comment]
2019.1.0 appears to be almost twice as fast on depthmap then it was in 2018.1.0: 36 mins on 2018.1.0 and 20 mins on 2019.1.0 using the monstree dataset

**Comment by zhangalex** [comment]
Is there any update here?

**Comment by Entretoize** [comment]
Today the problem is still there, depthmap still use only 10% of my RTX3080 and 60% of my Ryzen 5, and is very, very long !

**Comment by kreendurron** [comment]
Seems to still be an issue? 
![image](https://github.com/alicevision/AliceVision/assets/5321173/253ae00f-c1be-470c-87e6-9ca879f76f10)

**Comment by natowi** [comment]
Yes, the GPU utilization still has room for improvements.

However, the overall improvements over the last releases in the DepthMap node are considerable:
![236703694-6f63b24a-69db-42ea-9892-cc97d8a9afb6](https://github.com/alicevision/AliceVision/assets/8138537/f5400d81-09a2-47a0-b3f0-650759d568da)
