### ISSUE TITLE
problem with trailing spaces when reading EXIF

### ISSUE THREAD

**Issue by simogasp** [alicevision/AliceVision#485]
from https://github.com/alicevision/meshroom/issues/179#issuecomment-413016629

Apparently with some versions some trailing whitespace are left on the right of the model name thus preventing the search on the database.
Could be a OIIO bug?

**Comment by simogasp** [comment]
also, this commit has completely changed the comparison algorithm making it much less flexible: before it was able to match `Canon EOS 1200D` with `Canon EOS Rebel T5 / 1200D` (which is a bit of a stretch but effective).
https://github.com/alicevision/AliceVision/commit/99e0bef78a4dd8125c41dde6d551ce58502469e7
@fabiencastan @gregoire-dl

**Comment by canonex** [comment]
I confirm that I had to add:
alps                           ;Glory3                         ;3.75
to make the camera of my phone work.
