### ISSUE TITLE
Windows Building failed issue 

### ISSUE THREAD

**Issue by fbi369123456** [alicevision/AliceVision#488]
Hi 
I am building AliceVision on Windows, and I start with vcpkg and download each dependence package step by step. Finally, It worked successfully and generate a aliceVision.sln.

I compile this project and some error occurred. 
Here is my environment 
Windows 10
VS2017 With VS2015 build tool
Cuda 9.0

![image](https://user-images.githubusercontent.com/24413895/44640804-6ec12200-a9f6-11e8-892f-3bfc9e77a676.png)

It seems cuda reference can't be defined, but my cuda installed successfully.
Here is my problem.

Thanks

**Comment by RDelet** [comment]
I have some error too with same configuration but with PLYReader and OpenImageIO simd file.

![image](https://user-images.githubusercontent.com/7300189/45028623-07cee900-b046-11e8-888a-50945902d69f.png)
