### ISSUE TITLE
OnePlus One missing in cameraSensors.db

### ISSUE THREAD

**Issue by hcw70** [alicevision/AliceVision#491]
Hello all.

Found out about your great project due to a CG geek video recently, and it works quite well and easy.

However i was trying to use it with my OnePlus One mobile camera which yields a message stating that this camera is not in cameraSensors.db.

How can that be changed? What values need to be put in?

Kind regards

**Comment by hcw70** [comment]
Ok, i added:
`oneplus;A0001;4.69
`

Seems to work!

**Comment by simogasp** [comment]
if it works you can PR the update. Thanks!

**Comment by FLuAnotherMe** [comment]
Hello,
I also added the following lines
```
Canon;Canon EOS 2000D;22.3
Canon;Canon EOS 1200D;22.3
```
