### ISSUE TITLE
[Windows] Build failed

### ISSUE THREAD

**Issue by RDelet** [alicevision/AliceVision#492]
Hi everyone,

I try to build AliceVision on Windows 10.
I get all package with vcpkg except cuda, I download it without vcpkg

In CMakeOutput I don't have Avertissement or Error. I'm not very familiar with CMake and I don't understand problem here
[CMakeOutput.log](https://github.com/alicevision/AliceVision/files/2332824/CMakeOutput.log)

### Steps to Reproduce

1. Clone VCPKG
2. Install all dependencies
3. Download cuda toolkit and install it
4. Clone AliceVision
5. Make sur it's last version --> git pull
6. Launch cmake

(All command are getted in AliceVision install.md file)

### Versions

* AliceVision branch/version: Latest master
* OS: Windows 10
* C++ compiler: VisualStudio 2015

**Comment by fabiencastan** [comment]
Could you also send the `CMakeError.log`?

**Comment by RDelet** [comment]
I try to build with CMake UI and I have this log (**CMake 3.12.1**)
It's possible vcpkg install wrong version of libraries ?

> Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.16299.
> The C compiler identification is MSVC 19.0.24215.1
> The CXX compiler identification is MSVC 19.0.24215.1
> Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
> Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
> Detecting C compiler ABI info
> Detecting C compiler ABI info - done
> Detecting C compile features
> Detecting C compile features - done
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> Force CMAKE_INSTALL_DO_STRIP in Release
> ----------------------------------------
> ALICEVISION_BUILD_DEPENDENCIES: OFF
> ALICEVISION_BUILD_TESTS: OFF
> AV_BUILD_CUDA: OFF
> AV_BUILD_ZLIB: ON
> AV_BUILD_TIFF: ON
> AV_BUILD_JPEG: ON
> AV_BUILD_PNG: ON
> AV_BUILD_LIBRAW: ON
> AV_BUILD_POPSIFT: ON
> CMAKE_BUILD_TYPE: Release
> DEPS_CMAKE_BUILD_TYPE: Release
> CMAKE_INSTALL_LIBDIR: lib
> CMAKE_INSTALL_PREFIX: C:/Program Files (x86)/aliceVision
> CMAKE_INSTALL_RPATH: 
> CMAKE_INSTALL_DO_STRIP: TRUE
> ----------------------------------------
> CMake version: 3.12
> ** ALICEVISION_BUILD_DOC: 'AUTO'
> ** ALICEVISION_USE_OPENMP: 'ON'
> ** ALICEVISION_USE_CCTAG: 'AUTO'
> ** ALICEVISION_USE_POPSIFT: 'AUTO'
> ** ALICEVISION_USE_OPENGV: 'AUTO'
> ** ALICEVISION_USE_ALEMBIC: 'AUTO'
> ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
> ** ALICEVISION_USE_CUDA: 'ON'
> ** ALICEVISION_USE_OPENCV: 'OFF'
> Detected Host CPU: skylake-avx512
> Checking for C++11 compiler
> Checking for C++11 compiler - available
> OpenMP found.
> CMake Error at src/CMakeLists.txt:245 (message):
>   Failed to find Boost.
> 
> 
> CMake Error at src/CMakeLists.txt:246 (message):
>   Boost version: 1.64.0
> 
>   Boost include path: C:/Program Files/USD/include/boost-1_64
> 
>   Could not find the following Boost libraries:
> 
>           boost_container
>           boost_graph
>           boost_log
>           boost_log_setup
>           boost_serialization
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> 
> 
> CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
>   ILMBASE_INCLUDE_DIR: C:/Program Files/USD/include;C:/Program
>   Files/USD/include/OpenEXR
> Call Stack (most recent call first):
>   src/CMakeLists.txt:269 (find_package)
> 
> 
> OpenEXR found. (Version 2.2.0)
> CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
>   ILMBASE_INCLUDE_DIR: C:/Program Files/USD/include;C:/Program
>   Files/USD/include/OpenEXR
> Call Stack (most recent call first):
>   src/cmake/FindOpenImageIO.cmake:1 (find_package)
>   src/CMakeLists.txt:279 (find_package)
> 
> 
> OpenImageIO found.
> -- Did not find MOSEK header
> -- Did not find MOSEK library
> Could not find mosek library on this machine.
> CMake Error at src/CMakeLists.txt:318 (find_package):
>   By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Eigen3", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Eigen3" (requested
>   version 3.3) with any of the following names:
> 
>     Eigen3Config.cmake
>     eigen3-config.cmake
> 
>   Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
>   "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> Configuring incomplete, errors occurred!
> See also "D:/Work/Photogrammetrie/Soft/AliceVision/build/CMakeFiles/CMakeOutput.log".

**Comment by RDelet** [comment]
I solve my problem with this line

`vcpkg install alembic boost ceres eigen3 flann geogram opencv openexr opengv openimageio openmesh zlib --triplet x64-windows`

**Comment by RDelet** [comment]
Hi everyone,

I have other problem. When I build solution I have this error in VisualStudio

> Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
> Erreur	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\Work\Photogrammetrie\Soft\AliceVision\src\aliceVision\depthMap\DepthSimMap.cpp)	aliceVision_depthMap	D:\Work\Photogrammetrie\Soft\vcpkg\installed\x64-windows\include\OpenImageIO\simd.h	305	

When I doubleClick on this error VisualStudio jump to this File
> ".........../OpenImageIO/simd.h"
on this line 
> template<> struct simd_raw_t<int,16> { typedef __m512i type; };

Anyone know this problem ?
