### ISSUE TITLE
[Build error] Missing type specifier

### ISSUE THREAD

**Issue by RDelet** [alicevision/AliceVision#501]
### Problem

When I build solution with VisualStudio I have this error on simd.h file for aliveVision_image project. This file is in OpenImageIO lib.
I try with V140 (VisualStudio 2015 compiler) and V141 (VisualStudio 2017 compiler). With v141 I have a same problem with PlyReader.hh file

Problem is always on this line
```
#if OIIO_SIMD_AVX >= 512
template<> struct simd_raw_t<int,16> { typedef __m512i type; };
template<> struct simd_raw_t<float,16> { typedef __m512 type; };
template<> struct simd_bool_t<16> { typedef __mmask16 type; };
#else
```

![image](https://user-images.githubusercontent.com/7300189/45145479-07a72880-b1c1-11e8-958f-e22413bea59f.png)

### Versions

* **AliceVision branch/version:** Last master
* **OS:** Windows 10
* **C++ compiler:** VisualSutdion 2015 (v140)

**Comment by RDelet** [comment]
I tryed this morning to rebuild AliceVision with git update.
I have this error when I build OpenMesh or MeshSDFilter. I don't try other project in AliceVision.sln
`vertexProperties_': undeclared identifier	OpenMesh	D:\Work\Photogrammetrie\Soft\AliceVision\src\dependencies\MeshSDFilter\external\OpenMesh\Core\IO\reader\PLYReader.cc	332	`

**Comment by fabiencastan** [comment]
Just to be sure that you are in a correct state:
```
git pull
git submodule update -i
```
And retry to build.

**Comment by RDelet** [comment]
I have the same mistake.

In PLYReader.hh vertexProperties is private. It's normal ?

**Comment by RDelet** [comment]
Nobody has a solution to solve this problem ?
