### ISSUE TITLE
*** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by pfc** [alicevision/AliceVision#513]
### Problem

Meshing fails and I see errors reporting stack smashing in the terminal.  The GUI gives no indication as to what is going on other than the red bar on meshing.

[1/1] Meshing
 - commandLine: aliceVision_meshing  --ini "/home/user/Documents/3d/MeshroomCache/PrepareDenseScene/5193c0ba3d47f17dd070f46278496875d04b1eff/mvs.ini" --depthMapFolder "/home/user/Documents/3d/MeshroomCache/DepthMap/238102a3f58f3240c60fe4c14ff5b99ad39bf476" --depthMapFilterFolder "/home/user/Documents/3d/MeshroomCache/DepthMapFilter/e2d5504956d70b4bc8b17a6f08162d3b0683501a" --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --verboseLevel info --output "/home/user/Documents/3d/MeshroomCache/Meshing/fb4abc81c8a90d8bda55475ce9e139055ba77b5f/mesh.obj" 
 - logFile: /home/user/Documents/3d/MeshroomCache/Meshing/fb4abc81c8a90d8bda55475ce9e139055ba77b5f/log
 - elapsed time: 0:00:00.822353
ERROR:root:Error on node computation: Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapFilterFolder = "/home/user/Documents/3d/MeshroomCache/DepthMapFilter/e2d5504956d70b4bc8b17a6f08162d3b0683501a"
 * depthMapFolder = "/home/user/Documents/3d/MeshroomCache/DepthMap/238102a3f58f3240c60fe4c14ff5b99ad39bf476"
 * ini = "/home/user/Documents/3d/MeshroomCache/PrepareDenseScene/5193c0ba3d47f17dd070f46278496875d04b1eff/mvs.ini"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/home/user/Documents/3d/MeshroomCache/Meshing/fb4abc81c8a90d8bda55475ce9e139055ba77b5f/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * verboseLevel = "info"
 * voteMarginFactor = 4

[13:45:25.166655][info] Found 1 image dimension(s): 
[13:45:25.166700][info]  - [4656x2218]
[13:45:25.167842][info] Overall maximum dimension: [2328x1109]
[13:45:25.167872][warning] repartitionMode: 1
[13:45:25.167884][warning] partitioningMode: 1
[13:45:25.167892][info] Meshing mode: multi-resolution, partitioning: single block.
[13:45:25.168120][info] Estimate space.
*** stack smashing detected ***: <unknown> terminated

ERROR:root:Error during Graph execution Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapFilterFolder = "/home/user/Documents/3d/MeshroomCache/DepthMapFilter/e2d5504956d70b4bc8b17a6f08162d3b0683501a"
 * depthMapFolder = "/home/user/Documents/3d/MeshroomCache/DepthMap/238102a3f58f3240c60fe4c14ff5b99ad39bf476"
 * ini = "/home/user/Documents/3d/MeshroomCache/PrepareDenseScene/5193c0ba3d47f17dd070f46278496875d04b1eff/mvs.ini"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/home/user/Documents/3d/MeshroomCache/Meshing/fb4abc81c8a90d8bda55475ce9e139055ba77b5f/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * verboseLevel = "info"
 * voteMarginFactor = 4

[13:45:25.166655][info] Found 1 image dimension(s): 
[13:45:25.166700][info]  - [4656x2218]
[13:45:25.167842][info] Overall maximum dimension: [2328x1109]
[13:45:25.167872][warning] repartitionMode: 1
[13:45:25.167884][warning] partitioningMode: 1
[13:45:25.167892][info] Meshing mode: multi-resolution, partitioning: single block.
[13:45:25.168120][info] Estimate space.
*** stack smashing detected ***: <unknown> terminated

**Expected behavior:**  

**Actual behavior:**  

### Steps to Reproduce

1. add images
2. click start

### Versions

* AliceVision branch/version: 2.0.0-2
* OS: Arch Linux
* C++ compiler:

**Comment by mysticfall** [comment]
Have you checked the output of `journalctl -f`? I'm also on an Arch based distro (Manjaro) and experiencing a similar problem.

I got the following message from systemd when it happens:
```
Process 19682 (aliceVision_mes) of user 1000 dumped core.

Stack trace of thread 19682:
#0  0x00007f15da59bd7f raise (libc.so.6)
#1  0x00007f15da586672 abort (libc.so.6)
#2  0x00007f15da5de878 __libc_message (libc.so.6)
#3  0x00007f15da671415 __GI___fortify_fail_abort (libc.so.6)
#4  0x00007f15da6713c6 __stack_chk_fail (libc.so.6)
#5  0x00007f15d9fc70f7 _ZN11aliceVision4tql2EPdS0_S0_S0_S0_ (libaliceVision_mvsData.so.2)
#6  0x00007f15d9fc71ab _ZN11aliceVision6Stat3d19eigen_decompositionEPA3_dPdS3_S3_S3_ (libaliceVision_mvsData.so.2)
#7  0x00007f15daf5b75d _ZN11aliceVision7fuseCut5Fuser11divideSpaceEPNS_7Point3dERf (libaliceVision_fuseCut.so.2)
#8  0x000055adeeeac95b n/a (aliceVision_meshing-1.0)
#9  0x00007f15da588223 __libc_start_main (libc.so.6)
#10 0x000055adeeeaf27e n/a (aliceVision_meshing-1.0)

Stack trace of thread 19687:
#0  0x00007f15d958713e futex_wait (libgomp.so.1)
#1  0x00007f15d9584a98 gomp_simple_barrier_wait (libgomp.so.1)
#2  0x00007f15da72fa9d start_thread (libpthread.so.0)
#3  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19684:
#0  0x00007f15da738436 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f15da738538 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007f15d6a03714 _ZN13IlmThread_2_39Semaphore4waitEv (libIlmThread-2_3.so.24)
#3  0x00007f15d6a02a76 n/a (libIlmThread-2_3.so.24)
#4  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#5  0x00007f15da72fa9d start_thread (libpthread.so.0)
#6  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19683:
#0  0x00007f15da738436 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f15da738538 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007f15d6a03714 _ZN13IlmThread_2_39Semaphore4waitEv (libIlmThread-2_3.so.24)
#3  0x00007f15d6a02a76 n/a (libIlmThread-2_3.so.24)
#4  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#5  0x00007f15da72fa9d start_thread (libpthread.so.0)
#6  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19688:
#0  0x00007f15d958713e futex_wait (libgomp.so.1)
#1  0x00007f15d9584a98 gomp_simple_barrier_wait (libgomp.so.1)
#2  0x00007f15da72fa9d start_thread (libpthread.so.0)
#3  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19686:
#0  0x00007f15da738436 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f15da738538 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007f15d6a03714 _ZN13IlmThread_2_39Semaphore4waitEv (libIlmThread-2_3.so.24)
#3  0x00007f15d6a02a76 n/a (libIlmThread-2_3.so.24)
#4  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#5  0x00007f15da72fa9d start_thread (libpthread.so.0)
#6  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19691:
#0  0x00007f15da735afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f15da99fcd1 __gthread_cond_wait (libstdc++.so.6)
#2  0x00007f15d9e41c34 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN16OpenImageIO_v1_811thread_pool4Impl10set_threadEiEUlvE_EEEEE6_M_runEv (libOpenImageIO.so.1.8)
#3  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#4  0x00007f15da72fa9d start_thread (libpthread.so.0)
#5  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19689:
#0  0x00007f15d958713e futex_wait (libgomp.so.1)
#1  0x00007f15d9584a98 gomp_simple_barrier_wait (libgomp.so.1)
#2  0x00007f15da72fa9d start_thread (libpthread.so.0)
#3  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19690:
#0  0x00007f15da735afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f15da99fcd1 __gthread_cond_wait (libstdc++.so.6)
#2  0x00007f15d9e41c34 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN16OpenImageIO_v1_811thread_pool4Impl10set_threadEiEUlvE_EEEEE6_M_runEv (libOpenImageIO.so.1.8)
#3  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#4  0x00007f15da72fa9d start_thread (libpthread.so.0)
#5  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19685:
#0  0x00007f15da738436 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f15da738538 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007f15d6a03714 _ZN13IlmThread_2_39Semaphore4waitEv (libIlmThread-2_3.so.24)
#3  0x00007f15d6a02a76 n/a (libIlmThread-2_3.so.24)
#4  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#5  0x00007f15da72fa9d start_thread (libpthread.so.0)
#6  0x00007f15da65fb23 __clone (libc.so.6)

Stack trace of thread 19692:
#0  0x00007f15da735afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f15da99fcd1 __gthread_cond_wait (libstdc++.so.6)
#2  0x00007f15d9e41c34 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN16OpenImageIO_v1_811thread_pool4Impl10set_threadEiEUlvE_EEEEE6_M_runEv (libOpenImageIO.so.1.8)
#3  0x00007f15da9a6063 execute_native_thread_routine (libstdc++.so.6)
#4  0x00007f15da72fa9d start_thread (libpthread.so.0)
#5  0x00007f15da65fb23 __clone (libc.so.6)
```
