### ISSUE TITLE
what should I do after generating .sln --------windows10+vs2017+vcpkg

### ISSUE THREAD

**Issue by ysq201466** [alicevision/AliceVision#549]
D:\AliceVision\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\vcpkg-master\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T v140,host=x64
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.16299.
-- The C compiler identification is MSVC 19.0.24234.1
-- The CXX compiler identification is MSVC 19.0.24234.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Force CMAKE_INSTALL_DO_STRIP in Release
-- ----------------------------------------
-- ALICEVISION_BUILD_DEPENDENCIES: OFF
-- ALICEVISION_BUILD_TESTS: OFF
-- AV_BUILD_CUDA: OFF
-- AV_BUILD_ZLIB: ON
-- AV_BUILD_TIFF: ON
-- AV_BUILD_JPEG: ON
-- AV_BUILD_PNG: ON
-- AV_BUILD_LIBRAW: ON
-- AV_BUILD_POPSIFT: ON
-- AV_BUILD_OPENGV: ON
-- AV_BUILD_LAPACK: ON
-- AV_BUILD_SUITESPARSE: ON
-- CMAKE_BUILD_TYPE: Release
-- DEPS_CMAKE_BUILD_TYPE: Release
-- CMAKE_INSTALL_LIBDIR: lib
-- CMAKE_INSTALL_PREFIX: C:/Program Files (x86)/aliceVision
-- CMAKE_INSTALL_RPATH:
-- CMAKE_INSTALL_DO_STRIP: TRUE
-- ----------------------------------------
CMake version: 3.13
-- ** ALICEVISION_BUILD_DOC: 'AUTO'
-- ** ALICEVISION_USE_OPENMP: 'ON'
-- ** ALICEVISION_USE_CCTAG: 'AUTO'
-- ** ALICEVISION_USE_POPSIFT: 'AUTO'
-- ** ALICEVISION_USE_OPENGV: 'AUTO'
-- ** ALICEVISION_USE_ALEMBIC: 'AUTO'
-- ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
-- ** ALICEVISION_USE_CUDA: 'ON'
-- ** ALICEVISION_USE_OPENCV: 'OFF'
-- target changed from "" to "auto"
-- Detected Host CPU: kaby-lake
-- Performing Test check_c_compiler_flag__arch_AVX2
-- Performing Test check_c_compiler_flag__arch_AVX2 - Success
-- Performing Test check_cxx_compiler_flag__arch_AVX2
-- Performing Test check_cxx_compiler_flag__arch_AVX2 - Success
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- OpenMP found.
-- Boost 1_68 found.
-- Found ZLIB: optimized;E:/vcpkg/vcpkg-master/installed/x64-windows/lib/zlib.lib;debug;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Found Threads: TRUE
-- Found OpenEXR: E:/vcpkg/vcpkg-master/installed/x64-windows/include (found version "2.2.0")
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR:
  E:/vcpkg/vcpkg-master/installed/x64-windows/include;E:/vcpkg/vcpkg-master/installed/x64-windows/include/OpenEXR
Call Stack (most recent call first):
  E:/vcpkg/vcpkg-master/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  src/CMakeLists.txt:269 (find_package)

-- OpenEXR found. (Version 2.2.0)
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR:
  E:/vcpkg/vcpkg-master/installed/x64-windows/include;E:/vcpkg/vcpkg-master/installed/x64-windows/include/OpenEXR
Call Stack (most recent call first):
  E:/vcpkg/vcpkg-master/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  src/cmake/FindOpenImageIO.cmake:1 (find_package)
  E:/vcpkg/vcpkg-master/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  src/CMakeLists.txt:279 (find_package)

-- Found OpenImageIO: E:/vcpkg/vcpkg-master/installed/x64-windows/include;E:/vcpkg/vcpkg-master/installed/x64-windows/include (Required is at least version "1.8")
-- OpenImageIO found.
-- Did not find MOSEK header
-- Did not find MOSEK library
-- Could not find mosek library on this machine.
-- Trying to find package Ceres for aliceVision:
-- By default, Ceres required SuiteSparse to ensure best performances. if you explicitly need to build without it, you can use the option: -DALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE=OFF
-- Found installed version of Eigen: E:/vcpkg/vcpkg-master/installed/x64-windows/share/eigen3
-- Found required Ceres dependency: Eigen version 3.3.5 in E:/vcpkg/vcpkg-master/installed/x64-windows/include/eigen3
-- Found required Ceres dependency: glog
-- Ceres version 1.14.0 detected here: E:/vcpkg/vcpkg-master/installed/x64-windows was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
-- Found Ceres version: 1.14.0 installed in: E:/vcpkg/vcpkg-master/installed/x64-windows with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, SchurSpecializations, C++11, OpenMP, Multithreading]
-- Ceres include dirs E:/vcpkg/vcpkg-master/installed/x64-windows/include;E:/vcpkg/vcpkg-master/installed/x64-windows/include/eigen3;E:/vcpkg/vcpkg-master/installed/x64-windows/include
-- Ceres libraries ceres
-- Found BLAS: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/openblas.lib
-- Found AMD headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found AMD library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libamd.lib
-- Found CAMD headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found CAMD library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcamd.lib
-- Found COLAMD headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found COLAMD library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcolamd.lib
-- Found CCOLAMD headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found CCOLAMD library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libccolamd.lib
-- Found CHOLMOD headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found CHOLMOD library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcholmod.lib
-- Found SUITESPARSEQR headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found SUITESPARSEQR library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libspqr.lib
-- Did not find TBB library (optional SuiteSparse dependency)
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found SUITESPARSE_CONFIG headers in: E:/vcpkg/vcpkg-master/installed/x64-windows/include/suitesparse
-- Found SUITESPARSE_CONFIG library: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/suitesparseconfig.lib
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "5.1.2")
-- SUITESPARSE_LIBRARIES: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libspqr.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcholmod.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libccolamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcolamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/lapack.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/openblas.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/openblas.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/suitesparseconfig.lib
-- CERES_LIBRARIES: ceres;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libspqr.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcholmod.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libccolamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libcolamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/libamd.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/lapack.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/openblas.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/openblas.lib;E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/suitesparseconfig.lib
-- CERES_INCLUDE_DIRS: E:/vcpkg/vcpkg-master/installed/x64-windows/include;E:/vcpkg/vcpkg-master/installed/x64-windows/include/eigen3;E:/vcpkg/vcpkg-master/installed/x64-windows/include
-- Flann 1.8.4 found (include: D:/AliceVision/src/dependencies/flann/src/cpp/flann)
-- CoinUtils 2.9.3 found (include: D:/AliceVision/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.15.11 found (include: D:/AliceVision/src/dependencies/osi_clp/Clp/src)
-- Osi 0.106.10 found (include: D:/AliceVision/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon  found (include: D:/AliceVision/src/dependencies/lemon/lemon)
-- Alembic version 1.7.9 found.
-- Could NOT find PopSift (missing: PopSift_DIR)
-- Looking for OpenGV.
-- OpenGV headers not found!
-- Could NOT find OpenGV (missing: OPENGV_LIBRARY OPENGV_INCLUDE_DIR)
-- Looking for UncertaintyTE.
-- UncertaintyTE headers not found!
-- UncertaintyTE library include not found
-- UncertaintyTE library not found
-- Could NOT find UncertaintyTE (missing: UNCERTAINTYTE_LIBRARY UNCERTAINTYTE_INCLUDE_DIR)
-- Found Geogram: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/geogram.lib
-- Geogram: E:/vcpkg/vcpkg-master/installed/x64-windows/debug/lib/geogram.lib, E:/vcpkg/vcpkg-master/installed/x64-windows/include
MSVC compiler found.
OpenMP found. OpenMP activated in release.
-- BUILD_SHARED_LIBS ON
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.0")
-- CUDA found.
Build Mode: Release
-- CUDA Version is 9.0
-- Found Sphinx: C:/Users/ysq/Anaconda3/Scripts/sphinx-build.exe
-- Sphinx found.
generatedDir: D:/AliceVision/build/src/generated

** AliceVision version: 2.0.0
** Build Shared libs: ON
** Build SfM part: ON
** Build MVS part: ON
** Build AliceVision tests: OFF
** Build AliceVision documentation: 1
** Build AliceVision samples programs: OFF
** Build AliceVision+OpenCV samples programs: 0
** Build UncertaintyTE: 0
** Build MeshSDFilter: 1
** Build Alembic exporter: 1
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: 1
** Use CUDA: 1
** Use OpenCV SIFT features: 0
** Use CCTAG markers: 0
** Use OpenGV for rig localization: 0

-- EIGEN: 3.3.5
-- CERES: 1.14.0
-- FLANN: 1.8.4 (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON:  (internal)

-- Found PythonInterp: C:/Users/ysq/Anaconda3/python.exe (found version "3.7")
-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/AliceVision/build

**Comment by yann-lty** [comment]
```
-- Configuring done
-- Generating done
-- Build files have been written to: D:/AliceVision/build
```
Everything worked (CMake warnings can be ignored here), you should have a Visual Studio solution named `aliceVision.sln` in D:/AliceVision/build.

**Comment by ysq201466** [comment]
-- Did not find MOSEK header
-- Did not find MOSEK library
-- Could not find mosek library on this machine.

-- Did not find TBB library (optional SuiteSparse dependency)
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.

-- Did not find METIS library (optional SuiteSparse dependency)

-- Could NOT find PopSift (missing: PopSift_DIR)

-- UncertaintyTE headers not found!
-- UncertaintyTE library include not found
-- UncertaintyTE library not found
-- Could NOT find UncertaintyTE (missing: UNCERTAINTYTE_LIBRARY UNCERTAINTYTE_INCLUDE_DIR)

-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)

.sln was generated,but i opened it in vs2017 community and built,and run local windows debugger ,finally,it show "unable start program"D:\AliceVision\build\x64\Debug\ALL_BUILD"",拒绝访问

**Comment by ysq201466** [comment]
> ```
> -- Configuring done
> -- Generating done
> -- Build files have been written to: D:/AliceVision/build
> ```
> Everything worked (CMake warnings can be ignored here), you should have a Visual Studio solution named `aliceVision.sln` in D:/AliceVision/build.

**Comment by ysq201466** [comment]
> ```
> -- Configuring done
> -- Generating done
> -- Build files have been written to: D:/AliceVision/build
> ```
> Everything worked (CMake warnings can be ignored here), you should have a Visual Studio solution named `aliceVision.sln` in D:/AliceVision/build.

yes,I got it,then what's steps i should do one by one

**Comment by zvrba** [comment]
In file explorer, double-click on the SLN file and Visual studio will open. Then select "Build solution" from the "Build" menu and wait. There's an "Output" tab at the bottom where you can watch build progress and where the exe files have been placed.

**Comment by ysq201466** [comment]
> In file explorer, double-click on the SLN file and Visual studio will open. Then select "Build solution" from the "Build" menu and wait. There's an "Output" tab at the bottom where you can watch build progress and where the exe files have been placed.
> 
> You can also build from the command-line with cmake as in `cmake --build` but I don't remember the other necessary options.

Is all the exe same as "AliceVision-2.0.0-win64.zip"from Alicevision release?and then if I want to run exe built by my Alicevision.sln in windows command-line,what i have to install or what i have to prepare.
thanks!!!!!!!!.
