### ISSUE TITLE
How to use Rig Camera?

### ISSUE THREAD

**Issue by eroswade** [alicevision/AliceVision#559]
I've used meshroom. and reading the code with questions for days. 
and now i know , what is pose, what is rig , and also subpose. 
and i find the code in cameraInit. that if i use rig camera, i should create a folder named with 'rig'. 
if subfolder 'left' and 'right' . how to give the image name?
and i find in incrementalSfM, it's not load any calibration data. 
also, there is no param to tell the system. 
but i find there are a command, aliceVision_rigCalibration. maybe have some connection with it, that i still don't know how to pipline caminit, incrementalSfM, rigCalibration.

my question is . how to set my stereo camera into the system. i know the right/Left cameras R,and T.
or, how to use rigcalibration in meshroom . so that i can keep reading the code.

**Comment by natowi** [comment]
These features are not supported in the current MR 2018.1 release.

**Comment by eroswade** [comment]
@natowi  thank you .
i find that aliceVision_globalSfM contain it . but not in aliceVision_incrementalSfM. 
now a days , i working on openmvg. 
thanks a lot
