### ISSUE TITLE
Support UNC paths in incrementalSFM

### ISSUE THREAD

**Issue by kbladin** [alicevision/AliceVision#561]
### Problem

IncrementalSFM crashes after *Compute scene structure color* if UNC paths (non-mounted network drived) are used on windows. Seemingly when some file (finished sfm file?) is written to the drive.

**Expected behavior:**
Files should be writted to the drive even if the path starts with "\\\\"

**Actual behavior:**  
Program (aliceVision_incrementalSfm.exe) crashes after *Compute scene structure color* has reached 100%

### Steps to Reproduce

1. Run the previous required steps in the pipeline before aliceVision_incrementalSfm.exe
2. run aliceVision_incrementalSfm.exe with standard arguments but use a UNC path as output folder
e.g.

```aliceVision\bin\aliceVision_incrementalSfm.exe --minAngleForLandmark 2.0 --minNumberOfObservationsForTriangulation 2 --maxAngleInitialPair 40.0 --maxNumberOfMatches 0 --localizerEstimator acransac --describerTypes sift --lockScenePreviouslyReconstructed False --localBAGraphDistance 1 --initialPairA "" --initialPairB "" --interFileExtension .abc --useLocalBA True --minInputTrackLength 2 --useOnlyMatchesFromInputFolder False --verboseLevel info --minAngleForTriangulation 3.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --input "\\path\to\cameraInit.sfm" --featuresFolders "\\path\to\FeatureExtraction" --matchesFolders "\\path\to\FeatureMatching" --outputViewsAndPoses "\\path\to\StructureFromMotion\cameras.sfm" --extraInfoFolder "\\path\to\StructureFromMotion" --output "\\path\to\StructureFromMotion\sfm.sfm"```

### Versions

* AliceVision branch/version: Release 2.0.0 (2018/08/09)
* OS: Windows 10
* C++ compiler: Precompiled release

**Comment by belegdae** [comment]
Appears to be an issue with the boost library:
https://github.com/boostorg/filesystem/issues/87
