### ISSUE TITLE
Max_flow is single threaded?

### ISSUE THREAD

**Issue by TashaSkyUp** [alicevision/AliceVision#575]
BK Max_flow is single threaded.. horrible performance

please implement non locking multi threaded algorithm:
http://hpc.pnl.gov/mtaap/mtaap08/bohong_flow_max.pptx

**Expected behavior:**  
fast perfomance on all steps with a high end system
**Actual behavior:**  
poor performance in step "Compute boykov_kolmogorov_max_flow"

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* AliceVision branch/version:
* OS: 
* C++ compiler:

**Comment by pocketpixels** [comment]
The presentation you linked to shows a speedup of something like 25% compared to single threaded. And performance seems to get worse beyond 2 threads. 
Calling the single threaded algorithm performance 'horrible' based on that seems a bit exaggerated, no?

**Comment by zvrba** [comment]
> The presentation you linked to shows a speedup of something like 25% compared to single threaded. 

The paper is about *lock-free* parallel algorithm. The speedup of 25% compared to *lock-based* multithreaded algorithm, not single-threaded.

**Comment by pocketpixels** [comment]
I haven't read the paper, but the ~25% speedup is from slide 16 of the presentation linked to above, and that is relative to single threaded performance (thread count 1, the left most dot).

**Comment by zvrba** [comment]
Ah yes, I misinterpreted the figure.
