### ISSUE TITLE
AliceVision pre 2.1 Win x64 fails on Ceres lib

### ISSUE THREAD

**Issue by bluecd** [alicevision/AliceVision#586]
LINK : fatal error LNK1181: cannot open input file 'D:\Programowanie\AliceVision\build\external\lapack_build\lib\liblapack.so' [D:\Programowanie\AliceVision\build\external\ceres_build\internal\ceres\ceres.vcxproj]

While building on MSVC2017 x64 w/dependencies, build fails with CERES lib,
looks for non existing *.so library /Linux remains?/

MSVC2017 Community x64, building w/fetchting dependencies

**Comment by yann-lty** [comment]
How did you configure your project? Did you use the `ALICEVISION_BUILD_DEPENDENCIES` option? This has only been tested on Linux systems.
To build AliceVision on Windows, we recommend using VCPKG to build external dependencies, as described [here](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#building-the-project-using-vcpkg-recommended-on-windows).

**Comment by bluecd** [comment]
> How did you configure your project? Did you use the `ALICEVISION_BUILD_DEPENDENCIES` option? This has only been tested on Linux systems.
> To build AliceVision on Windows, we recommend using VCPKG to build external dependencies, as described [here](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#building-the-project-using-vcpkg-recommended-on-windows).

Yes, I did ALICEVISION_BUILD_DEPENDENCIES.
Trying to squeeze as much as possible from the framework, Meshroom is terribly slow so far.
As you may noticed many libs are not/yet/ available on VCPKG.

**Comment by yann-lty** [comment]
All the required libs are actually available on VCPKG, this is how we build AliceVision on our side. If you follow the guide I was mentioning, it will setup a ready-to-build Visual Studio project.

**Comment by bluecd** [comment]
> All the required libs are actually available on VCPKG, this is how we build AliceVision on our side. If you follow the guide I was mentioning, it will setup a ready-to-build Visual Studio project.

This may be true but so far I received 'CameraInit Error 1' when using built AliceVision w/Meshroom.
