### ISSUE TITLE
linking problem when building aliceVision_matching

### ISSUE THREAD

**Issue by maorp** [alicevision/AliceVision#595]
Hi,
linking problem when building alicevision_matching, unresolved ext symbols. 
from VS build log:

Error	LNK2019	unresolved external symbol LZ4_decompress_safe referenced in function "private: void __cdecl flann::serialization::LoadArchive::decompressAndLoadV10(struct _iobuf *)" (?decompressAndLoadV10@LoadArchive@serialization@flann@@AEAAXPEAU_iobuf@@@Z)	aliceVision_matching	D:\dev\AliceVision\build\src\aliceVision\matching\RegionsMatcher.obj	1	
Error	LNK2019	unresolved external symbol LZ4_setStreamDecode referenced in function "private: void __cdecl flann::serialization::LoadArchive::initBlock(struct _iobuf *)" (?initBlock@LoadArchive@serialization@flann@@AEAAXPEAU_iobuf@@@Z)	aliceVision_matching	D:\dev\AliceVision\build\src\aliceVision\matching\RegionsMatcher.obj	1	
Error	LNK2019	unresolved external symbol LZ4_decompress_safe_continue referenced in function "private: void __cdecl flann::serialization::LoadArchive::loadBlock(char *,unsigned __int64,struct _iobuf *)" (?loadBlock@LoadArchive@serialization@flann@@AEAAXPEAD_KPEAU_iobuf@@@Z)	aliceVision_matching	D:\dev\AliceVision\build\src\aliceVision\matching\RegionsMatcher.obj	1	
Error	LNK2019	unresolved external symbol LZ4_resetStreamHC referenced in function "private: void __cdecl flann::serialization::SaveArchive::initBlock(void)" (?initBlock@SaveArchive@serialization@flann@@AEAAXXZ)	aliceVision_matching	D:\dev\AliceVision\build\src\aliceVision\matching\RegionsMatcher.obj	1	
Error	LNK2019	unresolved external symbol LZ4_compress_HC_continue referenced in function "public: void __cdecl flann::serialization::SaveArchive::save_binary<void const >(void const *,unsigned __int64)" (??$save_binary@$$CBX@SaveArchive@serialization@flann@@QEAAXPEBX_K@Z)	aliceVision_matching	D:\dev\AliceVision\build\src\aliceVision\matching\RegionsMatcher.obj	1	
Error	LNK1120	5 unresolved externals	aliceVision_matching	D:\dev\AliceVision\build\Windows-AMD64\Release\aliceVision_matching.dll	1	

* AliceVision branch/version: develop
* OS: windows 10
* C++ compiler: VS2015 

thanks for the cool sw!

**Comment by fabiencastan** [comment]
Could you try to add `lz4` here: https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/matching/CMakeLists.txt#L32

**Comment by maorp** [comment]
adding lz4 to matching cmakelist helped!
