### ISSUE TITLE
libssl1.0-dev needed, which is not installed by ubuntu18.04 by default

### ISSUE THREAD

**Issue by mepster** [alicevision/AliceVision#599]
Thanks for all your work, amazing software!

### Problem
meshroom / alicevision needs libssl1.0-dev, which is not installed by default on ubuntu.

**Expected behavior:**
meshroom/alicevision would run without error messages.

**Actual behavior:**

I got the error message "qt.network.ssl: Incompatible version of OpenSSL"

qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL

I was able to fix this with "sudo apt-get install libssl1.0-dev" 

### Steps to Reproduce

1. Compile & install alicevision with the ubuntu18.04 docker image.

2. Run alicevision (via meshroom)

3. I get the openssl error above.

4. I was able to fix this with "sudo apt-get install libssl1.0-dev"

5) So maybe you want to:
  a) ask people to install libssl1.0-dev in the INSTALL.md instructions, OR
  b) have  libssl1.0-dev compiled in with the docker image if possible

### Versions

* AliceVision branch/version: from the the ubuntu18.04 alicevision docker image from commit 4f9b8d36d4ef376cba724273a1dc1483bab73a5b
* OS: ubuntu 18.04
* C++ compiler: ... from the the ubuntu18.04 alicevision docker image from commit 4f9b8d36d4ef376cba724273a1dc1483bab73a5b

P.S. Compiling alicevision with the docker image work great! So much easier than getting all those libraries working! You should highlight this at the top of the INSTALL.md instructions as the preferred method!

Thanks for the great open source sw.

**Comment by fabiencastan** [comment]
Thanks for the report. Really sorry for the delay!
I agree that adding it to the dockerfile seems to be the right way.

Could you submit a PR with a `Dockerfile_ubuntu` (as we have done on the https://github.com/alicevision/AliceVision/blob/develop/Dockerfile_ubuntu side)?
I think, we just need to replace the yum commands by apt and find the corresponding packages.

Best,
