### ISSUE TITLE
[localization] Test against ground truth of the CCTag localizer.

### ISSUE THREAD

**Issue by lcalvet** [alicevision/AliceVision#60]
Tests with the following scenario:
- CCTag based reconstruction
- SIFT+CCTag based reconstruction

Test with different image matching techniques.

**Comment by simogasp** [comment]
* Problem with CCTag and Levallois for the reconstruction: the number of visible CCTag is not enough and many of them are rejected
* Problem with CCTag and Levallois for the localization: the CCTag are too small/the image size is not adequate for detection --> parameter tuning is required or upscale of images

**Comment by simogasp** [comment]
Now the first problem (reconstruction) can be fixed by doing a sift reconstruction and then using `main_ComputeCCTagStructureFromKnownPoses`. The second still holds.
