### ISSUE TITLE
Is it possible to import an SfM scene from OpenMVG?

### ISSUE THREAD

**Issue by ssampang** [alicevision/AliceVision#600]
Our pipeline currently uses OpenMVG to generate a sparse point cloud and localize the cameras. We're interested in hooking up AliceVision to take the output of OpenMVG and generate a dense pointcloud. I wasn't able to find any documentation outlining how to import an SfM scene generated by a separate library - is this feasible currently? If not, can you give us guidelines on how we can go about implementing it?

Thanks!

**Comment by simogasp** [comment]
Hi @ssampang , u should use the json format. Openmvg and alicevision json formats are very similar in the structure but not compatible right away as openmvg is a data serialization file among other things. 
The best way to proceed is for you to write a piece of code in openmvg that loads a SfmData from a json file and save the SfmData into alicevision format. It is not a difficult task per se, maybe the more difficult part is to have a simple tool to generate the json file (here we use boost). You can have a look at the writeJson() function here https://github.com/alicevision/AliceVision/blob/25a9de0a482d1b23d604e45800d29c3449d999d0/src/aliceVision/sfmDataIO/jsonIO.cpp#L267
to have the gist of it.

**Comment by fabiencastan** [comment]
Does that answer your question or do you need more information?

**Comment by ssampang** [comment]
That answered my question. Thanks!

**Comment by PeterBetlem** [comment]
@ssampang Out of curiosity, what would be the workflow you implemented in combining openMVG and meshroom? I don't believe EXIF-based GPS coordinates have been implemented in Meshroom yet (please point out if I am wrong), and am thinking about using openMVG to generate a GPS-calibrated sfm scene, which I then hope to import into Meshroom to further play around with. Any advice?

**Comment by natowi** [comment]
@ssampang https://github.com/alicevision/AliceVision/issues/600#issuecomment-460535949
Without a small tool to convert the sfm format, this won´t work.

**Comment by PeterBetlem** [comment]
Thanks for the heads-up @natowi.
