### ISSUE TITLE
Trailing semicolon should be removed from cameraSensors.db

### ISSUE THREAD

**Issue by xzhub** [alicevision/AliceVision#601]
**Problem**
with the latest [cameraSensors.db](https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db) file, meshroom still report error like:

```
[06:46:17.667747][error] Sensor width doesn't exist in the database for image(s) :
[06:46:17.667864][error] image: '171.jpg'
	- camera brand: RaspberryPi
	- camera model: RP_OV5647

[06:46:17.667879][error] Please add camera model(s) and sensor width(s) in the database.
```

After I removed the trailing semicolon from that line, meshroom run through. 

4791:RaspberryPi;RP_OV5647;3.76;

==>

4791:RaspberryPi;RP_OV5647;3.76

I believe all the other lines which has trailing semicolon should be fixed as well. I was trying to submit a pull request, but I don't even have the permission to create a branch. Still trying to figure out the reason, but I think it's better to raise this issue first.

**Comment by fabiencastan** [comment]
Hi,
The cameraSensors.db has changed and you cannot use the new file with the previous release.
A new release is coming soon.
Best,
