### ISSUE TITLE
"has no member named 'get_string' " on make

### ISSUE THREAD

**Issue by dnzzcn** [alicevision/AliceVision#609]
I have been trying to install AliceVision for the last 9 hours and now I get the following error:

---
alice/AliceVision/src/aliceVision/image/io.cpp:89:51: error: ‘const class OpenImageIO::v1_6::ParamValue’ has no member named ‘get_string’
     metadata.emplace(param.name().string(), param.get_string());
                                                   ^
src/aliceVision/image/CMakeFiles/aliceVision_image.dir/build.make:110: recipe for target 'src/aliceVision/image/CMakeFiles/aliceVision_image.dir/io.cpp.o' failed
make[2]: *** [src/aliceVision/image/CMakeFiles/aliceVision_image.dir/io.cpp.o] Error 1
CMakeFiles/Makefile2:2317: recipe for target 'src/aliceVision/image/CMakeFiles/aliceVision_image.dir/all' failed
make[1]: *** [src/aliceVision/image/CMakeFiles/aliceVision_image.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
---

Any suggestions on how to solve this?

Thanks

**Comment by macnib** [comment]
Ya, I think you have an older version of OpenImageIO. Looks like version 1.6 in your case. Think the documentation wants 1.8 or greater. Anyhow, compiling with the latest code and installing fixed it for me on Linux Ubuntu.
