### ISSUE TITLE
Fails to find CUDA enabled GPU.

### ISSUE THREAD

**Issue by ejnaren** [alicevision/AliceVision#610]
### Problem
I am using the default setup, but the computation stops at the DepthMap node.
It seems it cant find the CUDA enabled GPU.
But my machine is running with a NVIDIA Quadro M2000 (CUDA 5+).

Is there any way to solve this in settings og help debug this further?

Here is the error repport from the nodes log:
"Program called with the following parameters:
 * downscale = 2
 * ini = "D:/Personal Projects/Lillingstonheimen/Meshroom/MeshroomCache/PrepareDenseScene/6caf53b4af5416b6167da35d63af90efca8cbdaf/mvs.ini"
 * output = "D:/Personal Projects/Lillingstonheimen/Meshroom/MeshroomCache/DepthMap/df7bb3d94a2a833d1c5aa2f032d33a5a2cbe5ad6"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "debug"

[08:00:31.686040][info] 
[08:00:31.690036][debug] Can't find CUDA-Enabled GPU.
[08:00:31.691036][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
"

### Steps to Reproduce

Not relevant as its a hardware issue, although I use the default setup when starting the program.

### Versions

* AliceVision branch/version: 2018.1.0
* OS: Windows 10
* C++ compiler: NA

Im attaching a Blender generated system-info txt.
Its not all relevant to Meshroom but contains info on the GPU that might be useful...
[system-info.txt](https://github.com/alicevision/AliceVision/files/2888081/system-info.txt)

**Comment by ejnaren** [comment]
I see i have created this issue in ALiceVision main.
It should have gone into the Meshrrom repo.
So ill check out the answers to this issue:
[https://github.com/alicevision/meshroom/issues/260](url)
and ill get back with the results...

**Comment by ejnaren** [comment]
Alright. This issue is solved by updating the graphics drivers as mentioned in above post.

**Comment by johnav** [comment]
https://github.com/alicevision/meshroom/issues/260
No results matched your search.
congratulation
Дoes not work!
