### ISSUE TITLE
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'

### ISSUE THREAD

**Issue by Vova-B** [alicevision/AliceVision#612]
### Problem
I run the reconstruction from the console and get the error `terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  basic_ios::clear: iostream error` when i use more 200 images.

The complete output log I attach the link: https://gist.github.com/Vova-B/1707d91dedd1dae59ef18eb4dbcfca9b

**Expected behavior:**  

**Actual behavior:**  

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* AliceVision branch/version: last version
* OS: Ubuntu
* C++ compiler: gcc 5.4.0

**Comment by zvrba** [comment]
Can you run `ulimit -a` in the terminal and paste the output here?

**Comment by Vova-B** [comment]
@zvrba Here is the output of the command:
`core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 120482
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 120482
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
`

**Comment by zvrba** [comment]
Ok, I thought that the problem could be caused by the process having a low limit on open files, but it's 1024 which is well above 200. (In case there was a bug where opened files were never closed.)

**Comment by Vova-B** [comment]
@zvrba I even increased the file limit to 500,000, but I still get this error.

**Comment by fabiencastan** [comment]
It has problems loading multiple files... I have never seen this error.
Do you have special characters in your paths? Meshroom installation folder, images folders of your dataset or meshroom project folder?

**Comment by fabiencastan** [comment]
Have you found a solution?
When we use more than 200 images, we use the vocabulary tree. Could you check that this file is not corrupted? Maybe download it again and on another storage...
If it doesn't work, a workaround, could be to not use the vocabularytree in the ImageMatching (set `ImageMatching.nbMatches` to 0). It will slow down the reconstruction process on large datasets, but at least it should work.
