### ISSUE TITLE
camera sensors db addition Nikon D500

### ISSUE THREAD

**Issue by jsa2340** [alicevision/AliceVision#625]
Add,
Nikon;D500;23.5;

The existing Nikon;Nikon D500;23.5 generates a warning.

I am using RAW image files for what it's worth.

**Comment by a4guy** [comment]
ok

**Comment by natowi** [comment]
Will be fixed with the next release.

**Comment by jsa2340** [comment]
Thanks

**Comment by natowi** [comment]
I just checked this with a few images. Meshroom (based on alicevision) can already handle brand and model variations:

[warning] image: 'DSC_226.jpg'
        - image camera brand: NIKON CORPORATION
        - image camera model: NIKON D500
      
        - database camera brand: Nikon
        - database camera model: Nikon D500
        - database camera sensor size: 23.5 mm

or

[warning] image: 'DSC_1825.NEF'
        - image camera brand: Nikon
        - image camera model: D500

        - database camera brand: Nikon
        - database camera model: Nikon D500
        - database camera sensor size: 23.5 mm

**Comment by jsa2340** [comment]
I needed to remove Nikon from the camera model for the warning to cease.
`    - database camera brand: Nikon
    - database camera model: D500
    - database camera sensor size: 23.5 mm`

**Comment by natowi** [comment]
This is just the notification that Meshroom/alicevision did not find an exact match in the database and is using the closest match (Nikon;Nikon D500;23.5). If you are using Meshroom GUI, you can ignore this message - or are you using the Alicevision CLI and can not continue unless you modify the database?

Changing Nikon;Nikon D500;23.5; to Nikon;D500;23.5; by default would solve the warning message for you, but would now appear for users with the model metadata Nikon D500...

---
[10:35:47.580347][warning] The camera found in the database is slightly different for image(s):
[10:35:47.581340][warning] image: 'DSC_1825.NEF'
        - image camera brand: Nikon
        - image camera model: D500
        - database camera brand: Nikon
        - database camera model: Nikon D500
        - database camera sensor size: 23.5 mm
[10:35:47.583324][warning] Please check and correct camera model(s) name in the database.

@fabiencastan we might want to clarify the warning messages in this case, to inform the user that it is not necessary to correct the camera model in the database, if the correct variation is detected.

**Comment by jsa2340** [comment]
Meshroom GUI. I could continue, though uncertain of how it might impact results.

I just added Nikon;D500;23.5 leaving the verbose Nikon D500 version in place. It caused no issue for me, having both in place, so I suspect the reverse would be true.

**Comment by fabiencastan** [comment]
This will not impact the result as far as the mapping is correct.
The goal of the warning is to allow users to check the mapping. In you case the mapping between "Nikon/D500" and "Nikon/Nikon D500" is obviously fine.

As there is no good way to deal with this mapping, we prefer to keep a warning to ensure that we don't get a border case mapping together 2 completely different cameras.
