### ISSUE TITLE
BUG raw_r and lcms2 missing in build from source

### ISSUE THREAD

**Issue by EnricoBeltramo** [alicevision/AliceVision#630]
I built AliceVision from source following instruction in paragraph "Building the project using vcpkg (recommended on Windows)". The build was complete correctly. If I start the user interface by meshroom, it open correctly but when I try to import images it say that dll raw_r.dll and lcms.dll are missing. How can I generate them?

- step 1) build using instruction "Building the project using vcpkg (recommended on Windows)"
- step 2) import images

I use:
Windows 2010 Home
Visual Studio 2017
Cuda 9

**Comment by EnricoBeltramo** [comment]
I found that those files aren't copied when I build in debug mode. If I build in Release, it works fine.

**Comment by fabiencastan** [comment]
Seems to be an issue within vcpkg, isn't it?

**Comment by ChaoJia** [comment]
I worked around this issue by modifying [the port file for libraw](https://github.com/microsoft/vcpkg/tree/master/ports/libraw) before install it:
remove this line: `-DCMAKE_DEBUG_POSTFIX=d`
and change all the `rawd.lib` and `rawd.dll` in the portfile to `raw.lib` and `raw.dll` respectively.

I did not touch lcms. `lcms2d.dll` was copied and loaded correctly.

However, I found it is also necessary for me to remove the postfix of debug build for `openexr `by applying the following patch (lastest portfile are used):
```
diff --git a/IlmBase/CMakeLists.txt b/IlmBase/CMakeLists.txt
index 95942c8..813de64 100644
--- a/IlmBase/CMakeLists.txt
+++ b/IlmBase/CMakeLists.txt
@@ -18,9 +18,6 @@ INCLUDE_DIRECTORIES ( Iex IexMath Imath Half
     IlmThread IexTest ImathTest HalfTest
     ${CMAKE_CURRENT_BINARY_DIR}/config )
 
-IF(WIN32)
-  SET(CMAKE_DEBUG_POSTFIX "_d")
-ENDIF()
 
 # also add the current directory to pick up the autogenerated headers
 SET(CMAKE_INCLUDE_CURRENT_DIR ON)
diff --git a/OpenEXR/CMakeLists.txt b/OpenEXR/CMakeLists.txt
index 9ddafa8..e793417 100644
--- a/OpenEXR/CMakeLists.txt
+++ b/OpenEXR/CMakeLists.txt
@@ -16,9 +16,6 @@ IF (NOT WIN32)
   SET ( PTHREAD_LIB pthread )
 ENDIF()
 
-IF(WIN32)
-  SET(CMAKE_DEBUG_POSTFIX "_d")
-ENDIF()
 
 
 MACRO(SET_ILMBASE_INCLUDE_DIRS _target)
```

More information on patching can be found [here](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/patching.md)

Tested `aliceVision_texturing` in debug mode, and it went very smoothly and extremely slow.

**Comment by ChaoJia** [comment]
with [this PR](https://github.com/microsoft/vcpkg/pull/8379) being merged into vcpkg master branch, this issue should be resolved automatically. The workaround above is no longer necessary. If the issue persists, remove `FindOpenEXR.cmake` and `FindOpenImageIO.cmake` (optionally `FindGeogram.cmake` and `FindSuiteSparse.cmake`) located under `${aliceVision_root}/src/cmake`. It might be a good idea to include these modules only if vcpkg is not in use.
