### ISSUE TITLE
BUG: isse on build from repo

### ISSUE THREAD

**Issue by EnricoBeltramo** [alicevision/AliceVision#631]
I have some issue if I build from repository:
- At load give me a warning:
loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2019-05-03 13:52:37,485][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

If I use follow set of images:
[https://codeload.github.com/openMVG/ImageDataset_SceauxCastle/zip/master](url)

- I have to drag and drop twice the picture in order to see them loaded from SW.
- After StructureFromMotion, the result is no show in graphic (either the file are processed and present in the folder)
- The final step "Texturing" fails (I attach the log file
[log.zip](https://github.com/alicevision/AliceVision/files/3141755/log.zip)
)

Any of those issue don't appears if I use the latest prebuild version

I use:
Windows 2010 Home
Visual Studio 2017
Cuda 9

**Comment by fabiencastan** [comment]
- For the warning about simpleFarmSubmitter, we just remove the simpleFarm submitter from the release.

- For the viewer, you need to install https://github.com/alicevision/qmlAlembic and https://github.com/alicevision/QtOIIO to get all features that you have in the release.

- I don't know for the drag&drop problem: maybe a problem with non-ascii characters in your path?

- The crash on the Texturing node is surprising... Could you relaunch it with "verbose" set to "trace"? Which branch of AliceVision are you using?
