### ISSUE TITLE
Can't run Cook in Houdini

### ISSUE THREAD

**Issue by artofka** [alicevision/AliceVision#636]
01_Camera_init node inside sop_av_initialize1 catch error:

Error | Python error: Traceback (most recent call last):File "", line 40, in File "opdef:/gamedev::Sop/sop_av_initialize::2.0?PythonModule", line 42, in logFile "/opt/hfs17.5.173/python/lib/python2.7/subprocess.py", line 394, in __init__errread, errwrite)File "/opt/hfs17.5.173/python/lib/python2.7/subprocess.py", line 1047, in _execute_childraise child_exceptionOSError: [Errno 2] No such file or directory
-- | --

Opensuse 42.2 / Houdini 17.5.173 / AliceVision-2.1.0

**Comment by natowi** [comment]
For Houdini related questions go to https://github.com/sideeffects/GameDevelopmentToolset/issues

**Comment by artofka** [comment]
Thanks

**Comment by artofka** [comment]
Moved in sideeffects/GameDevelopmentToolset issues
