### ISSUE TITLE
BUG: incorrect index calculation for "bottom-right to up-left" scan in void Texturing::generateTexturesSubSet(...)

### ISSUE THREAD

**Issue by ChaoJia** [alicevision/AliceVision#644]
Got `Abnormal program termination: received signal 11 (SIGSEGV)` in step `[11/11] Texturing`.

I built and compiled AliceVision with vcpkg and VS 2017 (15.9.12) under Windows 10 from the lastest commit in develop branch (commit 132ac39d67b8ba9a356b6b66c245ccf0e8f59258), and ran the photogrammetry pipeline through `python bin/meshroom_photogrammetry`.

[dataset_monstree/mini3](https://github.com/alicevision/dataset_monstree/tree/master/mini3) was used.

After changing 
```
617 unsigned int yoffset = (outTextureSide - y) * outTextureSide;
...
620     unsigned int xyoffset = yoffset + (outTextureSide - x);
```

to 

```
617 unsigned int yoffset = (outTextureSide - y - 1) * outTextureSide;
...
620     unsigned int xyoffset = yoffset + (outTextureSide - x - 1);
```
in file  `${AliceVision_root}/src/aliceVision/mesh/Texturing.cpp`, the problem went away, and the generated texture seems to be correct.

**Comment by fabiencastan** [comment]
Thanks for the report and the analysis!
We are aware of it and we are about to merge the PR https://github.com/alicevision/AliceVision/pull/629 in the coming days which already fixes this issue (and contains texturing improvements).

**Comment by ChaoJia** [comment]
Thanks!
