### ISSUE TITLE
Installation issue MacOS

### ISSUE THREAD

**Issue by Goldname98** [alicevision/AliceVision#649]
Running these commands:

git clone --recursive https://github.com/alicevision/AliceVision.git
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -G "Xcode" ../AliceVision

Result in an error (openMP and Boost are not found):

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Force CMAKE_INSTALL_DO_STRIP in Release
-- ----------------------------------------
-- ALICEVISION_BUILD_DEPENDENCIES: OFF
-- ALICEVISION_BUILD_TESTS: OFF
-- AV_BUILD_CUDA: OFF
-- AV_BUILD_ZLIB: ON
-- AV_BUILD_TIFF: ON
-- AV_BUILD_JPEG: ON
-- AV_BUILD_PNG: ON
-- AV_BUILD_LIBRAW: ON
-- AV_BUILD_POPSIFT: ON
-- AV_BUILD_OPENGV: ON
-- AV_BUILD_LAPACK: ON
-- AV_BUILD_SUITESPARSE: ON
-- CMAKE_BUILD_TYPE: Release
-- DEPS_CMAKE_BUILD_TYPE: Release
-- CMAKE_INSTALL_LIBDIR: lib
-- CMAKE_INSTALL_PREFIX: /usr/local
-- CMAKE_INSTALL_RPATH: 
-- CMAKE_INSTALL_DO_STRIP: TRUE
-- ----------------------------------------
CMake version: 3.14
-- ** ALICEVISION_BUILD_DOC: 'AUTO'
-- ** ALICEVISION_USE_OPENMP: 'ON'
-- ** ALICEVISION_USE_CCTAG: 'AUTO'
-- ** ALICEVISION_USE_POPSIFT: 'AUTO'
-- ** ALICEVISION_USE_OPENGV: 'AUTO'
-- ** ALICEVISION_USE_ALEMBIC: 'AUTO'
-- ** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
-- ** ALICEVISION_USE_CUDA: 'ON'
-- ** ALICEVISION_USE_OPENCV: 'OFF'
-- target changed from "" to "auto"
-- Detected Host CPU: haswell
-- Performing Test check_c_compiler_flag__march_haswell
-- Performing Test check_c_compiler_flag__march_haswell - Success
-- Performing Test check_cxx_compiler_flag__march_haswell
-- Performing Test check_cxx_compiler_flag__march_haswell - Success
-- Performing Test check_c_compiler_flag__msse2
-- Performing Test check_c_compiler_flag__msse2 - Success
-- Performing Test check_cxx_compiler_flag__msse2
-- Performing Test check_cxx_compiler_flag__msse2 - Success
-- Performing Test check_c_compiler_flag__msse3
-- Performing Test check_c_compiler_flag__msse3 - Success
-- Performing Test check_cxx_compiler_flag__msse3
-- Performing Test check_cxx_compiler_flag__msse3 - Success
-- Looking for C++ include pmmintrin.h
-- Looking for C++ include pmmintrin.h - found
-- Performing Test check_c_compiler_flag__mssse3
-- Performing Test check_c_compiler_flag__mssse3 - Success
-- Performing Test check_cxx_compiler_flag__mssse3
-- Performing Test check_cxx_compiler_flag__mssse3 - Success
-- Looking for C++ include tmmintrin.h
-- Looking for C++ include tmmintrin.h - found
-- Performing Test check_c_compiler_flag__msse4_1
-- Performing Test check_c_compiler_flag__msse4_1 - Success
-- Performing Test check_cxx_compiler_flag__msse4_1
-- Performing Test check_cxx_compiler_flag__msse4_1 - Success
-- Looking for C++ include smmintrin.h
-- Looking for C++ include smmintrin.h - found
-- Performing Test check_c_compiler_flag__msse4_2
-- Performing Test check_c_compiler_flag__msse4_2 - Success
-- Performing Test check_cxx_compiler_flag__msse4_2
-- Performing Test check_cxx_compiler_flag__msse4_2 - Success
-- Performing Test check_c_compiler_flag__mavx
-- Performing Test check_c_compiler_flag__mavx - Success
-- Performing Test check_cxx_compiler_flag__mavx
-- Performing Test check_cxx_compiler_flag__mavx - Success
-- Looking for C++ include immintrin.h
-- Looking for C++ include immintrin.h - found
-- Performing Test check_c_compiler_flag__mfma
-- Performing Test check_c_compiler_flag__mfma - Success
-- Performing Test check_cxx_compiler_flag__mfma
-- Performing Test check_cxx_compiler_flag__mfma - Success
-- Performing Test check_c_compiler_flag__mbmi2
-- Performing Test check_c_compiler_flag__mbmi2 - Success
-- Performing Test check_cxx_compiler_flag__mbmi2
-- Performing Test check_cxx_compiler_flag__mbmi2 - Success
-- Performing Test check_c_compiler_flag__mavx2
-- Performing Test check_c_compiler_flag__mavx2 - Success
-- Performing Test check_cxx_compiler_flag__mavx2
-- Performing Test check_cxx_compiler_flag__mavx2 - Success
-- Performing Test check_c_compiler_flag__mno_sse4a
-- Performing Test check_c_compiler_flag__mno_sse4a - Success
-- Performing Test check_cxx_compiler_flag__mno_sse4a
-- Performing Test check_cxx_compiler_flag__mno_sse4a - Success
-- Performing Test check_c_compiler_flag__mno_xop
-- Performing Test check_c_compiler_flag__mno_xop - Success
-- Performing Test check_cxx_compiler_flag__mno_xop
-- Performing Test check_cxx_compiler_flag__mno_xop - Success
-- Performing Test check_c_compiler_flag__mno_fma4
-- Performing Test check_c_compiler_flag__mno_fma4 - Success
-- Performing Test check_cxx_compiler_flag__mno_fma4
-- Performing Test check_cxx_compiler_flag__mno_fma4 - Success
-- Performing Test check_c_compiler_flag__mno_avx512f
-- Performing Test check_c_compiler_flag__mno_avx512f - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512f
-- Performing Test check_cxx_compiler_flag__mno_avx512f - Success
-- Performing Test check_c_compiler_flag__mno_avx512vl
-- Performing Test check_c_compiler_flag__mno_avx512vl - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vl
-- Performing Test check_cxx_compiler_flag__mno_avx512vl - Success
-- Performing Test check_c_compiler_flag__mno_avx512pf
-- Performing Test check_c_compiler_flag__mno_avx512pf - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512pf
-- Performing Test check_cxx_compiler_flag__mno_avx512pf - Success
-- Performing Test check_c_compiler_flag__mno_avx512er
-- Performing Test check_c_compiler_flag__mno_avx512er - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512er
-- Performing Test check_cxx_compiler_flag__mno_avx512er - Success
-- Performing Test check_c_compiler_flag__mno_avx512cd
-- Performing Test check_c_compiler_flag__mno_avx512cd - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512cd
-- Performing Test check_cxx_compiler_flag__mno_avx512cd - Success
-- Performing Test check_c_compiler_flag__mno_avx512dq
-- Performing Test check_c_compiler_flag__mno_avx512dq - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512dq
-- Performing Test check_cxx_compiler_flag__mno_avx512dq - Success
-- Performing Test check_c_compiler_flag__mno_avx512bw
-- Performing Test check_c_compiler_flag__mno_avx512bw - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512bw
-- Performing Test check_cxx_compiler_flag__mno_avx512bw - Success
-- Performing Test check_c_compiler_flag__mno_avx512ifma
-- Performing Test check_c_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma
-- Performing Test check_cxx_compiler_flag__mno_avx512ifma - Success
-- Performing Test check_c_compiler_flag__mno_avx512vbmi
-- Performing Test check_c_compiler_flag__mno_avx512vbmi - Success
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi
-- Performing Test check_cxx_compiler_flag__mno_avx512vbmi - Success
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Error at src/CMakeLists.txt:231 (message):
  Failed to find OpenMP.

CMake Error at src/CMakeLists.txt:259 (message):
  Failed to find Boost.

CMake Error at src/CMakeLists.txt:260 (message):
  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.

-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found Threads: TRUE  
-- Found OpenEXR: /opt/local/include (found version "2.2.0") 
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR: /opt/local/include;/opt/local/include/OpenEXR
Call Stack (most recent call first):
  src/CMakeLists.txt:283 (find_package)

-- OpenEXR found. (Version 2.2.0)
CMake Warning at src/cmake/FindOpenEXR.cmake:164 (message):
  ILMBASE_INCLUDE_DIR: /opt/local/include;/opt/local/include/OpenEXR
Call Stack (most recent call first):
  src/cmake/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:293 (find_package)

CMake Error at src/cmake/FindOpenImageIO.cmake:28 (message):
  Failed to find OpenImageIO - Could not find OpenImageIO include directory,
  set OPENIMAGEIO_INCLUDE_DIR to directory containing OpenImageIO/imageio.h
Call Stack (most recent call first):
  src/cmake/FindOpenImageIO.cmake:90 (openimageio_report_not_found)
  src/CMakeLists.txt:293 (find_package)

-- Configuring incomplete, errors occurred!

Any fixes to this?

**Comment by natowi** [comment]
Follow this guide https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html

**Comment by Goldname98** [comment]
Thank you, but the first step is a "Nvidia GPU with a CUDA compute capability of 2.0 or greater" Why do I need a Nvidia GPU? I have an Intel Iris Pro

**Comment by Goldname98** [comment]
Furthermore, I have Mojave. It says I need high sierra. Is a downgrade necessary?

**Comment by natowi** [comment]
As far as I know, Apple dropped support for nVidia CUDA in Mojave.
