### ISSUE TITLE
[test] Test rig calibration against ground truth.

### ISSUE THREAD

**Issue by lcalvet** [alicevision/AliceVision#65]
Tests should follow the same scenarios as for the localization issue poparteu/openMVG#61.
These tests rely on the dataset delivered by poparteu/popwaffle#5.

**Comment by fabiencastan** [comment]
What is the status?

**Comment by caymard** [comment]
@fabiencastan let it open, I will close it after holidays with clean results.

**Comment by simogasp** [comment]
done?

**Comment by fabiencastan** [comment]
status?
