### ISSUE TITLE
[sfm] Deal with bad CCTag identification in the reconstruction.

### ISSUE THREAD

**Issue by lcalvet** [alicevision/AliceVision#66]
Too many bad identification can lead to duplicated 3D landmarks with only one associated to the correct id. This situation is critical is the case where the minimum track length is very low (e.g. 2 or 3).

**Comment by simogasp** [comment]
@lcalvet @fabiencastan this should have been fixed with computeCCTAGFromKnownPoses?

**Comment by fabiencastan** [comment]
I think the ambition of this issue is to try using CCTag descriptors instead of IDs.

**Comment by simogasp** [comment]
that should be in cctag repository then, isn't it? 
I think this was more related to the fact that cctag were not reconstructed by sfm, due to rejection, hence the need for different values of threshold and so on.

**Comment by fabiencastan** [comment]
It's more related to the usage of the CCTag library. AFAIK, the CCTag library computes a fusion of all the cicular barcodes and then decide what is the ID. The idea here is to directly use the extracted barcode as a photometric descriptor.

So we need to change the 'src/openMVG/features/cctag/CCTAG_describer.cpp' and perform tests on the openMVG matching step to see if it improves the SfM results.
