### ISSUE TITLE
[sfm] Create a metric reconstruction.

### ISSUE THREAD

**Issue by lcalvet** [alicevision/AliceVision#67]
The scale of the reconstruction is currently arbitrary. Develop a solution allowing to provide one or many measures to the reconstruction algorithm used to export a "correctly scaled" reconstruction.
This issue is critical for the evaluation against any ground truth as they are not properly scaled. Therefore, the error on the translation term is irrelevant, yet usable for a comparison between different algorithms as a relative measure.

**Comment by pmoulon** [comment]
Note that there is a solution based on GCP rigid registration that is already available.
Creating and developing a registration API with various input would be logical for OpenMVG v1.0
Origin, relative measurements... axis constraint... we can imagine many... or use CCtag know sizes...
