### ISSUE TITLE
[COMPILATION ERROR] 'getModelPtr': is not a member of 'OsiMskSolverInterface'

### ISSUE THREAD

**Issue by RDelet** [alicevision/AliceVision#676]
### Problem

I try to compile AliceVision and I have this error when I build aliceVision_colorHarmonization project.
**PATH\TO\aliceVision/linearProgramming/OSIXSolver.hpp(286): error C2039: 'getModelPtr': is not a member of 'OsiMskSolverInterface'**

This error is only on Windows ?

### Versions

* AliceVision branch/version: Master
* OS: Windows 10
* C++ compiler: VS 15 2017

**Comment by RDelet** [comment]
Hi everyone,

I found my error. Some libs were not up to date.
But i found three other problem on windows.

1 - Full project is setted with two PLYReader and PLYWriter. First is in AliceVision and other is in OpenMesh getted by VCPKG but aren't a same files. VS use PLY files of Alice vision but if I build project with this file I have error on undeclared vriables **vertexProperties_** and **faceProperties_**. I change name of this file and it works now.
2 - Project AliceVision_matching doesn't have lib lz4.lib setted. It's an error on cmake file ?
3 - I try to set CMAKE_INSTALL_PREFIX for install AliceVision but he doesn't works. Output directory of projects always setted to "D:\ToBuild\AliceVision\build\Windows-AMD64\Release\..." and Post build event doesn't have my CMAKE_INSTALL_PREFIX path. It's an error on cmake file too ?

**Comment by simogasp** [comment]
> 1 - Full project is setted with two PLYReader and PLYWriter. First is in AliceVision and other is in OpenMesh getted by VCPKG but aren't a same files. VS use PLY files of Alice vision but if I build project with this file I have error on undeclared vriables **vertexProperties_** and **faceProperties_**. I change name of this file and it works now.

I don't think you are supposed to use an external version of openMesh, there is already one embedded with `MeshSDFilter`. Isn't that so @fabiencastan ?

> 2 - Project AliceVision_matching doesn't have lib lz4.lib setted. It's an error on cmake file ?

No, most likely it's a secondary dependency that is not correctly propagated. Can you please post the full line of the link command?

> 3 - I try to set CMAKE_INSTALL_PREFIX for install AliceVision but he doesn't works. Output directory of projects always setted to "D:\ToBuild\AliceVision\build\Windows-AMD64\Release..." and Post build event doesn't have my CMAKE_INSTALL_PREFIX path. It's an error on cmake file too ?

Maybe it's a problem of cache, have you tried to remove CMakeCache.txt and redo cmake with the  desired `CMAKE_INSTALL_PREFIX`, ie `-DCMAKE_INSTALL_PREFIX:PATH=C:\My\Favourite\location`

**Comment by RDelet** [comment]
> I don't think you are supposed to use an external version of openMesh, there is already one embedded with MeshSDFilter. Isn't that so @fabiencastan ?


It's possible vcpkg get external openMesh rather than AliceVision openMesh ?

**My full command line is** 

`cmake .. -Wno-dev -DCMAKE_INSTALL_PREFIX="D:/Work/Builded/AliceVision" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019 Win64" -A x64 -T host=x64`

I try with -G "Visual Studio 15 2017 Win64" too.
