### ISSUE TITLE
cmake boost

### ISSUE THREAD

**Issue by xin18060006** [alicevision/AliceVision#684]
CMake Error at src/CMakeLists.txt:259 (message):
  Failed to find Boost.
CMake Error at src/CMakeLists.txt:260 (message):
  Boost version: 1.65.1
  Boost include path: /usr/include
  Could not find the following Boost libraries:
          boost_container
          boost_log
          boost_log_setup
Some (but not all) of the required Boost libraries were found.  You may
need to install these additional Boost libraries.  Alternatively, set
BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
to the location of Boost.

**Expected behavior:**  

**Actual behavior:**  

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* AliceVision branch/version:
* OS: 
* C++ compiler:

**Comment by natowi** [comment]
You need to install the dependencies, see https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

**Comment by dprestegard** [comment]
To be fair, the documentation isn't super clear here.

INSTALL.md contains this:

Setup the required external library.
sudo apt-get install libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev

But... a lot more libraries are actually needed. I got stuck here too. Can this part of the documentation be updated?

**Comment by simogasp** [comment]
yes you are right we should restructure the instructions to make it more clear.

As now you can see that there is a first part of the instructions on how to build all the needed dependencies (vcpkg, using the CMake script etc). So you need to first build all those dependencies, you can use vcpkg no matter which platform you are in or for Linux you can build all the required dependencies directly from CMake
https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#building-the-project-with-embedded-dependencies
adding the flag `-DALICEVISION_BUILD_DEPENDENCIES=ON`.
Note that as explained this require to install some additional building tools.

> Setup the required external library.
sudo apt-get install libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev

As for this you only need 
```
sudo apt-get install libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev
```
