### ISSUE TITLE
[FR]: Save/export to glTF (.glb)

### ISSUE THREAD

**Issue by RafaelLinux** [alicevision/AliceVision#685]
I'm sure it's a hard work, but adopt open and updated technologies should be a priority to make Meshroom better. So, I propose that glTF to be the default 3D model format instead OBJ.
**OBJ**
- Has a limited feature set,
- Is inefficient in terms of storage space and the ability to quickly read and write data, and as consequence, loading and viewing it in a web browser it's very slow.
**glTF**
- Has a very rich set of features.
- Is very efficient at transferring 3D model data
- Adopted in Blender
- A growing set of software, industries and sites are adopting as a standard (Blender, Clara.io, Godot, Sketchfab, Threejs, Facebook ...)

I have no idea about how to do it, cause I'm not a C/C++ programmer, but I'm sure to adopt glTF as default format will make Meshroom the choice for all 3D creator.

Thank you

**Comment by natowi** [comment]
Interesting. https://github.com/KhronosGroup/glTF

**Comment by TheShubham99** [comment]
Any update on this @RafaelLinux? 🤔

**Comment by RafaelLinux** [comment]
Really it seems my question was not interesting for developers, cause no one replied 10 months ago

:/

**Comment by natowi** [comment]
It is interesting, but we have many ideas  to do but limited resources. At the moment the focus is on finishing MR2020.1.

**Comment by fabiencastan** [comment]
Yes it would great to have. It was already in our big dream-list backlog! As it is independent from the pipeline, it would be a perfect feature for a developer who wants to contribute for the first time. If someone is seeing this 🙂

**Comment by simogasp** [comment]
Assimp supports obj and gltf among many others. http://github.khronos.org/glTF-Project-Explorer/
And we can use it also to replace all the code for obj and ply in case

**Comment by hammady** [comment]
I identified an issue in the CMake files that prevents assimp from building with GLTF support. I will follow up shortly with a PR to fix that. While this does not make GLTF the default, but a simple change in the Meshroom pipelines would make this happen.

**Comment by hammady** [comment]
Created the required PRs as noted above.
