### ISSUE TITLE
BUG: a little bug in ${root}/src/aliceVision/depthMap/cuda/PlaneSweepingCuda.cpp

### ISSUE THREAD

**Issue by ChaoJia** [alicevision/AliceVision#689]
https://github.com/alicevision/AliceVision/blob/8ee651300da6e772b8847eb0e9eb321e3c003c9b/src/aliceVision/depthMap/cuda/PlaneSweepingCuda.cpp#L579

This line will cause an index out of bound exception if `out->size() == 0`. Tested on monstree/mini3 dataset, debug mode with vs 2019. However, vs 2017 will let it pass. 

Although it can be easily fixed:

`if(out->size() > 0 && (*out)[0] > (*out)[out->size() - 1])`

I'm not sure whether `out->size() == 0` implies a bug somewhere else.

**Comment by fabiencastan** [comment]
Good catch!
Could you make a PR?

**Comment by ChaoJia** [comment]
> Good catch!

All credit goes to vs 2019 debugger 😄
