### ISSUE TITLE
JSON reader crash on invalid characters from EXIF

### ISSUE THREAD

**Issue by edanvoye** [alicevision/AliceVision#697]
### Problem

aliceVision_cameraInit will store the EXIF data of the images in the .sfm json file. Some strings in the EXIF data may contain characters that are not valid UTF-8 values, this will creash the reader in the subsequent steps. This can happen for example if the Artist EXIF string contains a copyright character.

**Expected behavior:**

aliceVision_cameraInit should sanitize those strings before storing them in the sfm json file.

**Actual behavior:**

Currently, the boost json parser will throw an error when it encounters invalid characters, which will crash aliceVision_featureExtraction.exe without any helpful error message.

### Steps to Reproduce

1. Run cameraInit on an image file with a copyright character in the Artist field (this is 0xA9). 
2. Alternatively, simply edit an .sfm file to add such character manually.
3. Run featureExtraction on thie sfm file.
4. Observe crash.

### Versions

* AliceVision branch/version: 2.2.0 master
* OS: Windows
* C++ compiler: Visual Studio 2015

**Comment by simogasp** [comment]
could you provide an image sample to help fixing it? Thanks

**Comment by edanvoye** [comment]
Yes, here are 4 test files I prepared. These are not actually valid files for sfm, but this will be enough to repro the bug with these commands.

[zip](https://drive.google.com/file/d/1TkIB9ZSF7cZ8UovEvtqLJDp-rCCqJEl6/view?usp=sharing)

    D:\AliceVision-2.2.0\bin\aliceVision_cameraInit.exe --imageFolder D:\bug -o D:\bug\test.sfm -s D:\AliceVision-2.2.0\share\aliceVision\cameraSensors.db
    D:\AliceVision-2.2.0\bin\aliceVision_featureExtraction.exe -i D:\bug\test.sfm -o D:\bug\features
