### ISSUE TITLE
descriptorLoader in imageMatching.exe only works with SIFT

### ISSUE THREAD

**Issue by edanvoye** [alicevision/AliceVision#698]
### Problem

I've noticed the function getListOfDescriptorFiles reads feature descriptor files using hardcoded feature type SIFT to get the file name. I was just trying to use akaze descriptors, which got generated properly, but imageMatching.exe crashes because it cannot find the files with sift in the name.

This makes me wonder... has anyone tried descriptors other than SIFT? 

This is one of the lines in question:
    const std::string filepath = bfs::path(bfs::path(featureFolder) / (std::to_string(view.first) + "." + feature::EImageDescriberType_enumToString(feature::EImageDescriberType::SIFT) + ".desc")).string();

**Expected behavior:**  That function should use the proper filename.

**Actual behavior:**  Exception because the file does not exists.

### Versions

* AliceVision branch/version: master
* OS: windows
* C++ compiler: vs 2015

**Comment by simogasp** [comment]
yes, as now imageMatching only supports SIFT features. But it should be not difficult to extend to other types of descriptors, provided that you have a vocabulary trained with that kind of features. (see utils/main_voctreeCreation)

**Comment by natowi** [comment]
@edanvoye Can you share your akaze descriptor file?
+ Reference https://github.com/alicevision/meshroom/issues/340

**Comment by fabiencastan** [comment]
Yes, the main work is to re-create the voctree for other feature types from thousands of images.
@edanvoye The ImageMatching is using the voctree only if you have more than 200 images (see parameter "Minimal Number of Images"). So if your dataset is not too big and you want to test only with akaze, you can disable the usage of the voctree by putting for instance "Nb Matches" to 0.

**Comment by edanvoye** [comment]
Right, I see. I am testing right now with nbmatches=0, I have datasets with relatively few images (22 to 28) which is pretty typical for human head scans. I am trying to see if I can get good results with these. Results so far are pretty bad with SIFT. With these datasets we have much better results with STAR, I might try to add that to Alice (opencv's implementation).

**Comment by fabiencastan** [comment]
That's a good idea. It would be nice to support more feature and marker types.

**Comment by fabiencastan** [comment]
Sorry for the confusion, I said a mistake. In fact, it makes sense for nbMatches: it will still use the voctree but will keep all matches from the voctree results and not only the best ones.
The only solution is to put a very large value for "minNbImages" like 1000000.

TODO: We should make a fix to make the "tree" argument optional on the command line on the AliceVision side. The code already checks if "tree" is empty and switch to full matching mode, but the argument is still declared required.
TODO: "minNbImages" could recognize -1 to avoid the usage of the voctree (force full matching). This would avoid to choose a random very large value (which will invalidate if you change it).

**Comment by edanvoye** [comment]
To use the brute-force camera matching, I think I can simply bypass imageMatching.exe completely and omit the imagePairsList of featureMatching.
