### ISSUE TITLE
Plan to provide aliceVision as a prebuild C++ Library (.lib...)?

### ISSUE THREAD

**Issue by gameanimation3d** [alicevision/AliceVision#701]
### Problem

Do you plan to provide a prebuild AliceVision Library for C++ (with .lib files, header filles and include folder structure) including the different dependencies for Developer.
As the compiling of aliceVision for everyone else is very difficult and time consuming.

Would be amazing to include AliceVision in a C++ Solution relativily easily. Like for example the SFML Library or other c++ libaries

**Comment by gameanimation3d** [comment]
Hi,
perfect :) When will be the next release ;) ?

**Comment by gameanimation3d** [comment]
Would it be possible to release these prebuilt libaries with headers for the last release?
this would solve my issues of building aliceVision and i think many other people aswell.

Aswell you devs don't have to answer that many issues on building the existing framework. over and over again.

**Comment by natowi** [comment]
@gameanimation3d You can take a look at my most recent (March 2020) build of the [AliceVision binaries](https://github.com/natowi/meshroom_external_plugins/releases/download/av-dev2020.0.1/alicevision2020.0.1Win64.zip)

>  this would solve my issues of building aliceVision and i think many other people aswell. Aswell you devs don't have to answer that many issues on building the existing framework. over and over again.

I agree, building alicevision is not fun. Auto-generated "dev-build" releases by travis would be really useful (also for the alicevision plugins)

**Comment by natowi** [comment]
@gameanimation3d I hope this is what you were looking for:

From now on, a windows snapshot build for every commit can be downloaded from the [appveyor build artifacts tab](https://ci.appveyor.com/project/AliceVision/alicevision/build/artifacts).

This includes .exe, .dll, .lib, .exp files.

Note: Do not use snapshots if you need a stable build.
Snapshot builds are for developers and testers and should be considered unstable.

https://github.com/alicevision/AliceVision/pull/753
