### ISSUE TITLE
CameraInit failed with error code -11

### ISSUE THREAD

**Issue by FunWithFlaggs** [alicevision/AliceVision#703]
OS: OSX 10.13.6
Clang 10 CUDA 10

Downloaded sources as described in Readme, then configured and compiled with the solutions that i added here https://github.com/ryanfb/homebrew-alicevision/issues/5?_pjax=%23js-repo-pjax-container# and https://github.com/ryanfb/homebrew-alicevision/issues/6

When i now get Meshroom as described in the Readme and run it using `PYTHONPATH=$PWD python3 meshroom/ui` and drag some images in there, i get the following error (attached as .log)

[err.log](https://github.com/alicevision/AliceVision/files/3736330/err.log)

Are there any other things that i can add to help solving this?

**Comment by simogasp** [comment]
```
RuntimeError: CameraInit failed with error code -11. Command was: "aliceVision_cameraInit  --sensorDatabase "" --defaultFieldOfView 45.0 --groupCa....
```
It seems like you didn't set the database file: https://github.com/alicevision/meshroom/blob/f676b400a1e5735b5cd9d9623cae383584595186/INSTALL.md#alicevision
you need to set the env variable `ALICEVISION_SENSOR_DB=${ALICEVISION_INSTALL}/share/aliceVision/cameraSensors.db` 
and similarly `ALICEVISION_INSTALL` should point to the path where u installed alicevision

**Comment by simogasp** [comment]
I suggest to create a bash file `meshroom.sh` in the root of meshroom like this
```bash
export ALICEVISION_INSTALL=/path/to/alicevision/AliceVision/build/install
# if you need the plugins
export QML2_IMPORT_PATH=/path/to/qmlAlembic/build/install/qml:/path/to/QtAliceVision/build/install/qml:$QML2_IMPORT_PATH
export ALICEVISION_SENSOR_DB=${ALICEVISION_INSTALL}/share/aliceVision/cameraSensors.db
export LD_LIBRARY_PATH=/usr/lib/nvidia-384:/usr/local/cuda-8.0/lib64/:$LD_LIBRARY_PATH
export MESHROOMPATH=$PWD
PYTHONPATH=${MESHROOMPATH} PATH=$PATH:${ALICEVISION_INSTALL}/bin python ${MESHROOMPATH}/meshroom/ui $@
```
and then you just call
```bash
./meshroom.sh
```
or
```bash
./meshroom.sh --project yourproject.mg
```

**Comment by FunWithFlaggs** [comment]
Oh man thanks, the .db file was missing..
