### ISSUE TITLE
aliceVision_cameraInit doesn't support .png file?

### ISSUE THREAD

**Issue by AL9501** [alicevision/AliceVision#710]
### Problem

My cmd is aliceVision_cameraInit --imageFolder arg --s arg --o arg, imageFolder includes some .png file, the output is .png is not a valid folder or file path. Please help me, thank you.

**Comment by natowi** [comment]
You can use meshroom_photogrammetry.exe:

meshroom_photogrammetry.exe [-h] [--input FOLDER_OR_SFM]
                                   [--inputImages [IMAGES [IMAGES ...]]]
                                   [--pipeline MESHROOM_FILE]
                                   [--overrides SETTINGS] [--output FOLDER]
                                   [--cache FOLDER] [--save FILE]
                                   [--scale {-1,1,2,4,8,16}]
                                   [--toNode [NODE [NODE ...]]]
                                   [--forceStatus] [--forceCompute]

**Comment by natowi** [comment]
Can you share your exact cli parameters?

This might be useful for you:
http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/

**Comment by AL9501** [comment]
> Can you share your exact cli parameters?
> 
> This might be useful for you:
> http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/
![6ZTIT )KMBCCJ`%0ON`1@UV](https://user-images.githubusercontent.com/30255992/68263197-5def5000-0080-11ea-953c-d11750199c4c.png)
This is my parameters, you can see that the output is .png is not a valid folder or file path.
![~HYS@X5JN6W17 _R`YO Y3K](https://user-images.githubusercontent.com/30255992/68263275-8d9e5800-0080-11ea-8867-de42a603d974.png)
This is my .png pictures.

**Comment by AL9501** [comment]
@natowi  I still can't solve this problem, can you help me? If I use .jpg file the cmdline can work, but .png file can not work.

**Comment by natowi** [comment]
I see, you use the camerainit.exe directly. 
Better use meshroom_compute.exe or meshroom_photogrammetry.exe this will load all plugins including support for different image formats.

**Comment by AL9501** [comment]
OK but I need use cameraInit.exe so I can't use .png file. Is it right? Is there any way to solve this?

**Comment by natowi** [comment]
What exactly are you trying to achieve by using cameraInit.exe only?

**Comment by AL9501** [comment]
I just want to do it step by step. I found that the input of cameraInit.exe is viewpoints.sfm in meshroom. It is not imagefolder or image file.
