### ISSUE TITLE
CMake issue: "INTERFACE_INCLUDE_DIRECTORIES property contains path"

### ISSUE THREAD

**Issue by gameanimation3d** [alicevision/AliceVision#712]
CMake Building issue: INTERFACE_INCLUDE_DIRECTORIES property contains path.. which is prefixed in the source directory

### Problem
I am trying to build AliceVision. With vcpkg.
On CMake Building i get the following error for all CMakeList files.
I followed carefully the installation instruction from vcpkg and aliceVision

All necessary Dependencies seem to be installed.

example:

> -- Configuring done
> CMake Error in src/aliceVision/image/CMakeLists.txt:
>   Target "aliceVision_image" INTERFACE_INCLUDE_DIRECTORIES property contains
>   path:
> 
>     "M:/Repo/GitRepos/aliceVisionCompile/AliceVision/vcpkg/installed/x64-windows/include"
> 
>   which is prefixed in the source directory.

I am calling via CMD:

> cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -A x64 -T host=x64

**Expected behavior:**  

**Actual behavior:**  

https://gist.github.com/gameanimation3d/f477cde1783660f2d807608b4d763c41

### Steps to Reproduce

1. [First Step]

2. [Second Step]
3. [and so on...]

### Versions

* AliceVision branch/version: Release Master (8c601db)
* OS: Windows 10, 64 bit
* C++ compiler: Visual Studio 2019 MSVC v142 | CMake 3.15.4

Would be amazing if somebody could help me

**Comment by simogasp** [comment]
Hi, this is a problem related to your set up.
You should not have dependencies that inside the same path as your source.
If I see well you have
```
M:\Repo\GitRepos\aliceVisionCompile\AliceVision
```
with the sources of AV
```
M:\Repo\GitRepos\aliceVisionCompile\AliceVision\build
```
for the build, and
```
M:/Repo/GitRepos/aliceVisionCompile/AliceVision/vcpkg/
```
for vpckg. You need to use a different path for vcpkg, like eg
```
M:/Repo/GitRepos/aliceVisionCompile/vcpkg/
```
so that the libraries are not in the same source tree as AV

**Comment by gameanimation3d** [comment]
Thank you very much the help
This resolved this issue.

But now through moving the VCPKG Root Folder the packages don't get found anymore.
Even after reinstalling vcpkg with, as written in the docu

>  vcpkg integrate install

Error:
> CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
> Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
> Call Stack (most recent call first):
> C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
> C:/Program Files/CMake/share/cmake-3.15/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
> src/cmake/FindOpenEXR.cmake:22 (find_package)
> src/CMakeLists.txt:285 (find_package)

I removed all packages from vcpkg and removed the folders buildtrees,packages and installed. And kept the downloads archives.
After reinstalling the corresponding packages nothing changed.

vcpkg list tell me that for triplet x64-windows everything is installed

CMD Output
https://gist.github.com/gameanimation3d/5cbd82d9350255c99a815bec4fd166f2

CMakeError File:
https://gist.github.com/gameanimation3d/5b72fa84634f741f92ae3792b9b96f34
CMake Output:
https://gist.github.com/gameanimation3d/83685585beed6b5aa90a20b3f834d971

**Comment by simogasp** [comment]
Did u change %VCPKG_ROOT% so it points to the new location?

**Comment by gameanimation3d** [comment]
Yes its pointing to the root of vcpkg repo folder. 

Folder structure:
aliceVisionCompile :
----AliceVision (AliceVIison repo Files)
----vcpkg (vcpkg repo files) 

pointing to: ..aliceVisionCompile\vcpkg\

On installation i couldn't use this variable on PS or CMD because it wasn't existing (syntaxerror always)

> cd <VCPKG_INSTALL_DIR>

i had to manually go to the folder and then set the variable. But this shouldn't make any problem?

Where does CMake get the path for vcpkg package folder to search for?

**Comment by simogasp** [comment]
Try to give the full path instead of using the env variable.

If you do 
```
echo %VCPKG_ROOT%
```
what do you get?
To set the env variable http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/

**Comment by simogasp** [comment]
As a further test you can add this line
```cmake
message(STATUS "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")
```
to the CMakeLists.txt of alicevision to print out the value that is used

**Comment by gameanimation3d** [comment]
Hey,
thank you very much for the answer.  It builded on minimum
The issue was solved by having no space between argument and value:
-DCMAKE_TOOLCHAIN_FILE= and M:\ ..
Aswell as passing not any env variable as variable. But using the fullpath.

> message(STATUS "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")

showed before that the variable was empty

**Comment by simogasp** [comment]
great!
consider closing the issue if everything is ok

**Comment by gameanimation3d** [comment]
Do you provide prebuilt Libaries for Popsift for Windows? to be included on building?

**Comment by gameanimation3d** [comment]
Are these Libaries important, because there are still missing:
- UncertaintyTE
- Sphinx
- Doxygen
- OpenGV
- MOSEK Header and Libary
- METIS

I am sorry if i constantily requesting your help. but i am using AliceVision currently as part of my Bachelor Thesis. And can't workaround anymore with Exe CLI Interface and need to call instead the C++ function directly.

I am still hoping you can provide prebuilt static libaries for include sometime https://github.com/alicevision/AliceVision/issues/701

**Comment by natowi** [comment]
They are optional:

https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

UncertaintyTE (Uncertainty computation)
Sphinx (documentation) (old)
Doxygen (code doc)
OpenGV (rig calibration and localization)
Mosek 5 (linear programming)
METIS (Serial program for partitioning)

**Comment by gameanimation3d** [comment]
Thanks  @natowi for pointing it out

**Comment by natowi** [comment]
@gameanimation3d Did you resolve your issues? Than you can close this.

BTW I found [this thesis](https://scholarworks.iupui.edu/handle/1805/19992), maybe it is interesting for you.

**Comment by gameanimation3d** [comment]
the issue was resolved, thank you 

> BTW I found this thesis, maybe it is interesting for you.

thanks, i will have a look ;)

i am closing now
