### ISSUE TITLE
Building a docker image with ubuntu 18 fails.

### ISSUE THREAD

**Issue by xylnao42** [alicevision/AliceVision#718]
### Problem
Building a docker image with CentOS 7 image succeeds, but building one with ubuntu 18 image fails.
**Expected behavior:**  
The building process ends normally.
**Actual behavior:**  
I got the following error message and the build process stops.
> checking if g++ supports -c -o file.o... [ 49%] No patch step for 'opencv'
> [ 84%] Built target geogram_num_3rdparty
> [ 50%] No update step for 'opencv'
> -- [download 62% complete]
> [ 11%] Built target Half
> [ 51%] Performing configure step for 'opencv'
> Scanning dependencies of target HalfTest
> [100%] Linking C executable pngvalid
> ESC[91mCMake Error: The source directory "/tmp/AliceVision_build/external" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> ESC[0mCMakeFiles/opencv.dir/build.make:111: recipe for target 'opencv-prefix/src/opencv-stamp/opencv-configure' failed
> ESC[91mmake[2]: *** [opencv-prefix/src/opencv-stamp/opencv-configure] Error 1
> ESC[0mESC[91mmake[1]: *** [CMakeFiles/opencv.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ESC[0mCMakeFiles/Makefile2:194: recipe for target 'CMakeFiles/opencv.dir/all' failed

[AliceVsion-build-ubuntu.log](https://github.com/alicevision/AliceVision/files/3907203/AliceVsion-build-ubuntu.log)

### Steps to Reproduce

1. `git clone https://github.com/alicevision/AliceVision.git --recursive`
2. `cd AliceVision`
3. `docker build --tag alicevision:ubuntu18.04-cuda9.2 -f Dockerfile_ubuntu .`

### Versions

* AliceVision branch/version: develop/HEAD
* OS: ubuntu 18.04.3
* CMake: cmake version 3.10.2

**Comment by KeoChi** [comment]
In CMakeLists.txt, changing "../${OPENCV_SRC_PATH}" to " /tmp/AliceVision_build/opencv"
ExternalProject_Add(${OPENCV_TARGET}
  DEPENDS opencv_contrib ${TBB_TARGET} ${ZLIB_TARGET} ${OPENEXR_TARGET} ${TIFF_TARGET} ${PNG_TARGET} ${JPEG_TARGET} ${LIBRAW_TARGET}
  # URL https://github.com/opencv/opencv/archive/4.2.0.zip
  # URL_MD5 b02b54115f1f99cb9e885d1e5988ff70
  URL https://github.com/opencv/opencv/archive/4.1.0.zip
  URL_MD5 5c5a9ce3519415b263d512e7f6a1e2af
  UPDATE_COMMAND ""
  BUILD_IN_SOURCE 0
  BUILD_ALWAYS 0
  SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/opencv
  BINARY_DIR ${BUILD_DIR}/opencv_build
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
  CONFIGURE_COMMAND ${CMAKE_COMMAND} ${CMAKE_CORE_BUILD_FLAGS} -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR> <SOURCE_DIR>
    -DOPENCV_EXTRA_MODULES_PATH=${CMAKE_CURRENT_BINARY_DIR}/opencv_contrib/modules
    ${ZLIB_CMAKE_FLAGS} ${TBB_CMAKE_FLAGS}
    ${TIFF_CMAKE_FLAGS} ${PNG_CMAKE_FLAGS} ${JPEG_CMAKE_FLAGS} ${LIBRAW_CMAKE_FLAGS}
    -DWITH_TBB=ON
    -DBUILD_opencv_python2=OFF
    -DBUILD_opencv_python3=OFF
    -DWITH_GTK_2_X=OFF
    -DWITH_V4L=OFF
    -DINSTALL_C_EXAMPLES=OFF
    -DINSTALL_PYTHON_EXAMPLES=OFF
    -DBUILD_EXAMPLES=OFF
    -DWITH_QT=OFF
    -DWITH_OPENGL=OFF
    -DWITH_VTK=OFF
    -DWITH_OPENEXR=OFF  # Build error on IlmBase includes without "OpenEXR/" prefix
    -DENABLE_PRECOMPILED_HEADERS=OFF
    -DBUILD_SHARED_LIBS=ON
    -DWITH_CUDA=OFF
    -DWITH_OPENCL=OFF
    -DBUILD_TESTS=OFF
    -DBUILD_LIST=core,improc,photo,objdetect,video,imgcodecs,videoio,features2d,xfeatures2d,version
    /tmp/AliceVision_build/opencv#../${OPENCV_SRC_PATH}
)

**Comment by simogasp** [comment]
it's better to replace it with `<SOURCE_DIR>` as it less specific, ie replace 
`../${OPENCV_SRC_PATH}` --> `<SOURCE_DIR>`

Please let us know if it works so we can fix it in the script

**Comment by xylnao42** [comment]
After [a recent commit](https://github.com/alicevision/AliceVision/commit/c28706ca2e7c5b49b8189f8d40eddf327b04a781) AliceVision requires a newer cmake than the Ubuntu 18.04 image installs.
> Step 12/16 : RUN cmake "${AV_DEV}" -DCMAKE_BUILD_TYPE=Release -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON -DAV_BUILD_LAPACK:BOOL=OFF -DAV_BUILD_SUITESPARSE:BOOL=OFF -DCMAKE_INSTALL_PREFIX="${AV_INSTALL}" -DALICEVISION_BUNDLE_PREFIX="${AV_BUNDLE}"
>  ---> Running in ff9ba2578f89
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.11 or higher is required.  You are running version 3.10.2
> 
> 
> -- Configuring incomplete, errors occurred!
> The command '/bin/sh -c cmake "${AV_DEV}" -DCMAKE_BUILD_TYPE=Release -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON -DAV_BUILD_LAPACK:BOOL=OFF -DAV_BUILD_SUITESPARSE:BOOL=OFF -DCMAKE_INSTALL_PREFIX="${AV_INSTALL}" -DALICEVISION_BUNDLE_PREFIX="${AV_BUNDLE}"' returned a non-zero code: 1

**Comment by simogasp** [comment]
the dockerfile may be not up to date.
you can remove cmake from the installed packages and after the `apt-get install` and install a more recent version
```docker
# Manually install cmake
WORKDIR /tmp/cmake
ENV CMAKE_VERSION=3.17
ENV CMAKE_VERSION_FULL=${CMAKE_VERSION}.2
RUN wget https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION_FULL}.tar.gz && \
    tar zxf cmake-${CMAKE_VERSION_FULL}.tar.gz && \
    cd cmake-${CMAKE_VERSION_FULL} && \
    ./bootstrap --prefix=/usr/local  -- -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_USE_OPENSSL:BOOL=ON && \
    make -j$(nproc) install && \
    cd /tmp && \
    rm -rf cmake
```

**Comment by simogasp** [comment]
and you need to add `libssl-dev` among the packages
