### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [alicevision/AliceVision#727]
### Problem error
AliceVision/src/software/convert/main_convertLDRToHDR.cpp:291:89: error: ambiguous overload for ‘operator<<’ (operand types are ‘boost::log::v2_mt_posix::basic_record_ostream<char>’ and ‘float [3]’)
  291 |     ALICEVISION_LOG_INFO("Offset between target source image and recovered from hdr = " << offset);
      |                                                                                         ^~ ~~~~~~
      |                                                                                            |
      |                                                                                            float [3]
AliceVision/src/aliceVision/system/Logger.hpp:30:42: note: in definition of macro ‘ALICEVISION_LOG’
   30 | #define ALICEVISION_LOG(MODE, a) MODE << a
      |                                                    ^

### Steps to Reproduce

cmake .. \\
-DALICEVISION_USE_CUDA=ON \\
              -DALICEVISION_BUILD_DOC=OFF \\
              -DCMAKE_INSTALL_PREFIX=/usr \\
              -DCMAKE_INSTALL_LIBDIR=lib \\
              -DCOINUTILS_INCLUDE_DIR_HINTS=/usr/include/coin \\
-DGEOGRAM_INSTALL_PREFIX=/usr \\
              -DEIGEN_INCLUDE_DIR=/usr/include/eigen3 \\
              -DEIGEN_INCLUDE_DIR_HINTS=/usr/include/eigen3 \\
              -DFLANN_INCLUDE_DIR_HINTS=/usr/include/flann \\
              -DLEMON_INCLUDE_DIR_HINTS=/usr/include/lemon \\
              -DCLP_INCLUDE_DIR_HINTS=/usr/include/coin \\
              -DOSI_INCLUDE_DIR_HINTS=/usr/include/coin \\
              -DCERES_DIR=/usr/include/ceres
    make -j \`nproc\`

### Versions

* AliceVision branch/version: https://github.com/alicevision/AliceVision.git  develop
* OS: linux
* C++ compiler: gcc 9

### Need 
    ALICEVISION_LOG_INFO("Offset between target source image and recovered from hdr = " << offset[0] << ", " << offset[1] << ", " << offset[2] << ";" );

**Comment by fabiencastan** [comment]
Thanks for the report.
Could you submit a PR?

**Comment by salfter** [comment]
I ran into the same problem building against Boost 1.72.0.  I think this should fix it:

[alicevision-2.2.0-boost-ambiguity-fix.patch.txt](https://github.com/alicevision/AliceVision/files/4229406/alicevision-2.2.0-boost-ambiguity-fix.patch.txt)

Now I need to deal with CUDA vs. gcc 9, but that's another matter.

**Comment by simogasp** [comment]
Is the problem solved?

**Comment by AlexandrParkhomenko** [comment]
`printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"`
version r5415.0a3ad0f09 **build ok**

**Comment by majioa** [comment]
how to fix it?

**Comment by fabiencastan** [comment]
@majioa This code has changed now, so what is your error message now?

**Comment by majioa** [comment]
im just trying to compile the release not a tot
