### ISSUE TITLE
so much errors for compiling this project! why?

### ISSUE THREAD

**Issue by csunking** [alicevision/AliceVision#728]
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
Force CMAKE_INSTALL_DO_STRIP in Release
//----------------------------------------
ALICEVISION_BUILD_DEPENDENCIES: OFF
ALICEVISION_BUILD_TESTS: OFF
AV_BUILD_CUDA: OFF
AV_BUILD_ZLIB: ON
AV_BUILD_TIFF: ON
AV_BUILD_JPEG: ON
AV_BUILD_PNG: ON
AV_BUILD_LIBRAW: ON
AV_BUILD_CCTAG: ON
AV_BUILD_POPSIFT: ON
AV_BUILD_OPENGV: ON
AV_BUILD_OPENCV: ON
AV_BUILD_LAPACK: ON
AV_BUILD_SUITESPARSE: ON
CMAKE_BUILD_TYPE: Release
DEPS_CMAKE_BUILD_TYPE: Release
CMAKE_INSTALL_LIBDIR: lib
CMAKE_INSTALL_PREFIX: C:/Program Files (x86)/aliceVision
CMAKE_INSTALL_RPATH: 
CMAKE_INSTALL_DO_STRIP: TRUE
//----------------------------------------
CMake version: 3.15
** ALICEVISION_BUILD_DOC: 'AUTO'
** ALICEVISION_USE_OPENMP: 'ON'
** ALICEVISION_USE_CCTAG: 'AUTO'
** ALICEVISION_USE_POPSIFT: 'AUTO'
** ALICEVISION_USE_OPENGV: 'AUTO'
** ALICEVISION_USE_ALEMBIC: 'AUTO'
** ALICEVISION_USE_UNCERTAINTYTE: 'AUTO'
** ALICEVISION_USE_CUDA: 'ON'
** ALICEVISION_USE_OPENCV: 'OFF'
Detected Host CPU: kaby-lake
Checking for C++11 compiler
Checking for C++11 compiler - available
OpenMP found.
CMake Error at src/CMakeLists.txt:259 (message):
  Failed to find Boost.

CMake Error at src/CMakeLists.txt:260 (message):

File OPENEXR_INCLUDE_PATH-NOTFOUND/OpenEXR/ImfMultiPartInputFile.h does not exist. Default to 1.6.1
CMake Error at D:/Pros/IDE/IDE Tools/cmake-3.15.0-rc1-win64-x64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: ILMBASE_INCLUDE_PATH OPENEXR_INCLUDE_PATH
  OPENEXR_IMATH_LIBRARY OPENEXR_ILMIMF_LIBRARY OPENEXR_IEX_LIBRARY
  OPENEXR_HALF_LIBRARY) (found version "1.6.1")
Call Stack (most recent call first):
  D:/Pros/IDE/IDE Tools/cmake-3.15.0-rc1-win64-x64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/FindOpenEXR.cmake:163 (find_package_handle_standard_args)
  src/CMakeLists.txt:283 (find_package)

Configuring incomplete, errors occurred!

**Comment by natowi** [comment]
> Failed to find Boost.
> OPENEXR_INCLUDE_PATH

You did not install or link all Dependencies. https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

**Comment by csunking** [comment]
i had compiled the ceres, boost, eigen, flann etc. before, and used the vcpkg manner for the residual libs,  but still  had trouble for this compiling.

**Comment by natowi** [comment]
You can try [this](https://github.com/natowi/mr_dev_build) (I did not test this recently)

**Comment by csunking** [comment]
I want to add new camera models for the meshroom, so not just the binaries I want to use. 
But hank you all the same.

**Comment by fabiencastan** [comment]
You mean a new camera model or declare new sensors in the sensordb?
The sensor db is a text file that you can edit in the release.

**Comment by natowi** [comment]
You can find the path and folder via meshroom gui:
![grafik](https://user-images.githubusercontent.com/8138537/72186367-656f0480-33f5-11ea-8824-db05ab71c242.png)

**Comment by csunking** [comment]
I desire to add an opencv camera type for my typical device as the following image showing. So,  I want to read the source and  understand the algorithms realeated deeply. 
![test](https://user-images.githubusercontent.com/6279897/72205855-8baea600-34c2-11ea-817e-e6a03fb7dbc5.png)

**Comment by csunking** [comment]
I had already finished createing .sln file for windows plateform. But, Still have so much errors for compling **aliceVision_geometry** and so on.

`1>E:\Projs\algs\meshroom\AliceVision\src\aliceVision/robustEstimation/randSampling.hpp(71): warning C4267: 'argument': conversion from 'size_t' to '_Ty', possible loss of data
1>        with
1>        [
1>            _Ty=int
1>        ]
1>E:\Projs\algs\meshroom\AliceVision\src\aliceVision/robustEstimation/randSampling.hpp(151): note: see reference to function template instantiation 'std::vector<size_t,std::allocator<_Ty>> aliceVision::robustEstimation::randSample<size_t>(IntT,IntT,IntT)' being compiled
1>        with
1>        [
1>            _Ty=size_t,
1>            IntT=size_t
1>        ]
1>e:\projs\algs\meshroom\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp(244): warning C4018: '<': signed/unsigned mismatch
1>e:\projs\algs\meshroom\alicevision\src\alicevision\geometry\rigidTransformation3D.hpp(242): note: while compiling class template member function 'void aliceVision::geometry::ACKernelAdaptor_PointsRegistrationSRT<SolverType,aliceVision::geometry::RTSSquaredResidualError,aliceVision::Mat4>::Errors(const Eigen::Matrix<double,4,4,0,4,4> &,std::vector<double,std::allocator<_Ty>> &) const'
1>        with
1>        [
1>            _Ty=double
1>        ]
1>E:\Projs\algs\meshroom\AliceVision\src\aliceVision/robustEstimation/ACRansac.hpp(216): note: see reference to function template instantiation 'void aliceVision::geometry::ACKernelAdaptor_PointsRegistrationSRT<SolverType,aliceVision::geometry::RTSSquaredResidualError,aliceVision::Mat4>::Errors(const Eigen::Matrix<double,4,4,0,4,4> &,std::vector<double,std::allocator<_Ty>> &) const' being compiled
1>        with
1>        [
1>            _Ty=double
1>        ]
1>E:\Projs\algs\meshroom\AliceVision\src\aliceVision\geometry\rigidTransformation3D.cpp(152): note: see reference to class template instantiation 'aliceVision::geometry::ACKernelAdaptor_PointsRegistrationSRT<SolverType,aliceVision::geometry::RTSSquaredResidualError,aliceVision::Mat4>' being compiled
1>D:\Pros\IDE\VS_LIBS\vcpkg\vcpkg\installed\x64-windows\include\boost/log/utility/formatting_ostream.hpp(929): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'T' (or there is no acceptable conversion)
1>        with
1>        [
1>            T=std::vector<size_t,std::allocator<size_t>>
1>        ]
1>C:\Program\Dev\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ostream(508): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)'

`

By the way,  I'm sorry for my english expression.
