### ISSUE TITLE
[question] build meshroom successfully, UI mesh and texture cannot be viewed

### ISSUE THREAD

**Issue by Samyang7** [alicevision/AliceVision#729]
### Problem
Hi I am doing the project related to 3-D image reconstruction and I am suggested to use Meshroom. I built the Alicevision which followed the instruction here https://github.com/alicevision/meshroom. I could successfully build the Alicevision and open the Meshroom UI from the command prompt. I could drag my image into the meshroom and successfully generate the sparse point after finishing the 'structure from motion' step. However, I could not get the mesh and texture result in the 3-D viewer after finishing the pipeline but I could get the file in my stored folder. I check the command prompt and i got:

[2020-01-10 19:02:54,485][WARNING] class Qt3DCore::QEntity *__cdecl Qt3DRender::Render::LoadSceneJob::tryLoadScene(class Qt3DRender::Render::Scene *,enum Qt3DRender::QSceneLoader::Status &,const class QStringList &,const class std::function<void __cdecl(class Qt3DRender::QSceneImporter *)> &) Found no suitable importer plugin for QUrl("file:///C:/Users/yan168/Desktop/sam/MeshroomCache/Texturing/a7581616189e513cf7923a0c2669a1ba04c34572/texturedMesh.obj")

My computer didn't have CUDA so I followed the step7 for building mesh from this website https://sketchfab.com/blogs/community/tutorial-meshroom-for-beginners. 

I tried to fix the problem by looking through issues that other people mentioned and I suspected that my problem was because qmlAlembic was not built fully. here is the issue that gave me the idea https://github.com/alicevision/qmlAlembic/issues/8. When I did the cmake .. step for qmlAlembic, i got ILMBASE_ROOT is undefined and generating done, configuring done. I didn't install the Qtalicevision plugin at the moment because I meet the issue when I build it also. I could find the path alicevision/cmake but i could not cmake successfully. The error is below. (i included my steps for setting the path also)
![Untitled picture1](https://user-images.githubusercontent.com/58925650/72228221-f2ce7680-35f8-11ea-9ac1-40ad84ee3e6f.png)

I check the file in the cmake folder but I could not find the AliceVisionConfig.cmake file but I did found it here "C:\Users\yan168\project\AliceVision\build\src\generated\AliceVisionConfig.cmake"

**Expected behavior:**  
in the 3-D viewer window, i can see the mesh and texture result

**Actual behavior:**  
I can only see the sparse point after the 'structure from motion'
![Untitled picture](https://user-images.githubusercontent.com/58925650/72228435-a5eb9f80-35fa-11ea-90a0-c2e281a98ad8.png)

### Steps to Reproduce

1. [First Step]
my directory 
![Untitled picture2](https://user-images.githubusercontent.com/58925650/72228340-dda61780-35f9-11ea-8a12-4480f893eab4.png)
![Untitled picture3](https://user-images.githubusercontent.com/58925650/72228360-04644e00-35fa-11ea-8081-cdf78e51a49c.png)

2. [Second Step]
step for building the alicevision

cd vcpkg
set VCPKG_ROOT=%cd%
vcpkg install ^
          boost-algorithm boost-accumulators boost-atomic boost-container boost-date-time boost-exception boost-filesystem boost-graph boost-log ^
          boost-program-options boost-property-tree boost-ptr-container boost-regex boost-serialization boost-system boost-test boost-thread boost-timer ^
          lz4 ^
          openexr ^
          openimageio[libraw] ^
          alembic ^
          geogram ^
          eigen3 ^
          ceres[suitesparse] ^
          cuda ^
          --triplet x64-windows

cd Alicevision
mkdir build && cd build 
# Windows: CUDA >= 10.0 + Visual 2017
cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64

double click the .sln file that generates
(fix the problem that is "offset << not ambiguous" by following this link https://github.com/alicevision/AliceVision/pull/709/commits/7d1f69aa5b5ab4982abadf0f13531d210f8f0f17)
![Untitled picture6](https://user-images.githubusercontent.com/58925650/72228851-6e7ef200-35fe-11ea-9a93-b94b2143e50d.png)

3. [and so on...]

### Versions

* AliceVision branch/version: I downloaded by this command in this website 
https://github.com/alicevision/AliceVision
git clone --recursive git://github.com/alicevision/AliceVision
2.20 i think
* OS: Windows 10
* C++ compiler: Visual Studio 2017 15.7.6 professional ( i am not too sure if it is the answer)

**Comment by Samyang7** [comment]
Also in my case, when I set the path for this one 
{ALICEVISION_ROOT}/src/aliceVision/sensorDB/cameraSensors.db
I cannot drag my image to meshroom, it said the image was corrupted

**Comment by Samyang7** [comment]
this is what my store folder looks like
![Untitled picture4](https://user-images.githubusercontent.com/58925650/72228571-f0b9e700-35fb-11ea-9b1b-fdaecdab6613.png)
![Untitled picture5](https://user-images.githubusercontent.com/58925650/72228573-f31c4100-35fb-11ea-9963-5e51deb79f78.png)

**Comment by natowi** [comment]
Workaround: you can copy/paste qmlAlembic  and qtalicevision from the prebuild binaries to your own build

**Comment by Samyang7** [comment]
I am not sure what I did is what you mean. I download the meshroom2019.2.0 64 bit and copy and replace my meshplug folder with qtplugins folder. right now, i could not even drag the image to meshroom. i can still use command prompt to open the UI but it didn't load the QTOIIO plugin anymore. below is the current error message.
![Untitled picture](https://user-images.githubusercontent.com/58925650/72302021-d562e080-36bc-11ea-8aaa-235f37106631.png)

**Comment by Samyang7** [comment]
I rebuild the alicevision and rebuild the qmlalembic and QtOIIO in my computer and used the qmlalembic and QtOIIO that i build. I can now drag the image and generate the sparse point but the mesh and texture problem still exist.
here is the error message i got when i double type the mesh in the meshroom pipline
![Untitled picture](https://user-images.githubusercontent.com/58925650/72305295-5a52f780-36c7-11ea-853f-902fa18cae74.png)

**Comment by natowi** [comment]
Meshroom folder should contain:
- _aliceVision_ folder
- (meshroom folder containing the python files and folders when starting meshroom gui from source)
- _qtPlugins_ folder with: _imageformats_ folder and _qml_ folder
_imageformats_ contains _QtOIIOPlugin_
_qml_ contains _AlembicEntity_ and _DepthMapEntity_
Missing plugins can be copied from the binary release as a workaround.
- meshroom.exe (or Meshroom.bat when starting meshroom gui from source)

**Comment by Samyang7** [comment]
sorry, I don't really understand 'lib folder with compiled meshroom GUI file' mean here. Do you mean that after i compiled the alicevision and then i need to start meshroom by typing 
set PYTHONPATH=%CD% && python meshroom/ui.
after then I will see a lib folder and move it under the meshroom folder?

**Comment by fabiencastan** [comment]
@Samyang7 I'm a bit lost in the thread what is the remaining problem, but to answer to the initial question:
To load the textured mesh in the 3D viewer, you need to have the following qt file in your installation:
`./lib/PySide2/Qt/plugins/sceneparsers/libassimpsceneimport.so`

**Comment by Samyang7** [comment]
the problem I had was that I cannot get the mesh and textured mesh in the 3-D viewer even I could get the sparse point result in the 3-D viewer. I was not sure the reason for that and I suspected something wrong with the qmlAlembic and Qtalicevision plugins since I could not build the Qtalicevision and got ' ILMBASE_ROOT is undefined ' when doing the cmake for qmlAlembic. 
I post the command prompt picture for The ' ILMBASE_ROOT is undefined ' and error that could not build Qtalicevision in my question.

another question is that
when I mentioned that I could open the UI in the command prompt and drag the image, at that time, I did not set the path for the Alicevision_sensor_db. After I set the path for Alicevision_sensor_db followed the instruction in install.mb, I could not drag the image and it said that the image was corrupted

**Comment by Samyang7** [comment]
@fabiencastan I am kind of new for set up environment.
I install the qt5.11.1 from this web https://download.qt.io/archive/qt/5.11/5.11.1/
I also did this command: pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/latest/ pyside2 --trusted-host download.qt.io
I did not see libassimpsceneimport.so in the location you mentioned.
should i do the ''pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/latest/ pyside2 --trusted-host download.qt.io" after i installed the Qt5.11.1?

**Comment by Samyang7** [comment]
@natowi Can you tell me which step for building the meshroom can I get these files: meshroom.exe, meshroom_compute.exe, meshroom_photogrammetry.exe, python35.dll (or Meshroom.bat when starting meshroom gui from source) and the lib folder you mentioned(lib folder with compiled meshroom gui files)

**Comment by natowi** [comment]
I recommended to copy the missing library (qmlAlembic) to the final folder as a quick fix.

>  I did not see libassimpsceneimport.so in the location you mentioned.

As Fabien said; https://github.com/alicevision/meshroom/issues/563#issuecomment-515405296

> Can you tell me which step for building the meshroom can I get these files

To build Meshroom navigate to downloaded source code:

set python PATH

set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

Install dependencies

pip install -r requirements.txt -r dev_requirements.txt --timeout 45

Build Meshroom UI

python setup.py build

the build folder contains the exe files and the lib folder

**Comment by Samyang7** [comment]
@natowi 
I did what you said and I got the error when I tried to launch the meshroom in the command prompt follow this command
set PYTHONPATH=%CD% && python meshroom/ui
the error message is below 
![Untitled picture](https://user-images.githubusercontent.com/58925650/72398977-dec17b00-3798-11ea-9a33-c700c846313f.png)

i also attached my current meshroom directory looks like:
![Untitled picture2](https://user-images.githubusercontent.com/58925650/72399026-0adcfc00-3799-11ea-97cc-0be0ac491dbd.png)

**Comment by Samyang7** [comment]
I solved the issue I mentioned, it is because my python version is not correct

**Comment by Samyang7** [comment]
@natowi @fabiencastan 
I make it work! 
thank you so much for your guys help!

**Comment by Samyang7** [comment]
@natowi 
I had another question for meshroom.
as I am almost new to programming, I didn't really understand how to enable the optional library by using the cmake optional. 

For example, as my computer is CUDA enable now, how can I do the ALICEVISION_USE_CUDA and ALICEVISION_USE_OPENMP using cmake?

Is that related to this command line when building the alicevision?
cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64

**Comment by simogasp** [comment]
> Is that related to this command line when building the alicevision?
> cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64

yes, you can append:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017" -A x64 -T host=x64  -DALICEVISION_USE_OPENMP:BOOL=ON -DALICEVISION_USE_CUDA:BOOL=ON
```

**Comment by Samyang7** [comment]
thank you @simogasp 
at the moment, I want to enable the PopSift (feature extraction on GPU). but after finishing building the alicevision. I could see that it mentioned that: Could NOT find PopSift (missing: PopSift_DIR).

what should I do get the PopSift install?

I checked the link below and I did not get the idea for building the popsift.
https://github.com/alicevision/popsift

**Comment by simogasp** [comment]
it's similar to building alicevision. Create a build directory where you run cmake. Inside that directory run, e.g. from the roor directory of popsift:
```
md build
cd build
cmake -G "Visual Studio 14 2015" -A x64 -T v140,host=x64 -DPopSift_BUILD_EXAMPLES:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -D ..
```
then compile and install in a preferred directory.

Then you need to re-run the cmake step in alicevision adding this option
```
-DPopSift_DIR:PATH=<path to popsift install>\lib\cmake\PopSift
```
and build again
