### ISSUE TITLE
StructureFromKnownPoses can't find any landmarks

### ISSUE THREAD

**Issue by cortwave** [alicevision/AliceVision#747]
I've tried to use `StructureFromKnownPoses` method for pipeline executing with known camera poses. For this purpose, I've got a gt poses from executing a standard meshroom pipeline on this dataset https://www.agisoft.com/datasets/doll.zip . Standard `StructureFromMotion` node reconstructed 78 of 81 images poses. I've taken this result (sfmData.sfm file from `StructureFromMotion` node output)  as gt poses.
 I removed all not restored images (without gt pose) from dataset (now it has only images with reconstructed camera poses). After that,  I wrote a meshroom node wrapper for `StructureFromKnownPoses` (nothing special, just needed parameters). In `CameraInit` node I added my gt poses (from sfmData.sfm) to cameraInit.sfm file. In `FeatureMatching` node I set `matchFromKnownCameraPoses` attribute to True (really I 've tried both variants). And finally, I replaced `StructureFromMotion` node with `StructureFromKnownPoses` node.

After the pipeline starts, all looks good till `StructureFromKnownPoses`. There are no landmarks found after that execution (in sfmData.sfm output file). It occurs in `Meshing` node:

``` 
[10:27:08.374202][info] Estimate space from SfM.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to estimate space from SfM: The space bounding box is too small.
```

 If I run with `matchFromKnownCameraPoses=False` in  `FeatureMatching` then `StructureFromKnownPoses` fails with segmentation fault.

My AliceVision version was built from sources (commit b05535ffa3e6f37f8a73bf6fa5900570b22bfd4c )
And Meshroom version also from sources (commit f676b400a1e5735b5cd9d9623cae383584595186)

Meshroom cache for pipeline execution attached (with `matchFromKnownCameraPoses=True` in  `FeatureMatching`) from start till `StructureFromKnownPoses` node. At the end of `StructureFromKnownPoses` node log you can see:
```
[10:26:03.637360][info] Structure estimation took (s): 36.92.
	- # landmarks found: 0
```
[cache.zip](https://github.com/alicevision/AliceVision/files/4254658/cache.zip)

**Comment by natowi** [comment]
Did you read through the discussions here https://github.com/alicevision/meshroom/issues/788 and here https://github.com/alicevision/meshroom/issues/807 ?

**Comment by Totorro35** [comment]
I suspect the commit e9476f27617aa36eb00c72fb829778ac8f9f3466 changed some functions in TracksBuilder like TracksBuilder::filter

**Comment by Totorro35** [comment]
I proposed a PR  #748 to fix the problem...

**Comment by cortwave** [comment]
@Totorro35 I pulled your PR to my repo and now it works! But I wonder what resulting model much worse than model obtained from a pipeline without known poses.

**Comment by cortwave** [comment]
This is result from standard pipeline
![image](https://user-images.githubusercontent.com/8936357/75384372-0d318a80-58ef-11ea-9095-796d5bc655e9.png)

And this is a result with known poses taken from standard pipeline
![image](https://user-images.githubusercontent.com/8936357/75384179-bdeb5a00-58ee-11ea-9f8f-f40760810114.png)

**Comment by natowi** [comment]
> I pulled your PR to my repo and now it works! But I surprised that resulting model much worse than model obtained from a pipeline without known poses.

StructureFromKonwnPoses triangulates the points only. I use this node to test the validity of modified sfm files only.

For high quality reconstructions, use the StructureFromMotion node with "Lock Scene Previously reconstructed" and "Force Lock of all Intrinsic camera"

**Comment by cortwave** [comment]
> > In FeatureMatching node I set matchFromKnownCameraPoses attribute to True
> 
> Ah, you used a slightly different method.
> 
> I inserted the sfm file directly in the StructureFromMotion node or StructureFromKnownPose

But anyway we should pass `matchesFolders` argument as required to any of these nodes
