### ISSUE TITLE
[Bug] SfmData Destructor

### ISSUE THREAD

**Issue by Totorro35** [alicevision/AliceVision#758]
### Problem
SfmData generates an error when calling the destructor. This is not a problem in Alice Software because they are called directly in Main function. But if SfmData is used in another scope, a segmentation fault appears at the destruction. This Exception occured in the function handmade_aligned_free in Eigen/Core/util/Memory.h

**Expected behavior:**
Successful end of program

**Actual behavior:** 
`Segmentation fault (core dumped)`

### Steps to Reproduce
Example of Main Program :
```
#include <aliceVision/sfmData/SfMData.hpp>
#include <aliceVision/sfmDataIO/sfmDataIO.hpp>

namespace av = aliceVision;

int main(int argc, char const *argv[])
{
    if ( argc < 1 )
        return 1;

    av::sfmData::SfMData sfmData;
    if (!av::sfmDataIO::Load(sfmData, argv[1], av::sfmDataIO::ESfMData(av::sfmDataIO::VIEWS | av::sfmDataIO::INTRINSICS)))
    {
        std::cout<<"The input SfMData file '" << argv[1] << "' cannot be read.";
        return 1;
    }
    std::cout<<"The SfmData file loaded"<<std::endl;

    return 0;
}
```

Output Log : 
```
[dock@0c0abbb427ac tests]$ ./core_tests_3 /workspaces/3DML_Pipeline/CORE3DML/core3dml/tests/dataTest/test.sfm 
The SfmData file loaded
Segmentation fault (core dumped)
[dock@0c0abbb427ac tests]$ 
```

### Versions

* AliceVision branch/version: #748 
* OS: Centos7
* C++ compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39)

**Comment by simogasp** [comment]
It's true that we should add an explicit default destructor for the class, but still, all the member objects  (and there are no raw pointers) should be destroyed automatically AFAIK.
Can you share your sfm file so we can test?
Thanks!

**Comment by Totorro35** [comment]
We can test with this file [cameraInit.txt](https://github.com/alicevision/AliceVision/files/4358574/cameraInit.txt) but but all SfM file I tested have the same error.

**Comment by simogasp** [comment]
I cannot reproduce it on my system (Ubuntu 18.04 gcc 7.5.0-3ubuntu1-18.04), it ends correctly.
It could be something related to the version of gcc but we are using a similar version (gcc (Ubuntu 4.8.4-2ubuntu1-14.04.3) 4.8.4) for the CI on Travis and the tests do not fail (although they are not exhaustive). (see https://travis-ci.org/github/alicevision/AliceVision/jobs/664483525#L29)

Can you run the tests just to see if they fail?

Also, try to add ` ~sfmData() = default` to the `sfmData` class and see if it solves it.

**Comment by Totorro35** [comment]
The same exception is obtained by using an explicit destructor. I saw that the error only happens when using Alice in 3rd parts.

I've activated the tests on Alice `-DALICEVISION_BUILD_TESTS=ON` but no tests were found.
```
Running tests...
Test project /workspaces/3DML_Pipeline/AliceVision/build
No tests were found!!!
```

**Comment by simogasp** [comment]
for the tests you need to re-run cmake with `-DALICEVISION_BUILD_TESTS:BOOL=ON` and rebuild, and then `make test`

I tried the same in a 3rd party configuration and still it works ok for me. Here is my piece of cmake:
```cmake
cmake_minimum_required(VERSION 3.14)

project(testAV3rd)

set(CMAKE_CXX_STANDARD 11)

set(BUILD_SHARED_LIBS ON)

find_package(AliceVision CONFIG REQUIRED)
message(STATUS "Found AliceVision : ${AliceVision_FOUND}")
message(STATUS "Found AliceVision version: ${AliceVision_VERSION}")

add_executable(testSfm testSfm.cpp)
target_link_libraries(testSfm PUBLIC aliceVision_sfmData aliceVision_sfmDataIO)
```
and `testSfm.cpp` is the piece of code you posted earlier.

The only thing that I can guess, in a 3rd party configuration, is that there is a library version mismatch, between the AV dependencies used to build and those found in the at runtime when you execute the sample.

* can you `ldd testSfm` (or whatever you named the binary) and check if the long list of libs are those that you used to build AV (or are from the place where you have the AV binaries if you download the pre-built version)?

* if u build AV yourself (kudos!) did u also installed or are u using the in-tree build?

**Comment by Totorro35** [comment]
Sorry for the response time.

I build AV myself but the last modifications have solved the problems. I don't understand where is the bug but now, it works

Thx for your time

**Comment by simogasp** [comment]
Can I ask which modifications exactly?

**Comment by simogasp** [comment]
possibly related to #766 and the propagation of eigen flags

**Comment by Totorro35** [comment]
It's between #743 and #766 but I didn't look for it specifically

**Comment by simogasp** [comment]
ok thanks, it's very likely related to #766 and the eigen flag that was not propagated when used as third party. Still strange that it worked on my side...
