### ISSUE TITLE
Fatal error C1001 (Internal compiler error) when compiling with CUDA 10 and VS 2019

### ISSUE THREAD

**Issue by EwoutH** [alicevision/AliceVision#778]
When updating the AppVeyor configuration an error popped up in the compile log:
```
 C:\projects\alicevision\src\aliceVision\matching\kvld\algorithm.h(122): fatal error C1001: Internal compiler error. [C:\projects\alicevision\build\src\aliceVision\matching\kvld\aliceVision_kvld.vcxproj]
   (compiler file 'd:\agent\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 182)
    To work around this problem, try simplifying or changing the program near the locations listed above.
   If possible please provide a repro here: https://developercommunity.visualstudio.com
   Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
     CL!CloseTypeServerPDB()+0xa5b20
     CL!CloseTypeServerPDB()+0xa5b20
     CL!CloseTypeServerPDB()+0xa5863
     CL!CloseTypeServerPDB()+0xa5476
     CL!CloseTypeServerPDB()+0xa52eb
     CL!CloseTypeServerPDB()+0xa546a
 cl : command line error D8040: error creating or communicating with child process [C:\projects\alicevision\build\src\aliceVision\matching\kvld\aliceVision_kvld.vcxproj]
```

Here the [AppVeyor configuration used](https://github.com/EwoutH/AliceVision/blob/AppVeyor-Cuda10/appveyor.yml) and the [run itself](https://ci.appveyor.com/project/AliceVision/alicevision/builds/32559120).

Blocks #776.

**Comment by fabiencastan** [comment]
You can try to remove the global const variable `PI_`.
```
#include <boost/math/constants/constants.hpp>
using namespace boost::math;

...
  angle += constants::pi<double>();
...
```

**Comment by EwoutH** [comment]
Thanks for the suggestion. Unfortunately I couldn't get it to work, could you take a look at it? See [this run](https://ci.appveyor.com/project/EwoutH/alicevision/builds/32824504) on [this branch](https://github.com/EwoutH/AliceVision/commits/patch-3).

**Comment by julianrendell** [comment]
@EwoutH - I have a hack (https://github.com/alicevision/AliceVision/compare/develop...julianrendell:vs2019-hacks?expand=1) that has let me build beyond this point (92% and still going...) It also has a fix to work with latest cctags. This is most definitely not a fix; I just brute force copied the code into the two places where it was being called, and I think I've also pushed a function from the .h -> .cpp. Not 100% sure if this last piece is needed, but it's compiling, I'm not a C++ expert, and I'm short on time :-)

I'm new to building meshroom; and rusty re building on Windows. My notes for what I've done so far: https://gist.github.com/julianrendell/da6372201234d943d3e4f77e43674fd2 - in case they're useful to you.

@fabiencastan - I think it has something to do with the arguments being references. Not really sure, going on some vague pattern recognition from reading random google searches for this internal compiler error.
