### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by skinkie** [alicevision/AliceVision#787]
I am probably missing something. What makes this configuration incomplete?
[CMakeOutput.log](https://github.com/alicevision/AliceVision/files/4605975/CMakeOutput.log)
[alicevision-cmake.log](https://github.com/alicevision/AliceVision/files/4605976/alicevision-cmake.log)

**Comment by simogasp** [comment]
can you try to surround the input variable with `"` in `src/cmake/FindOpenEXR.cmake` line 66 and all the other lines that generate the same error.
For [line 66](https://github.com/alicevision/AliceVision/blob/develop/src/cmake/FindOpenEXR.cmake#L66) it would look like this:
```cmake
string (REGEX MATCHALL "[0-9]+[.0-9]+" OPENEXR_VERSION "${TMP}")
```
It seems to be a problem when the input is empty
https://gitlab.kitware.com/cmake/cmake/issues/18737

**Comment by skinkie** [comment]
Adding "{$TMP}" seems to do the trick.
