### ISSUE TITLE
added 2 cameras

### ISSUE THREAD

**Issue by cyberbob00** [alicevision/AliceVision#789]
I added the sensor data of 2 cameras to _cameraSensors.db_: 

1st camera: Samsung S10e:

    samsung;SM-G970F;5.65;digicamdb

2nd camera: DJI Mavic 2 Pro:

    Hasselblad;L1D-20c;15.86;digicamdb

**Comment by natowi** [comment]
Thank you

**Comment by natowi** [comment]
@cyberbob00 where did you get the value 15.86 from?
We already have the model in the DB:
Hasselblad;Hasselblad L1D-20c;13.2;usercontribution
