### ISSUE TITLE
Build for Win using VS2019 results in illegal /bigobj being added to rc parameters

### ISSUE THREAD

**Issue by julianrendell** [alicevision/AliceVision#795]
With some hacks (see https://gist.github.com/julianrendell/da6372201234d943d3e4f77e43674fd2) I've got AliceVision building with VS2019 on Windows... but `cmake` breaks and I have to do some manual fixes to the generated build files.

I use: 
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=%TCF% -DCMAKE_PREFIX_PATH=%PREFIX% -DVCPKG_TARGET_TRIPLET=x64-windows -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%INSTALL% -DCMAKE_BUILD_TYPE=Release -DPopSift_DIR:PATH=D:\Meshroom_Dev\popsift\lib\cmake\PopSift -DALICEVISION_USE_OPENCV=ON -DOpenCV_DIR:PATH=D:\Users\MakeItZone\Documents\vcpkg\buildtrees\opencv4\x64-windows-rel -DOPENGV_DIR:PATH=D:\Meshroom_Dev\opengv -DCCTag_DIR:PATH=D:\Meshroom_Dev\cctag\lib\cmake\CCTag
```

(cmake version is 3.17.)

And if I try to compile (`nmake install`) I will get error `fatal error RC1106: invalid option: /bigobj
NMAKE : fatal error U1077: 'C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe' : return code '0x1'`

Work around is to search and replace for `RC_FLAGS = -DWIN32   /bigobj` in files in `build\**\flags.make` and replace with `RC_FLAGS = -DWIN32`.

And then `nmake install` completes.

I've tried looking for where RC_FLAGS is defined, but I haven't found it yet, and don't know cmake.

Any pointers as to where/how RC_FLAGS is defined?

**Comment by simogasp** [comment]
just to test, can you replace in src/CMakelists:121
```cmake
add_compile_options(/bigobj)
```
instead of add_definitions
I think RC_FLAGS is an NMAKE internal variable generated by cmake

**Comment by julianrendell** [comment]
That worked great- thanks!

I've submitted a pull request: #796 .
