### ISSUE TITLE
Release 2.2.0 incrementalSFM Crash

### ISSUE THREAD

**Issue by Jiucao** [alicevision/AliceVision#812]
[av_structure_from_motion_errorlog.txt](https://github.com/alicevision/AliceVision/files/4776853/av_structure_from_motion_errorlog.txt)

[av_structure_from_motion_errorlog.txt](https://github.com/alicevision/AliceVision/files/4776852/av_structure_from_motion_errorlog.txt)

Crash every time

**Comment by natowi** [comment]
You probably have special characters in your path that are not supported. Change the folder name.

https://github.com/alicevision/meshroom/issues/396

If this does not work, clear your project folder cache and reboot.
https://github.com/alicevision/meshroom/issues/201

**Comment by Jiucao** [comment]
I am useing alicevision inside houdini, the sop version no problem,but problem is , i move alicevision to PDG network,and everytime i run step of 05_Structure_from_Motion and 06_Prepare_Dense_Scene,
the Process will crash

**Structure_from_Motion error log said :**No valid initial pair found automatically.

**Prepare_Dense_Scene error log said:** HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5F.c line 370 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5Fint.c line 826 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'D:\AV_Cache\3D_Scans_PDG\scan_test4\05_StructureFromMotion\sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file


I think problem is step 5 Structure_from_Motion did genarate any think, or i should said it didnt work

**Comment by Jiucao** [comment]
![QQ截图20200615121705](https://user-images.githubusercontent.com/33847787/84617642-3d368500-af02-11ea-8f30-9793a1a236f8.png)

**Comment by natowi** [comment]
You you have Chinese characters in your image file name? Do a test run with [this dataset](https://github.com/alicevision/dataset_monstree) - does it work?

**Comment by Jiucao** [comment]
Now i knew why crash,beacuse my paramter value not that good, so Process will crash, if i can set right value for parameter, i will work. but question is :this is not that great, i cant found my problem dirctly, i must try diffrent value for my mult scans in pdg,this is wrong way,riht?

I choose PDG is because is can auto genarate 3Dmodel,and i dont wanna test every parameter value until i found a good balance.

or if error log can suggest me what parameter is wrong , i think it will be helps

BTW:i didnt use  Chinese characters in my image file name
