### ISSUE TITLE
Cmake GUI configuration error

### ISSUE THREAD

**Issue by kishooo** [alicevision/AliceVision#813]
when i click on configure it send me an error and it says "Error in configuration process, project files may be invalid "

**Comment by natowi** [comment]
This is not enough information to help you.

**Comment by kishooo** [comment]
i followed the steps to build AliceVision and this error happened

**Comment by natowi** [comment]
You can download a recent windows develop build [here](https://ci.appveyor.com/api/buildjobs/sg400f7j3o5iremj/artifacts/build%2FalicevisionWin64snapshot-f08d3c5529c4bdf313a039100f2452afea0b093a.zip)

You best use vcpkg to build a sln vor VS so you get all the dependencies.
