### ISSUE TITLE
build/src/doc missing?

### ISSUE THREAD

**Issue by jaggzh** [alicevision/AliceVision#816]
```-- Installing: /usr/local/include/aliceVision_dependencies/flann/src/cpp/flann/config.h
-- Installing: /usr/local/include/aliceVision_dependencies/flann/src/cpp/flann/flann.h
-- Installing: /usr/local/include/aliceVision_dependencies/flann/cmake
CMake Error at src/cmake_install.cmake:45 (file):
  file INSTALL cannot find "/home/jaggz/tmp/alicevision-build/src/doc".
Call Stack (most recent call first):
  cmake_install.cmake:51 (include)
```

**Comment by simogasp** [comment]
there is an error in the cmake concerning the doxygen creation.
You can either disable the documentation by passing `-DALICEVISION_BUILD_DOC:BOOL=OFF` or modify this line https://github.com/alicevision/AliceVision/blob/develop/src/CMakeLists.txt#L882 with
```cmake
add_custom_target( doc_doxygen ALL
```

**Comment by jaggzh** [comment]
Thank you.  :)
(I just mkdir'ed src/doc and that worked).  It's addressed in your referenced blob, so we can close?

**Comment by simogasp** [comment]
no please let it open, someone is going to fix it, then we can close it
