### ISSUE TITLE
Faling rules to find Eigen/Eigen (v3)?

### ISSUE THREAD

**Issue by jaggzh** [alicevision/AliceVision#817]
I don't know how to get AliceVision to build eigen itself, so I built and installed it (Eigen3)
...AliceVision isn't finding it.

I believe the issue is POSSIBLY cmake file naming conventions.

https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#user-content-building-the-project-using-external-dependencies

In this page we (or you, depending on your outlook) state: *"CMAKE_MODULE_PATH .. pointing at the <EigenInstallDir>/share/cmake/Modules/ directory of the Eigen installation, in which **Eigen-config.cmake or FindEigen3.cmake** can be found..."*

Now, apparently the name Eigen-config MIGHT be wrong anyway.  "<Module>Config.cmake" is possibly the proper convention.  See the issue discussed here: https://gitlab.com/libeigen/eigen/-/issues/1219

In any case, my fresh Eigen install doesn't provide the FindEigen3.cmake, but it does provide an Eigen3Config:

```
/usr/local/share/eigen3/cmake/Eigen3ConfigVersion.cmake
/usr/local/share/eigen3/cmake/Eigen3Config.cmake
/usr/local/share/eigen3/cmake/UseEigen3.cmake
/usr/local/share/eigen3/cmake/Eigen3Targets.cmake
```
It also, of course, provided all its headers, which my install placed here:
```
/usr/local/include/eigen3/unsupported/
/usr/local/include/eigen3/Eigen/
```

**Comment by natowi** [comment]
I´m using vcpkg (as described in the install.md) to avoid issues like this. If you just want to try a more recent AliceVision version, you can download it [here](https://ci.appveyor.com/api/buildjobs/v3eehracp8ex4ybp/artifacts/build%2FalicevisionWin64snapshot-.zip)

**Comment by jaggzh** [comment]
> I´m using vcpkg (as described in the install.md) to avoid issues like this. If you just want to try a more recent AliceVision version, you can download it [here](https://ci.appveyor.com/api/buildjobs/v3eehracp8ex4ybp/artifacts/build%2FalicevisionWin64snapshot-.zip)

I'm using a fresh git pull.  My options were to copy Eigen's FindEigen3.cmake by hand (which for some reason might be wrong) -- so instead I just set an env var CPLUS_INCLUDE_PATH=/usr/local/include/eigen3
(...until we somehow resolve this issue.)

**Comment by simogasp** [comment]
the doc is outdated (and wrong). we switched to the modern cmake way to use eigen (do not use FindEigen3).
So you can pass `-DEigen3_DIR:PATH=/usr/local/share/eigen3/cmake/, that should do it

**Comment by natowi** [comment]
> the doc is outdated

I was just checking on this

**Comment by jaggzh** [comment]
I'm actually still having issues with this. I installed eigen and ceres myself, and there was some version conflict there. (ceres's own files had a version mismatch between 3.3.4 and 3.3.7 or something) -- AliceVision detected the conflict during cmake.
I'm fiddling with the -D options in AliceVision right now, just to get it to not show a blank EIGEN:, but haven't gotten it to work yet.

This is my current cmake setup script:
`mkdir src/doc
export CPLUS_INCLUDE_PATH=/usr/local/include/eigen3

cmake -DEigen3_DIR:PATH="$CPLUS_INCLUDE_PATH" -DALICEVISION_USE_ALEMBIC=ON -DCMAKE_BUILD_TYPE=Release . ../AliceVision

# References:
# CMakeLists.txt:set(EIGEN_CMAKE_FLAGS ${EIGEN_DISABLE_ALIGN_FLAGS} -DEigen3_DIR:PATH=${CMAKE_INSTALL_PREFIX}/share/eigen3/cmake -DEIGEN3_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include/eigen3 -DEIGEN_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include/eigen3 -DEigen_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include/eigen3)
#/usr/local/share/eigen3/cmake/
`
