### ISSUE TITLE
Stable Meshroom-2019.2.0 wants plain AliceVision binaries, but we install -version'ed files

### ISSUE THREAD

**Issue by jaggzh** [alicevision/AliceVision#818]
So, Meshroom is looking for, for example, aliceVision_cameraInit, but my fresh build of AliceVision creates binaries like aliceVision_cameraInit-2.0

I'm not sure if this is intended behavior or not, and I should focus my attention on getting the newer Meshroom (from git) to run, or if there's a cmake option to install non-version'ed names (or symlinks)

Here's a subset of the files installed to /usr/local/bin:
```
aliceVision_panoramaExternalInfo-2.0
aliceVision_panoramaWarping-1.0
aliceVision_prepareDenseScene-2.0
aliceVision_rigCalibration-1.0
aliceVision_rigLocalization-1.0
aliceVision_texturing-3.0
aliceVision_utils_fisheyeProjection-1.0
aliceVision_utils_frustumFiltering-1.0
```

**Comment by natowi** [comment]
You can not mix different Alicevsion and Meshroom versions. Use the stable binaries or source code provided with the 2019.2 release. The next stable release will be coming soon.

**Comment by jaggzh** [comment]
Thank you so much for your help.
I'm using fresh git checkouts of AliceVision and Meshroom, by the way.
Nevertheless, I'm having a hard time finding links to the stable AliceVision build(s).  Can we update the website with those links, and possibly the README.md as well?

**Comment by natowi** [comment]
https://github.com/alicevision/AliceVision/releases/tag/v2.2.0
https://github.com/alicevision/meshroom/releases/tag/v2019.2.0
