### ISSUE TITLE
 Failed to find OpenImageIO

### ISSUE THREAD

**Issue by smpotdar** [alicevision/AliceVision#822]
> CMake Error at src/cmake/FindOpenImageIO.cmake:28 (message):
>   Failed to find OpenImageIO - Could not find OpenImageIO include directory,
>   set OPENIMAGEIO_INCLUDE_DIR to directory containing OpenImageIO/imageio.h
> Call Stack (most recent call first):
>   src/cmake/FindOpenImageIO.cmake:90 (openimageio_report_not_found)
>   src/CMakeLists.txt:306 (find_package)
> 

Hi! I am getting the above error. I installed openimageio using homebrew and I set  environment variable OPENIMAGEIO_INCLUDE_DIR to the directory which contains "OpenImageIO/imageio.h". 

The directory in my case is: 
OPENIMAGEIO_INCLUDE_DIR="/home/linuxbrew/.linuxbrew/Cellar/openimageio/2.1.16/include/"

Can anyone suggest what I might be doing wrong?

**Comment by SoninnM** [comment]
I met the same problem,how did you solve it?
