### ISSUE TITLE
reduce computation time by making in memory operation [type:question]

### ISSUE THREAD

**Issue by raphael2692** [alicevision/AliceVision#827]
Hello, 

I was wondering whether it would be possible to reduce computation time between nodes by replacing I/O operations with in-memory ones. I noticed that with my dataset the overall computation uses little memory (both GPU and RAM).

So, before venturing into trying to make some actual changes to the code, is this operation possible? Would you recommend it in my circumstances? (necessity to speed-up, low memory usage with actual build).

Thanks

**Comment by fabiencastan** [comment]
Hi,
It would be possible to keep everything in memory only on very small datasets. It is possible to create a new main with all the pipeline in one binary, but I'm not sure that the most important optimization to do. If you are on linux, you may have an idea of the impact, by putting the MeshroomCache in tempfs.

If you are interested in contributing, we have many ideas of optimizations to do but limited ressources ;)
We can setup a confcall to discuss about it if you want.
Best,

**Comment by raphael2692** [comment]
Hi @fabiencastan , thanks for your reply. My teammates and I would really like to share some ideas about it. Let me know how can we reach to you and help setting the call.

**Comment by fabiencastan** [comment]
You can reach me at fabien.castan@mikrosimage.com.
