### ISSUE TITLE
Export with textures instead of vertex colors/paint

### ISSUE THREAD

**Issue by TheShubham99** [alicevision/AliceVision#830]
Is there any way to export a 3d model with colors but without vertex colors?  
By using textures or something like that ? 🤔

**Comment by fabiencastan** [comment]
There is a texturing step to create a textured mesh. It's in the default pipeline if you look in Meshroom.

**Comment by TheShubham99** [comment]
Thanks for the help but could you share any resource/blog/tutorial for that?
I am using the command line to execute the task. Also, I am using the `texturing` stage but the final products still contains vertex colors.

**Log-**

```
[11/12] Texturing
 - commandLine: aliceVision_texturing  --input "/tmp/MeshroomCache/Meshing/7d00d35835d149dddd0dfd2019ce90ab6826f7af/densePointCloud.abc" --imagesFolder "/tmp/MeshroomCache/PrepareDenseScene/cb3d36fbb38d4f440d5e3f05d32d9a9f1ba2b86c" --inputMesh "/tmp/MeshroomCache/MeshFiltering/54017f4540c63730ef9c9743a8e847c0bcd5ecd5/mesh.obj" --textureSide 8192 --downscale 1 --outputTextureFileType png --unwrapMethod Basic --useUDIM True --fillHoles False --padding 5 --correctEV False --useScore True --processColorspace sRGB --multiBandDownscale 4 --multiBandNbContrib 1 5 10 0 --bestScoreThreshold 0.1 --angleHardThreshold 90.0 --forceVisibleByAllVertices False --flipNormals False --visibilityRemappingMethod PullPush --verboseLevel info --output "/tmp/MeshroomCache/Texturing/f937b20c659cb9a2e1c08c3e17a466f41a6ad5a1" 
 - logFile: /tmp/MeshroomCache/Texturing/f937b20c659cb9a2e1c08c3e17a466f41a6ad5a1/log
 - elapsed time: 0:00:26.649837
 ```
 
I wish to build a file that can be converted to .glb/gltf without having any vertex colors. 
The generated model is failing the test at - https://arvr.google.com/scene-viewer-preview

It gives an error saying - 
``` 
[Error] The glTF contains a vertex color, which is not supported by the Scene Viewer specification.
```

**Comment by fabiencastan** [comment]
Ensure that `colorizeOutput` is disabled on the Meshing step.
