### ISSUE TITLE
.clang-format file seems to be inconsistent with the code.

### ISSUE THREAD

**Issue by saedrna** [alicevision/AliceVision#833]
It seems that the .clang-format file in the root directory is inconsistent with most of the format of the code. Notably,

- The indent is 2 instead of 4 in .clang-format
- The spaces before and after braces are different
- Pointer alignment is also different

**Comment by simogasp** [comment]
yes most of the code is not consistent with that because it has been added later.
that style is intended to be used with new code that is added. One day we should apply it to the whole codebase.

**Comment by saedrna** [comment]
Thanks for the clarification!
