### ISSUE TITLE
ceres-solver causes running error

### ISSUE THREAD

**Issue by jsjtczh** [alicevision/AliceVision#834]
When I run aliceVision_globalSfM, I met this error:

*** Error in `/home/Projects/AliceVision/build/Linux-x86_64/aliceVision_globalSfM': double free or corruption (out): 0x00000000045d2400 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x814f9)[0x7f425551b4f9]
/home//local/lib64/libceres.so.1(_ZN5ceres8internal27FindInterpolatingPolynomialERKSt6vectorINS0_14FunctionSampleESaIS2_EE+0x368)[0x7f425a400788]
/home/local/lib64/libceres.so.1(_ZN5ceres8internal31MinimizeInterpolatingPolynomialERKSt6vectorINS0_14FunctionSampleESaIS2_EEddPdS7_+0x2e)[0x7f425a4020be]
/home/local/lib64/libceres.so.1(_ZNK5ceres8internal10LineSearch41InterpolatingPolynomialMinimizingStepSizeERKNS_27LineSearchInterpolationTypeERKNS0_14FunctionSampleES7_S7_dd+0x466)[0x7f425a3c9346]
/home/local/lib64/libceres.so.1(_ZNK5ceres8internal16ArmijoLineSearch8DoSearchEdddPNS0_10LineSearch7SummaryE+0x502)[0x7f425a3cad02]

I found similar issue https://github.com/openMVG/openMVG/issues/1403, which said it's caused by the version of Eigen. In my case, ceres-solver and AliceVision use the same Eigen. I also tried ceres-solver 1.4, but the error still exists.

**Comment by fabiencastan** [comment]
Sorry for the late answer.
See EIGEN_DISABLE_ALIGN_FLAGS here https://github.com/alicevision/AliceVision/blob/develop/CMakeLists.txt#L183.
The same flags should be set on all libraries using eigen (ceres and AliceVision).
