### ISSUE TITLE
Processing JPEG from MP4

### ISSUE THREAD

**Issue by RomainDG** [alicevision/AliceVision#847]
Hello everyone,

I'm trying to get a 3D model from pictures extracted from a video. Here is the complete process:

- I shoot a video of an object with an Iphone X
- From Blender 'Video Sequencer', I extract several picture in JPEG format. 
- I input those pictures into Meshroom and start the process

The issues:
Intrinsics are unknown. It can't recognize the pictures are from an Iphone X. It works when I directly upload it from the phone, but not extacted from the video it seems.
When computing to 'Structure from motion', only the first 10 pictures will be accepted. Does not matter if I input 100 or 50 pictures.

Is there some step i'm missing? I tried to manually input the correct Iphone X intrinsic on the node, but it just made it fail.

![Blender video sequencer](https://user-images.githubusercontent.com/45511160/88921656-76a03580-d2a1-11ea-9548-75cc620dbb57.png)

![Failed recognition](https://user-images.githubusercontent.com/45511160/88921885-d991cc80-d2a1-11ea-99af-8c9a0cf38639.png)

**Comment by natowi** [comment]
In the CameraInit node you can modify the camera values. Open a new project and import an image with metadata to see hw it is supposed to look like.

**Comment by RomainDG** [comment]
> In the CameraInit node you can modify the camera values. Open a new project and import an image with metadata to see how it is supposed to look like. You could also use the KeyframeExtraction node to specify the camera parameters and extract frames from your mp4 video.

Thanks for the answe Natowi!
I tried filling up manually the exact same information on the CameraInit node, it ended up in failing (Red bar, I will try to redo it and post the log here later)

I will get on the KeyframeExtraction node now, to see if this can resolve the issue.

**Comment by RomainDG** [comment]
The Keyframe selection is working wonders!

I had to disable the 'Use sharpness selection', or I would only get 8 pictures. You can see the result right here:

![Succes Keyframeselection](https://user-images.githubusercontent.com/45511160/89019246-9a21b980-d34f-11ea-85f8-bb4d84037e0b.png)

Thanks a lot for your help natowi.

**Comment by natowi** [comment]
> I had to disable the 'Use sharpness selection'

Yes, maybe we should disable this by default

Good to see that everything worked
