### ISSUE TITLE
Implement more helpful error message when CUDA is not installed

### ISSUE THREAD

**Issue by nschapeler** [alicevision/AliceVision#870]
I recently opened an [issue](https://github.com/alicevision/AliceVision/issues/869) where I was getting the error message "Failed to estimate space from SfM: The space bounding box is too small" for a, to me, inexplicable reason, as the same images had worked with no change the just a few days prior. It turns out, the problem was my computer having updated and thereby uninstalling CUDA. 

I believe in such a case a more fitting error message would be helpful, as checking for CUDA not being installed is not very difficult from AliceVision's point of view and very easy to fix for the user.

**Comment by fabiencastan** [comment]
Hi @nschapeler,
Thanks for the feedback.

1/ This is strange as the "estimate space from SfM", rely only on the SfM results (which does not use GPU).
Could you send the log of the SfM node (from the scene with the failure)?

2/ The other strange thing is that to compute the Meshing, the DepthMap needs to be computed which cannot succeed without proper CUDA installation.
Could you send the log of one chunk of the DepthMap node (from the scene with the failure)?

**Comment by nschapeler** [comment]
Hi @fabiencastan,

Thanks for getting back to me so fast. I would love to send you the logs for both of these, but I've been trying to recreate the problems I had been having by uninstalling CUDA, but have been unable to recreate the same issue. Although at least that indicates that my problems had been caused by some other factor and just coincidentally fixed themselves around the same time as I re-installed CUDA. Sorry about that!
