### ISSUE TITLE
aliceVision_utils_split360Images encounters error loading shared library linux.

### ISSUE THREAD

**Issue by jcc10** [alicevision/AliceVision#883]
I have been attempting to use `aliceVision_utils_split360Images` to use panoramic images to generate models. ( [meshroom/199](https://github.com/alicevision/meshroom/issues/199#issuecomment-506746884) , [meshroom/526](https://github.com/alicevision/meshroom/issues/526#issuecomment-505829215) )

When running the command `./Meshroom-2019.2.0/aliceVision/bin/aliceVision_utils_split360Images` I receive the following error:
```
./Meshroom-2019.2.0/aliceVision/bin/aliceVision_utils_split360Images: error while loading shared libraries: libaliceVision_image.so.2: cannot open shared object file: No such file or directory
```

I was unsure if this issue was in downstream Meshroom or here, I figure that Meshroom takes the CI from here so I opened the bug here.

**Comment by grische** [comment]
@jcc10 the error means that your system cannot find the libraries.

In my case, the library `libaliceVision_image.so.2` is in `/home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libaliceVision_image.so.2`.

If you are using Linux, you can then (temporarily) tell your operating system to also look in this folder:
```sh
export LD_LIBRARY_PATH=/home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/
# in case of MacOS check out `DYLD_LIBRARY_PATH`
```

Now your binary should work just fine, but you can also manually verify it with `ldd`:
```
ldd Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/bin/aliceVision_utils_split360Images
        linux-vdso.so.1 (0x00007ffcbb1a2000)
        libaliceVision_image.so.2 => /home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libaliceVision_image.so.2 (0x00007f7a87de1000)
        libOpenImageIO.so.2.2 => /home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libOpenImageIO.so.2.2 (0x00007f7a87246000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7a87042000)
        libboost_program_options.so.1.70.0 => /home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libboost_program_options.so.1.70.0 (0x00007f7a86db4000)
        libboost_filesystem.so.1.70.0 => /home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libboost_filesystem.so.1.70.0 (0x00007f7a86b89000)
        libaliceVision_system.so.2 => /home/user/Downloads/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/lib/libaliceVision_system.so.2 (0x00007f7a86954000)
        ... (and many more) ...
```

To avoid that problem, programs like Blender for example, simply bake all those libraries into their binary.
