### ISSUE TITLE
Ubuntu build - error : AliceVision is built without Alembic support

### ISSUE THREAD

**Issue by remmel** [alicevision/AliceVision#902]
Hi,

I'm trying to build AliceVision on Ubuntu 20.04 LTS
But when using `aliceVision_prepareDenseScene` (via Meshroom), I get the following error :
`Cannot load the ABC file: "[...]/sfm.abc", AliceVision is built without Alembic support.`

I built alicevision with following command  
`cmake -DAlembic_DIR:PATH=/home/remmel/workspace/alembic/lib/Alembic -DCMAKE_BUILD_TYPE=Release . ../AliceVision` 
(tried also with `-DAlembic_DIR=/home/remmel/workspace/alembic/lib/Alembic`  `-DALICEVISION_USE_ALEMBIC=ON`) 
but also get that message :
```
-- Could NOT find Alembic (missing: Alembic_DIR)
CMake Error at src/CMakeLists.txt:565 (message):
  Failed to find Alembic.
```
[Full logs alicevisioncmakelog.txt](https://github.com/alicevision/AliceVision/files/5276086/alicevisioncmakelog.txt)

I installed Alambic via `pip3 install alembic` which is probably useless and also clone the sources :  
 `/home/remmel/workspace$  git clone https://github.com/alembic/alembic.git`
I'm following the [install doc](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md) which indicates :
`ALICEVISION_USE_ALEMBIC (default AUTO) Build with Alembic file format support (required version >= 1.7). -DAlembic_DIR:PATH=/path/to/alembic/install/lib/cmake/Alembic/ (where AlembicConfig.cmake can be found)`
But no `AlembicConfig.cmake` can be found, only `AlembicConfig.cmake.in`
```
$ ls /home/remmel/workspace/alembic/lib/Alembic
Abc  AbcCollection  AbcCoreAbstract  AbcCoreFactory  AbcCoreHDF5  AbcCoreLayer  AbcCoreOgawa  AbcGeom  AbcMaterial  AlembicConfig.cmake.in  CMakeLists.txt  Ogawa  Util
```

*Thus how to use build AliceVision with Alembic support?*

I also tried using git tag 1.7.0 or 1.7.10 for Alembic and duplicating file AlembicConfig.cmake.in into AlembicConfig.cmake Duplicating file make disappear that error `Could NOT find Alembic (missing: Alembic_DIR)` but get instead:
```
CMake Warning at src/CMakeLists.txt:555 (find_package):
  Could not find a configuration file for package "Alembic" that is
  compatible with requested version "1.7.0".

  The following configuration files were considered but not accepted:

    /home/remmel/workspace/alembic/lib/Alembic/AlembicConfig.cmake, version: unknown
```
I also tried to use [alembic-1.7.10.tgz](https://github.com/alicevision/AliceVisionDependencies/releases/download/alembic-1.7.10/alembic-1.7.10.tgz) for Travis found in [ci/install-dependencies.sh](https://github.com/alicevision/AliceVision/blob/develop/ci/install-dependencies.sh) which has proper `AlembicConfig.cmake` and `AlembicConfigVersion.cmake` 

By the way I installed thoses differents libs to build the project on my fresh installed Ubuntu 20.04 LTS : 
- `sudo apt-get install build-essential libopenexr-dev libboost-all-dev cmake libopenimageio-dev libeigen3-dev libceres-dev doxygen python3-sphinx`
- Download and install Geogram-x.y.z.deb from https://gforge.inria.fr/frs/?group_id=5833
- CUDA toolkit : https://developer.nvidia.com/cuda-downloads?target_os=Linux

Thanks! :)

**Comment by simogasp** [comment]
Hi, you have to build and install alembic.
From the alembic root directory, create a `build` directory and
```
mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH=<a path where u want to install>
```
then you can do `make install`.
Also consider the instruction in the readme of the repository
https://github.com/alicevision/alembic/blob/master/README.txt

Once you have installed, the `-DAlembic_DIR:PATH` must point to `<a path where u want to install>/lib/Alembic`
