### ISSUE TITLE
LG G4 Sensor not recognized

### ISSUE THREAD

**Issue by bes1002t** [alicevision/AliceVision#906]
Hi,

I tried to compile alicevision by myself but there are multiple errors and I don't wanted to spend even more time with this, that's why I've downloaded Meshroom for x64 Linux: https://github.com/alicevision/meshroom/releases/tag/v2019.2.0

I used the LG G4 to take some photos and checked the sensor database before (https://github.com/alicevision/AliceVision/blob/c2f4e66a9632128f4028a03e027dcd0329c8df64/src/aliceVision/sensorDB/cameraSensors.db) and there is an entry for my phone:
Lg;Lg G4;5.95;devicespecifications

Unfortunately the sensor size is not recognized when I import the images into Meshroom:
"- SensorWidth: undefined"

I think the issue is that 'Lg G4' is not the real name of this model, but 'LG-H815'.

Is there a way I could test it? I've changed my sensorDB manually, but it seems this does not have any effect in meshroom.

**Comment by natowi** [comment]
You need to check the Image Metadata and use the Model and Make information from there. Sometimes the Make differs from the official device name. Try adding Lg;LG-H815;5.95;devicespecifications

**Comment by bes1002t** [comment]
@natowi sorry for the confusion. I meant the model in the image EXIF data is 'LG-H815'. So I think the entry in database is wrong.

I already changed the the sensor db and added "Lg;LG-H815;5.95;devicespecifications". But after your post I noticed that it has to be "LG Electronics;LG-H815;5.95;devicespecifications".

Now the images are working without any warning, so thanks. :)

**Comment by natowi** [comment]
> Is there a need for a pull request?

That would be good :)
