### ISSUE TITLE
Build failure on Pop OS / Ubuntu 20

### ISSUE THREAD

**Issue by jcc10** [alicevision/AliceVision#919]
After getting tired of unable to install deps via vcpkg I finally got around to just doing the whole build tree by hand.

```
...
** AliceVision version: 2.3.1
** Target architecture: zen
** Build Shared libs: ON
** Build SfM part: ON
** Build MVS part: ON
** Build AliceVision tests: OFF
** Build AliceVision documentation: 1
** Build AliceVision samples programs: OFF
** Build AliceVision+OpenCV samples programs: 0
** Build UncertaintyTE: 1
** Build MeshSDFilter: 1
** Build Alembic exporter: 0
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: 1
** Use CUDA: 1
** Use OpenCV SIFT features: 0
** Use PopSift feature extractor: 1
** Use CCTAG markers: 0
** Use OpenGV for rig localization: 1


-- EIGEN: 3.3.7
-- CERES: 1.14.0
-- FLANN: 1.8.4 (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)


-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
...
```

[broken build.log](https://github.com/alicevision/AliceVision/files/5387603/broken.build.log)

Any help with getting this to compile?

**Comment by fabiencastan** [comment]
The error seems to be in ceres. Maybe you could use a more recent version.

You could look at the docker files as an example to build:
https://github.com/alicevision/AliceVision/blob/develop/docker/Dockerfile_ubuntu_deps

**Comment by jcc10** [comment]
I think the issue is that one of the deps itself depends on cres and told me to simply fork it. (Which gets v2.0 not 1.14)
Re-building from that step, will close if that fixes it.

**Comment by jcc10** [comment]
Needed to downgrade CERES. Thanks for the help @fabiencastan !
