### ISSUE TITLE
ROG phone 2 missing in cameraSensors.db

### ISSUE THREAD

**Issue by 100percentARA** [alicevision/AliceVision#924]
As in the title. Is giving me issues with the meshroom photo stuff

**Comment by 100percentARA** [comment]
I was reading #491 , and #179 but I'm unsure what I should be putting for the second section for the Model ...

So far I've put  `Asus;Asus ROG Phone 12.7;devicespecifications`

**Comment by natowi** [comment]
No, Meshroom gives you a hint with the Make and model:

`ASUS;ASUS_I001DC;12.7;devicespecifications `

should work. (Image metadata and sensordatabase entry need to match)

**Comment by 100percentARA** [comment]
Thanks for the help!
