### ISSUE TITLE
Docker build errors

### ISSUE THREAD

**Issue by Misterdudeman** [alicevision/AliceVision#926]
I'm getting an error when trying to build Alicevision Docker container with the build_ubuntu.sh script.

I'm building on Ubuntu 20.04 with CUDA 11.0

The error I am getting is right after this:
```[ 63%] Completed 'geogram'```
```[ 63%] Built target geogram```

```make: *** [Makefile:103: all] Error 2```

```The command '/bin/sh -c cmake --build . -j "$(nproc)" &&     mv "${AV_INSTALL}/bin" "${AV_INSTALL}/bin-deps" &&     rm -rf "${AV_BUILD}"' returned a non-zero code: 2 ```

**Comment by bariomalotelli** [comment]
I have your exact same problem.
Trying to build with docker on Ubuntu 20.04 and CUDA 11.1

**Comment by bariomalotelli** [comment]
I made it work with Ubuntu 18.04 and CUDA 10.0.

**Comment by stellarpower** [comment]
I'm getting the same, but it stops at the 'opengv' phase, or the 'suitesparse' phase. I've forked the master branch as of b8e58ad7, although I see some CI failures at this commit.

**Comment by simogasp** [comment]
I suggest to try with `-j 2`, if you use all the available threads you may run out of resources

**Comment by stellarpower** [comment]
I'll try it, however, this usually comes up after the majority of the dependencies have built successfully, and, I'm now building it on a machine with 32 cores. I'd have thought it might fail earlier if resources were an issue.

30 Sep 2021 11:50:40 Simone Gasparini ***@***.***>:

**Comment by simogasp** [comment]
Yes, that -j will make the libs to be built in parallel and each of them in parallel as well. So at some points when there are many compilation heavy libs that are building in parallel, each demanding all available threads, then u may run out of resources. Otherwise try to find in the log which one is failing and its error message.

**Comment by stellarpower** [comment]
Thanks - problem appears unrelated but using just two threads meant I could see the error - I had dozens and dozens of pages of warnings coming out of Eigen before so couldn't see anything evident. Hate how Make defaults to this - I want the error that stopped the build down at the bottom!
