### ISSUE TITLE
Can't find camera sensor size

### ISSUE THREAD

**Issue by turret001** [alicevision/AliceVision#927]
Hello! After reading #491 I've noticed that my phone camera was not in the cameraSensors.db. 

I tried visiting the website that was mentioned in #491 but I couldn't find the sensor size for my phone camera. Can someone please help me out?

This is my phone: https://www.devicespecifications.com/en/model/9e0a44db

I need the third and fourth parameters for cameraSensors.db  Samsung;SM-N9500;**?**;**?**

**Comment by natowi** [comment]
Samsung;Samsung Galaxy S8;5.75;usercontribution

What does the image metadata say on the model name?

**Comment by turret001** [comment]
says this:
![image](https://user-images.githubusercontent.com/24281147/98143431-222cd780-1eda-11eb-8812-20bd094c04aa.png)

odd, shutter icon was appearing Red, now it's yellow.
My phone is Note 8, not S8, should I still copy and paste that one?

**Comment by natowi** [comment]
As you can see Meshroom estimates the Sensor width to be 5.72
The sensor width for the S8 is 5.75, so we can guess that the S8 has the same camera than the S8 note.

Samsung;SM-N9500;5.75;usercontribution

**Comment by turret001** [comment]
> As you can see Meshroom estimates the Sensor width to be 5.72
> The sensor width for the S8 is 5.75, so we can guess that the S8 has the same camera than the S8 note.
> 
> Samsung;SM-N9500;5.75;usercontribution

awesome! thank you so much 👍
