### ISSUE TITLE
aliceVision_utils_split360Images.exe output not suitable for Multi Camera Rig feature

### ISSUE THREAD

**Issue by shuttercat** [alicevision/AliceVision#941]
While the aliceVision_utils_split360Images.exe tool performs well for slicing the output from my Insta360 One R, it seems that it would be an excellent opportunity to generate the requirements for Multi Camera Rig detection in Meshroom, e.g.:

- Output directory structure and filenames 
- generated EXIF serial numbers for each virtual pose from the split
- correct+matching EXIF date/time

**Comment by Archviz360** [comment]
i have aproblem. how do i split 360 images into an output folder?? ERROR: the option '--output' is required but missing
Usage:
how do i solve this??
