### ISSUE TITLE
Installation in arch64+cuda10 Jetson SBC

### ISSUE THREAD

**Issue by FPSychotic** [alicevision/AliceVision#942]
Hi, I have a Jetson Xavier NX which has 6Core arch64 CPU and nVidia GPU, 7.x rated power, Volta artichecture and Tensor cores, Cuda 10 and cuDNN support..
Do you know or think that I will be able to complete compile it successfully? 

Regards and thanks by share.

**Comment by natowi** [comment]
Here is the Google Groups discussion https://groups.google.com/g/alicevision/c/dP-zKpvzWBo/m/EnSIsvv5AQAJ

If you are familiar with compiling programs on arm you may be able to get it to work, but expect some issues with dependencies you need to solve.

I always wanted to try this myself, but I don´t have a jetson.

**Comment by FPSychotic** [comment]
Thanks, I will joint to the group. I will try install and I will keep informed.
As I understand Arm is not a native target platform so I close the issue as it is not such, I will keep informed of any advance in both and reopen the issue if it is needed.

Thank you and take care

**Comment by simogasp** [comment]
Did u manage to build with arm?

**Comment by natowi** [comment]
https://github.com/alicevision/geogram/issues/19

https://forums.developer.nvidia.com/t/running-meshroom-on-2gb-jetson-nano/173469

https://projects.eng.uci.edu/projects/2019-2020/integrated-platform-hyperspectral-3d-photogrammetry-biomedical-applications
(They probably did not test it on the Jetson in the end)
