### ISSUE TITLE
Sony A7R has wrong sensor size

### ISSUE THREAD

**Issue by spuder** [alicevision/AliceVision#943]
According to the database, the sony has a 35.9 mm sensor

https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db#L5834-L5836

```
Sony;Sony a7R;35.9;dpreview
Sony;Sony a7R II;35.9;dpreview
Sony;Sony a7R III;35.9;dpreview
```

But if you compare that with Sonys website for the A7R, they list a 35.7mm sensor

https://www.sony.com/electronics/interchangeable-lens-cameras/ilce-7rm4#product_details_default

```
35.7 x 23.8 mm	42.91 mm	849.66 mm²	3:2
```

Which is correct? 35.9 that AliceVision has in the database or 35.7 that is listed on Sonys website?

**Comment by natowi** [comment]
The information on the official website should be reliable. The value 35.9 is probably an estimation. The difference of 0.2 is not a big deal but it would be good to fix the value.
