### ISSUE TITLE
SfMTransform: The camera "DJI_0001.JPG" exists in the sfmData but is not reconstructed

### ISSUE THREAD

**Issue by tmhab** [alicevision/AliceVision#948]
SFMTransform node with transformation mode "from single image" gives me: "The camera "DJI_0001.JPG" exists in the sfmData but is not reconstructed" and the subsequent nodes are downgraded to status "none".

I am running the graph through meshroom_compute on the commandline.

![graph](https://user-images.githubusercontent.com/64837013/101604264-f634d280-3a00-11eb-9864-70fe34ce6cc0.PNG)
![sfmtt-node](https://user-images.githubusercontent.com/64837013/101604276-f8972c80-3a00-11eb-8b47-8d498e9bf186.PNG)

**Comment by ChemicalXandco** [comment]
Is `DJI_0001.JPG` reconstructed? If not then you will need to choose a different image to transform to.

**Comment by tmhab** [comment]
How do I tell if it is reconstructed?

**Comment by natowi** [comment]
When you click on an image in the image panel, the camera is highlighted in the 3D SFM viewer. If not, the camera has not been reconstructed. Choose another one.

**Comment by tmhab** [comment]
Will this be true even if I haven't run the graph in Meshroom? (Haven't clicked the green "Start" button" I am only using Meshroom to create the .mg file, which I am running through meshroom_compute.

**Comment by natowi** [comment]
You need to make sure the image you use for the transformation is reconstructed. If all your images face in the same direction (drone footage), it does not matter which image you use, you could try to use a wildcard like `*.JPG` (not sure if it is supported with _from_single_camera_) or try _auto_from cameras_

**Comment by tmhab** [comment]
It is drone footage that I am working with but the first and last images are taken from the ground; the drone standing on the ground, looking straight ahead. I am investigating if that first image could be used as a frame of reference (idk, using camera meta data about orientation) so that the scene is transformed correctly unlike previous results without the SfMTransform node where it is flipped almost on its head.

Maybe there are other ways of doing this...

**Comment by natowi** [comment]
You could print out CCTAG markers and make sure they are visible in multiple images. https://github.com/alicevision/meshroom/wiki/CCTAG-scaling (second part)
