### ISSUE TITLE
How can i use this AliceVision framework??

### ISSUE THREAD

**Issue by tjdgns0258** [alicevision/AliceVision#959]
Hi, 

I'm sorry for asking these quetions but how can i use this software??

I installed all dependencies by vcpkg and build process also perfectly done.

Now I can see various Alicevision project with software - pipeline folder in VS.

Can i running this build project such as meshroom??

If i want to check the results of each pipelines, what shoud i do??

Please someone tell me how to use this framework I'm new with this kind of Opensource project.

**Comment by fabiencastan** [comment]
You could the used pre-compiled binaries to start testing Meshroom.
See the [Meshroom manual](https://meshroom-manual.readthedocs.io) to see how to start using it.

**Comment by tjdgns0258** [comment]
@fabiencastan yeah I already know about the Meshroom and have read the Meshroom manual.

I mean

If i want to use these pipelines functions in other software such as Unity3D.

Is it correct to use Alicevision framework or should i change it to meshroom??

**Comment by fabiencastan** [comment]
If you are in C++, you can use AliceVision directly.
Which one to use or which level of integration is needed depends on what you are trying to do.
For instance, the SideFX integration of AliceVision in Houdini use directly the AliceVision command lines.

**Comment by tjdgns0258** [comment]
@fabiencastan Oh thanks so much for your advice.

I don't know exactly how to use it right now, but I'll take a closer look at the case of SideFX you mentioned.

Once again, thank you so much, and Happy New Year!
