### ISSUE TITLE
Cuda 11

### ISSUE THREAD

**Issue by ahemberger** [alicevision/AliceVision#965]
Hi, I'm trying to build Alicevision from a very fresh setup, using the latest CUDA downloaded from Nvidia and Visual Studio 2019. When I try to follow the install doc, I get errors when trying to install cuda-related packages via vcpkg:

-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:69 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  ports/cuda/portfile.cmake:9 (vcpkg_find_cuda)
  scripts/ports.cmake:136 (include)

Error: Building package cuda:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

To be clear, Cuda 11.2 is currently installed, but the latest cuda package available via vcpkg seems notably older, and it's unclear to me how to resolve one with the other.

**Comment by ahemberger** [comment]
To add to this: I tried forging ahead with my build without resoling this CUDA issue, as the doc states that cuda is optional. The remainder of the vcpkg installs seemed to run without issue. However, when I try to then run cmake, I get (after a lot of other output and lots of boost warnings) this error:


CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
CMake Error at src/CMakeLists.txt:722 (message):
  Failed to find CUDA (>= 7.0).

Which seems to suggest cuda IS in fact required? Or am I inadvertently misconfiguring something? I'm just following the step-by-step [here](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md).

**Comment by simogasp** [comment]
vcpkg does not install cuda, it just verifies that is installed and generates the relevant variables.
You have to manually install cuda before.

**Comment by ahemberger** [comment]
Hm; I trust you're right, but I suppose that leaves me wondering:
--what is happening when I do "vcpkg install cuda"?
--what more I need to do - beyond running Nvidia's CUDA installer - to make it so that vcpkg can find it?

(I realize that latter question is not germane to this Alicevision project itself and is a broader "i need to google around to figure this out" type of thing).

**Comment by ahemberger** [comment]
*facepalm*

To close this loop, in case anyone else runs into this: I found that I needed to restart my command prompt after installing Cuda 11, to refresh the environment variables needed by vcpkg. Doing so allows me to proceed with installing cuda via vcpkg, as well as all related packages. 

Thanks much for the clue, @simogasp!
