### ISSUE TITLE
Linker error undefined reference on Arch Linux 

### ISSUE THREAD

**Issue by ultramango** [alicevision/AliceVision#974]
I'm having problems compiling AliceVision on Arch Linux. I get linker error with undefined reference. I followed installation guide in `INSTALL.md` file (chapter "Building the project using external dependencies"). 
```
> make -j7
...
[ 68%] Linking CXX executable ../../../Linux-x86_64/aliceVision_meshResampling
/usr/bin/ld: ../../../Linux-x86_64/libaliceVision_feature.so.2.3: undefined reference to `__fatbinwrap_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37'
collect2: error: ld returned 1 exit status
```

Output from `cmake`: https://gist.github.com/ultramango/aef2efa3bd29474ef584972d9aac5219

**Comment by simogasp** [comment]
can you post the log of
```
make VERBOSE=1
```
It could be a conflict of different versions of cuda on the machine

**Comment by ultramango** [comment]
Thanks to you and bartus (https://aur.archlinux.org/packages/alice-vision/) I was able to find the root of the problem - my PopSift was compiled with CUDA 10, after recompiling it now everything builds fine. I'll close the issue.

If you still need the verbose output - let me know.

**Comment by kellergoech** [comment]
I don't get it it was compiled against cuda 10 and you recompiled it with Cuda 10, so what's the difference?

**Comment by ultramango** [comment]
> ... and you recompiled it with Cuda 10 ...

If you check the output from `cmak` I tried to compile it with CUDA 11:
```bash
...
-- CUDA Version is 11.2
...
```

PopSift was compiled with CUDA 10, so recompiling it to use CUDA 11 helped.
