### ISSUE TITLE
'FIND_PACKAGE(Eigen QUIET)' should be 'FIND_PACKAGE(Eigen3 QUIET)'

### ISSUE THREAD

**Issue by yurivict** [alicevision/AliceVision#990]
https://github.com/alicevision/AliceVision/blob/develop/src/cmake/FindOpenGV.cmake#L30

**Comment by simogasp** [comment]
u're right, but we should rather get rid of this and use the moder cmake approach with targets to import the library now that https://github.com/laurentkneip/opengv/pull/45 has been merged
