### ISSUE TITLE
Compilation failure on file test 'merom', ' sgemm_', 'cheev_'

### ISSUE THREAD

**Issue by hzhshok** [alicevision/AliceVision#991]
Compilation failed on the following steps, and it showed the function test failed for 'sgemm_', 'cheev_' with undefined reference to ....

What I guessed and checked something please see the last for the failure of 'undefined reference'.

-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Configuring incomplete, errors occurred!
See also "/media/zhansheng/disk-d/workshop/prj/opensoure/build/CMakeFiles/CMakeOutput.log".
See also "/media/zhansheng/disk-d/workshop/prj/opensoure/build/CMakeFiles/CMakeError.log".

Error inside this /media/zhansheng/disk-d/workshop/prj/opensoure/build/CMakeFiles/CMakeError.log: 
"/media/zhansheng/disk-d/workshop/prj/opensoure/build/CMakeFiles/CMakeError.log".
...
 Source file was:
     int main() { return 0;}
     Performing C++ SOURCE FILE Test check_cxx_compiler_flag__march_merom failed with the following output:
...
/usr/bin/cc   -Dcheck_c_compiler_flag__march_merom   -march=merom -o CMakeFiles/cmTC_515bc.dir/src.c.o   -c /media/zhansheng/disk-d/workshop/prj/opensoure/build/CMakeFiles/CMakeTmp/src.c
     cc1: error: bad value (‘merom’) for ‘-march=’ switch

...
/usr/bin/ld: CMakeFiles/cmTC_71f1f.dir/CheckFunctionExists.c.o: in function `main':
     CheckFunctionExists.c:(.text+0x14): undefined reference to `sgemm_'
...
/usr/bin/cc  -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp -DCHECK_FUNCTION_EXISTS=cheev_    CMakeFiles/cmTC_95a44.dir/CheckFunctionExists.c.o  -o cmTC_95a44  /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so
     CheckFunctionExists.c:(.text+0x14): undefined reference to `cheev_'

I guess that maybe it is the version of lapack/blas library, but lapack showed the following, which have that function, but not involved, so **lapack needs to be involved inside makefile**?
And from the above we can see that it not involved lapack, so that is saying it wish libatlas.so have comprised that symbols.
In addition, **sgemm_ should be exist inside libblas.s**o.

**nm -D --defined-only /usr/lib/x86_64-linux-gnu/atlas/liblapack.so | grep cheev**
00000000000cb180 T cheev_
00000000000cb6c0 T cheev_2stage_
00000000000cbcd0 T cheevd_
00000000000cc470 T cheevd_2stage_
00000000000ccd30 T cheevr_
00000000000cdfe0 T cheevr_2stage_
00000000000cf2a0 T cheevx_
00000000000d0310 T cheevx_2stage_

**nm -D --defined-only /usr/lib/x86_64-linux-gnu/atlas/libblas.so | grep sgemm_**
0000000000034b50 T atl_f77wrap_sgemm_
0000000000361570 T sgemm_

**Comment by simogasp** [comment]
Cmake seems to be using different libraries than the ones u checked
```
CMakeFiles/cmTC_95a44.dir/CheckFunctionExists.c.o -o cmTC_95a44 /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so
CheckFunctionExists.c:(.text+0x14): undefined reference to `cheev_'
```

`usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so`

Can u check those?

**Comment by hzhshok** [comment]
Thks for your quick comment!

nm -D --defined-only /usr/lib/x86_64-linux-gnu/libf77blas.so | grep sgemm
000000000000c370 T atl_f77wrap_sgemm_
000000000000b0d0 T sgemm_

but, no cheev_ symbol.

And i install atlas used by ceres,
ii  libatlas-base-dev:amd64                       3.10.3-8ubuntu7                       amd64        Automatically Tuned Linear Algebra Software, generic static
ii  libatlas3-base:amd64                          3.10.3-8ubuntu7                       amd64        Automatically Tuned Linear Algebra Software, generic shared

and atlas involved blas and lapack as the following,
ls -al /usr/lib/x86_64-linux-gnu/atlas/lib
libblas.a            libblas.so.3         liblapack.a          liblapack.so.3       
libblas.so           libblas.so.3.10.3    liblapack.so         liblapack.so.3.10.3

I guessed the problem is from my installs for atlas and openblas(forgot if it has cblas), but, actually i removed openblas, 

and the blas refered to alts: 
ls -al /etc/alternatives/lib
libblas.a-x86_64-linux-gnu       liblapack.a-x86_64-linux-gnu     libmpi++.so-x86_64-linux-gnu     
libblas.so.3-x86_64-linux-gnu    liblapack.so.3-x86_64-linux-gnu  libmpi.so-x86_64-linux-gnu       
libblas.so-x86_64-linux-gnu      liblapack.so-x86_64-linux-gnu    libpsm_infinipath.so.1

ls -al /etc/alternatives/libblas.so-x86_64-linux-gnu
lrwxrwxrwx 1 root root 42 2月  20 10:35 /etc/alternatives/libblas.so-x86_64-linux-gnu -> /usr/lib/x86_64-linux-gnu/atlas/libblas.so

But, i still do't know which step(which cmakelist.txt) triggered that function test to find which software triggered this check, 
Now I just check cmakelist.txt one by on( now src/cmakelist.txt) to check which module/software trigger to focus on the problem source, but not found. 

Regards

**Comment by hzhshok** [comment]
By the way, maybe the problem is other dependence which used different blas to trigger the check(e.g. openblas), so the my first goal i to find which library trigger that check(because i install openblas/alts a long long ago for other application).

**Comment by simogasp** [comment]
ah sorry my bad, i didn't notice that you were showing the error log file.
Those errors are ok, it's just cmake checking whether things are supported or not.
If the cmake process ends fine you don't have to consider those errors.
In case report the errors that are reported at the termina if any.

**Comment by hzhshok** [comment]
The cmake failed to configure the total configuration the following terminal output, and the CMakeError.log is as what i posted.

So, could you show me which cmakelist(or component) trigger that check? because i can check by manually modifying cmakelist  once i know the specific cmakefile/component, because is hard to accurately know the specific reason(Mixed versions or mismatched versions).

The terminal output: 
- CERES: 2.0.0
-- FLANN: 1.8.4 (internal)
-- CLP: 1.15.11 (internal)
-- COINUTILS: 2.9.3 (internal)
-- OSI: 0.106.10 (internal)
-- LEMON: 1.3 (internal)
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
Have added the dependency subdirectories
Finished the installation of configfile
-- Configuring incomplete, errors occurred!
**See also "/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeOutput.log".
See also "/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeError.log".**


**CMakeOutput.log showed** the last lines, 
Determining size of long long passed with the following output:
   1742 Change Dir: /media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp
   1743 
   1744 Run Build Command(s):/usr/bin/make cmTC_9df3a/fast && /usr/bin/make -f CMakeFiles/cmTC_9df3a.dir/build.make CMakeFiles/cmTC_9df3a.dir/build
   1745 make[1]: Entering directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'
   1746 Building C object CMakeFiles/cmTC_9df3a.dir/LONG_LONG.c.o
   1747 /usr/bin/cc   -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp    -o CMakeFiles/cmTC_9df3a.dir/LONG_LONG.c.o   -c /media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CheckTypeSize/LONG_LONG.c
   1748 Linking C executable cmTC_9df3a
   1749 /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9df3a.dir/link.txt --verbose=1
   1750 /usr/bin/cc  -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp     -rdynamic CMakeFiles/cmTC_9df3a.dir/LONG_LONG.c.o  -o cmTC_9df3a
   1751 make[1]: Leaving directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'


**CMakeErr.log** showed the lines of the last:
...
...
     36 Run Build Command(s):/usr/bin/make cmTC_0be6f/fast && /usr/bin/make -f CMakeFiles/cmTC_0be6f.dir/build.make CMakeFiles/cmTC_0be6f.dir/build
     37 make[1]: Entering directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'
     38 Building C object CMakeFiles/cmTC_0be6f.dir/CheckFunctionExists.c.o
     39 /usr/bin/cc   -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp -DCHECK_FUNCTION_EXISTS=sgemm_   -o CMakeFiles/cmTC_0be6f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
     40 Linking C executable cmTC_0be6f
     41 /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0be6f.dir/link.txt --verbose=1
     42 /usr/bin/cc  -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp -DCHECK_FUNCTION_EXISTS=sgemm_    CMakeFiles/cmTC_0be6f.dir/CheckFunctionExists.c.o  -o cmTC_0be6f
     43 /usr/bin/ld: CMakeFiles/cmTC_0be6f.dir/CheckFunctionExists.c.o: in function `main':
     44 CheckFunctionExists.c:(.text+0x14): undefined reference to `sgemm_'
     45 collect2: error: ld returned 1 exit status
     46 make[1]: *** [CMakeFiles/cmTC_0be6f.dir/build.make:87: cmTC_0be6f] Error 1
     47 make[1]: Leaving directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'
     48 make: *** [Makefile:121: cmTC_0be6f/fast] Error 2
     49 
     50 
     51 
     52 Determining if the function cheev_ exists failed with the following output:
     53 Change Dir: /media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp
     54 
     55 Run Build Command(s):/usr/bin/make cmTC_6194f/fast && /usr/bin/make -f CMakeFiles/cmTC_6194f.dir/build.make CMakeFiles/cmTC_6194f.dir/build
     56 make[1]: Entering directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'
     57 Building C object CMakeFiles/cmTC_6194f.dir/CheckFunctionExists.c.o
     58 /usr/bin/cc   -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp -DCHECK_FUNCTION_EXISTS=cheev_   -o CMakeFiles/cmTC_6194f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
     59 Linking C executable cmTC_6194f
     60 /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6194f.dir/link.txt --verbose=1
     61 /usr/bin/cc  -march=core2 -msse2 -msse3 -mssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -Werror=return-type -Werror=switch -Werror=return-local-addr -fopenmp -DCHECK_FUNCTION_EXISTS=cheev_    CMakeFiles/cmTC_6194f.dir/CheckFunctionExists.c.o  -o cmTC_6194f  /usr/lib/x86_64-linux-gnu/libf77blas.so /usr/lib/x86_64-linux-gnu/libatlas.so
     62 /usr/bin/ld: CMakeFiles/cmTC_6194f.dir/CheckFunctionExists.c.o: in function `main':
     63 CheckFunctionExists.c:(.text+0x14): undefined reference to `cheev_'
     64 collect2: error: ld returned 1 exit status
     65 make[1]: *** [CMakeFiles/cmTC_6194f.dir/build.make:89: cmTC_6194f] Error 1
     66 make[1]: Leaving directory '/media/zhansheng/disk-d/workshop/prj/opensoure/AliceVision/build/CMakeFiles/CMakeTmp'
     67 make: *** [Makefile:121: cmTC_6194f/fast] Error 2

Regards

**Comment by simogasp** [comment]
Try to find the error shown in the terminal, it must be before those lines CERES etc you are showing.
If you can just copy paste the whole terminal output from the beginning.
The errors in CMakeErr are "normal", I have almost a similar output on my side, those are checks that cmake perform to determine the features of the compiler.

**Comment by hzhshok** [comment]
I got good news i passed cmake procedure with disabling cuda option(ALICEVISION_USE_CUDA) off and it passed.

Once i suspected that, but i found that cuda option is optional dependence, so ignored that, recently i compared two cmake log(one for cuda, and one for this one), but, excluding cuda is explicit nothing found, and i also know that ALICEVISION_USE_CUDA  with default ON, but not thought which broken cmake step(since it is optional option, then default status should not change the optional behavior).
Just as a hint fro the new guy:
a. Check the options and default value no matter it is dependence or optional one.
b. My case is just from ALICEVISION_USE_CUDA with my desktop without GPU.
    For sure also other issues, please refer to all other issues as reference.

Thanks simogasp for your lots help!

Regards
